### ISSUE TITLE
Support changing transponders via signal (SIGINFO?)

### ISSUE THREAD

**Issue by ghost** [braice/MuMuDVB#101]
I'd like to be able to make mumudvb "change channel", probably by reloading the config file on a certain signal. That way I could have a single instance of mumudvb support more than one DVB-T transponder.

**Comment by braice** [comment]
Le 17 oct. 2015 05:43, "Adam Baxter" notifications@github.com a écrit :

> I'd like to be able to make mumudvb "change channel", probably by
> reloading the config file on a certain signal. That way I could have a
> single instance of mumudvb support more than one DVB-T transponder.

Hello

I think the best to do that is to use deamon management tools which are
made for that and more flexible.

I cc to the ml in case other users implemented such things

Best

**Comment by braice** [comment]
Hello,

> On 25 Oct 2015, at 10:06, Brice Dubost bricedubost@gmail.com wrote:
> Le 17 oct. 2015 05:43, "Adam Baxter" <notifications@github.com <mailto:notifications@github.com>> a écrit :
> 
> > I'd like to be able to make mumudvb "change channel", probably by reloading the config file on a certain signal. That way I could have a single instance of mumudvb support more than one DVB-T transponder.
> 
> Please describe the use-case a bit more.
> Especially the case if two clients would request channels from different muxes.
> Depending on the use case mumudvb can be your tool, or not.
> Also if you are running on a full blown PC or just something more or less embedded, where mumudvb happen to run on.
> …
> I think the best to do that is to use deamon management tools which are made for that and more flexible.
> 
> Here just my two cents …
> you could go with something like tvheadend if you want your personal media center solution, and get server side recording as a bonus.

OR 
you just implement both mumudvb config files call via 
systemd/inetd/cgi-bin, and call mumudvb through that. There should be the conflict management, to handle conflicting calls.

You want to send signals to mumudvb, but killing mumudvb and restarting with another config isn’t so expensive when done on a pc, and not worth the work, if done sparingly. If you want to skim through channels for EPG, you probably should use the app collecting epg for that.

And finally: I once had a testrun with the cheapest DVB-T sticks in one USB bus. I was able to run all (five) free-to-air muxes in my area on one usb bus for a test reliably. And this only cost you a few dozen euro if you are buying new DVB-T (not T2). The same setup is still there (three years later, running three muxes from two countries 24/7).

For the start I can recommend systemd, which handles the occasional reboot on my and the transmitter side fine. It could be configured to provide on-demand setup on a first-come-first-served basis. 
The handling of parallel config is also fine in systemd.  I keep my mumudvb config with 60s timeout, so the chain of systemd-rsyslog-customlognotify keeps me in the loop about any downtime, but comes back on its own. 

You could setup something similar with procd/daemontools on custom embedded plattform.

Keep us posted if you happen to develop something. If you need need sample config, please send us what you already have, so we don’t do the same work again, or worse work you don’t need or can’t use on your (what?) plattform.

good luck
Matthias

**Comment by ghost** [comment]
Thanks. I've had some hardware failures so I'm not currently using MuMuDVB but I will keep this in mind.
