### ISSUE TITLE
port_http not properly parsed

### ISSUE THREAD

**Issue by lobeck** [braice/MuMuDVB#102]
I noticed that `port_http` is not correctly parsed if there is one or more spaces before the equal sign in the config statement like:

`port_http = 2000+%card*100`

however if defined as 

`port_http= 2000+%card*100` it is working correctly.

I suspect this is due to the delimiter parameter of `strtok` is an empty string instead of `delimiteurs`/`" ="`  (space + equals) in https://github.com/braice/mumudvb/blob/mumudvb2/src/unicast_http.c#L209.

I haven't seen this on other parameters and a quick grep just showed `port_http` is affected.

**Comment by braice** [comment]
Hi,

I don't remember why I did put an empty string instead of delimiteurs, can
you try with delimiteurs (and spaces in the equation) and with "="

Thanks !

2015-10-25 17:19 GMT+01:00 lobeck notifications@github.com:
