### ISSUE TITLE
android_build --> c compiler not work

### ISSUE THREAD

**Issue by gsus24** [braice/MuMuDVB#109]
Hello 

i would rebuild this Android Project to get it work with Lollipop
https://github.com/OuNao/droidtv/tree/mumudvb

I stuck on 
    sh android_build.sh

Here is conf.log, i am to new in linux to indicate the problem
    This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by MuMuDVB configure 2.0.0_20150614_mumudvb2, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --host=arm-eabi --enable-android --prefix=/home/gsus/Schreibtisch/out
## ---------

hostname = gsus-VirtualBox
uname -m = x86_64
uname -r = 3.13.0-74-generic
uname -s = Linux
uname -v = #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/gsus/Schreibtisch/shared/android/android-ndk-r10d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games
PATH: /home/gsus/.rvm/bin
## -----------

configure:2414: checking for a BSD-compatible install
configure:2482: result: /usr/bin/install -c
configure:2493: checking whether build environment is sane
configure:2548: result: yes
configure:2607: checking for arm-eabi-strip
configure:2634: result: arm-linux-androideabi-strip
configure:2699: checking for a thread-safe mkdir -p
configure:2738: result: /bin/mkdir -p
configure:2745: checking for gawk
configure:2761: found /usr/bin/gawk
configure:2772: result: gawk
configure:2783: checking whether make sets $(MAKE)
configure:2805: result: yes
configure:2834: checking whether make supports nested variables
configure:2851: result: yes
configure:2991: checking for style of include used by make
configure:3019: result: GNU
configure:3050: checking for arm-eabi-gcc
configure:3077: result: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/
configure:3346: checking for C compiler version
configure:3355: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/ --version >&5
arm-linux-androideabi-gcc (GCC) 4.6 20120106 (prerelease)
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3366: $? = 0
configure:3355: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/ -v >&5
Using built-in specs.
COLLECT_GCC=arm-linux-androideabi-gcc
COLLECT_LTO_WRAPPER=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../libexec/gcc/arm-linux-androideabi/4.6/lto-wrapper
Target: arm-linux-androideabi
Configured with: /s/ndk-toolchain/src/build/../gcc/gcc-4.6/configure --prefix=/tmp/ndk-andrewhsieh/build/toolchain/prefix --target=arm-linux-androideabi --host=x86_64-linux-gnu --build=x86_64-linux-gnu --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --with-gmp=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-mpfr=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-mpc=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-cloog=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-isl=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-ppl=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --disable-ppl-version-check --disable-cloog-version-check --disable-isl-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-float=soft --with-fpu=vfp --with-arch=armv5te --enable-target-optspace --enable-initfini-array --disable-nls --prefix=/tmp/ndk-andrewhsieh/build/toolchain/prefix --with-sysroot=/tmp/ndk-andrewhsieh/build/toolchain/prefix/sysroot --with-binutils-version=2.21 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gmp-version=5.0.5 --with-gcc-version=4.6 --with-gdb-version=7.3.x --with-python=/usr/local/google/home/andrewhsieh/mydroid/ndk/prebuilt/linux-x86_64/bin/python-config.sh --with-gxx-include-dir=/tmp/ndk-andrewhsieh/build/toolchain/prefix/include/c++/4.6 --with-bugurl=http://source.android.com/source/report-bugs.html --enable-languages=c,c++ --disable-bootstrap --enable-plugins --enable-libgomp --disable-libsanitizer --enable-gold --enable-graphite=yes --with-cloog-version=0.18.0 --with-ppl-version=1.0 --enable-eh-frame-hdr-for-static --with-arch=armv5te --program-transform-name='s&^&arm-linux-androideabi-&' --enable-gold=default
Thread model: posix
gcc version 4.6 20120106 (prerelease) (GCC) 
configure:3366: $? = 0
configure:3355: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/ -V >&5
arm-linux-androideabi-gcc: error: unrecognized option '-V'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:3366: $? = 1
configure:3355: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/ -qversion >&5
arm-linux-androideabi-gcc: error: unrecognized option '-qversion'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:3366: $? = 1
configure:3386: checking whether the C compiler works
configure:3408: arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/ -I  -L conftest.c -lc -lgcc -liconv >&5
/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: error: cannot find -liconv
collect2: ld returned 1 exit status
configure:3412: $? = 1
configure:3450: result: no
configure: failed program was:
| /\* confdefs.h _/
| #define PACKAGE_NAME "MuMuDVB"
| #define PACKAGE_TARNAME "mumudvb"
| #define PACKAGE_VERSION "2.0.0_20150614_mumudvb2"
| #define PACKAGE_STRING "MuMuDVB 2.0.0_20150614_mumudvb2"
| #define PACKAGE_BUGREPORT "mumudvb@braice.net"
| #define PACKAGE_URL ""
| #define PACKAGE "mumudvb"
| #define VERSION "2.0.0_20150614_mumudvb2"
| /_ end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3455: error: in `/home/gsus/Schreibtisch/MuMuDVB-mumudvb2':
configure:3457: error: C compiler cannot create executables
See`config.log' for more details
## ----------------

ac_cv_env_CC_set=set
ac_cv_env_CC_value='arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/'
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=-I
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=set
ac_cv_env_CPP_value='arm-linux-androideabi-cpp --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/'
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=-L
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value='-lc -lgcc -liconv'
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=arm-eabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_CC='arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/'
ac_cv_prog_STRIP=arm-linux-androideabi-strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes
## -----------------

ACLOCAL='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/missing aclocal-1.14'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/missing autoconf'
AUTOHEADER='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/missing autoheader'
AUTOMAKE='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/missing automake-1.14'
AWK='gawk'
BUILD_CAMSUPPORT_FALSE=''
BUILD_CAMSUPPORT_TRUE=''
BUILD_SCAMSUPPORT_FALSE=''
BUILD_SCAMSUPPORT_TRUE=''
CC='arm-linux-androideabi-gcc --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/'
CCDEPMODE=''
CFLAGS='-I'
CPP='arm-linux-androideabi-cpp --sysroot=/home/gsus/Schreibtisch/shared/android/android-ndk-r10d/platforms/android-8/arch-arm/'
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS='-L'
LIBICONV=''
LIBOBJS=''
LIBS='-lc -lgcc -liconv'
LTLIBICONV=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/missing makeinfo'
MKDIR_P='/bin/mkdir -p'
OBJEXT=''
PACKAGE='mumudvb'
PACKAGE_BUGREPORT='mumudvb@braice.net'
PACKAGE_NAME='MuMuDVB'
PACKAGE_STRING='MuMuDVB 2.0.0_20150614_mumudvb2'
PACKAGE_TARNAME='mumudvb'
PACKAGE_URL=''
PACKAGE_VERSION='2.0.0_20150614_mumudvb2'
PATH_SEPARATOR=':'
SET_MAKE=''
SHELL='/bin/bash'
STRIP='arm-linux-androideabi-strip'
VERSION='2.0.0_20150614_mumudvb2'
ac_ct_CC=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='arm-eabi'
host_alias='arm-eabi'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/gsus/Schreibtisch/MuMuDVB-mumudvb2/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/home/gsus/Schreibtisch/out'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''
## -----------

/\* confdefs.h */
# define PACKAGE_NAME "MuMuDVB"
# define PACKAGE_TARNAME "mumudvb"
# define PACKAGE_VERSION "2.0.0_20150614_mumudvb2"
# define PACKAGE_STRING "MuMuDVB 2.0.0_20150614_mumudvb2"
# define PACKAGE_BUGREPORT "mumudvb@braice.net"
# define PACKAGE_URL ""
# define PACKAGE "mumudvb"
# define VERSION "2.0.0_20150614_mumudvb2"

configure: exit 77

What i am doing wrong?

**Comment by braice** [comment]
Hello

I put the audience of the mailing list in copy, unfortunately I don't have
an android build platform to test

Thank you

Brice

2016-01-20 14:11 GMT-05:00 gsus24 notifications@github.com:
