### ISSUE TITLE
Crossdomain option with unicast

### ISSUE THREAD

**Issue by djpimp2010** [braice/MuMuDVB#110]
Hi.

I run mumudvb with unicast, and I love it. However, I need a browser plugin to allow crossdomain ajax calls to poll data from the unicast HTTP server.

Would it be possible to somehow use a config file option that specifies the list of domain strings (proto + host + port) that can access the HTTP server over ajax ?

This all arises because my javascript server is not hosted on the same port as the unicast server.

Thanks

**Comment by m0yellow** [comment]
The unicast server does not restrict where it is called from.
It is the browser, which restricts it.

If you still think this is an issue, please post a javascript example to test with.

**Comment by djpimp2010** [comment]
The browser restricts cross domain ajax calls, unless the webserver (in this case, mumudvb) sends a specific domain (or \* wildcard) that specifies the parent page domain that can call it (if not the same).

Webpage on port 80, uses jquery to perform the folowing AJAX call to mumu (on port 8080),

```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

$.get('http://localhost:8080/, function(data){
    console.log(data);
});
```

This should return a string of HTML data that is the index page of the unicast server (this is the check I perform to check that mumu is actually started and streaming)

The JS console logs an error like this:

```
XMLHttpRequest cannot load http://localhost:8080/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:80' is therefore not allowed access.
```

The access control header is not set, which is causing the issues. I think it may also grumble because the port is different, but the current error is because the header is not even being set.

Thanks,
Glenn

**Comment by braice** [comment]
Hi

I am definitely not an expert in modern browser security checks

What do you see as the easiest solution to tackle this issue?

Thank you

**Comment by djpimp2010** [comment]
The best solution to this, would be to put an optional variable in the config. If param supplied in config then HTTP server built into MuMu will send the header.

Eg, 

Config:
http_access_control=*

Header returned:
Access-Control-Allow-Origin: *

Or

Config:
http_access_control=localhost:8080

Header returned:
Access-Control-Allow-Origin: localhost:8080

Or

Config:
http_access_control=example.com:441

Header returned:
Access-Control-Allow-Origin: example.com:411

Obviously, if the param is not set in config, then HTTP server does not send header.

I hope this helps.

Thanks,
Glenn

**Comment by m0yellow** [comment]
Hello,
thanks for your idea,
but wouldn’t it be better, to have the Webserver who does serving the webpage also fetch the json?

Since mumudvb has no access control at all (besides restricting http access to localhost by binding IP), I would say 
a) just patch mumudvb to send 
Access-Control-Allow-Origin: *
all the time,
or 
b) make a proxy configuration where the access control happens.
I could supply nginx and apache config for that.

Matthias

**Comment by braice** [comment]
Hello

If you are fine with the header allowing everybody this is a super quick
patch.
You can do it youserlf by adding a line after line 1032 of unicast_http.c
https://github.com/braice/MuMuDVB/blob/5d2ca79267b8fbac79f38cf66fce2662c2bb3b3c/src/unicast_http.c

And do a pull request

If you prefer an option this is also easy but slightly longer

Best

Brice

2016-07-29 3:54 GMT-04:00 Matthias Šubik notifications@github.com:

**Comment by djpimp2010** [comment]
Hi, unfortunately, there is a strange but necessary reason for the two different webservers.

Option A sounds perfect thanks, as security is not really a concern. I just thought a config option would be cool :)

I have thought about using a proxy, but it is one more layer of un-necessary bloat, on a system that needs to be as responsive as possible.

Thanks very much
Glenn

---

Glenn Murley
Manager
G.Murley Hosting & Design

T: 03303 501 531
M: 0784 000 4720
E: glenn@g.murley.info
W: https://g.murley.info

**Comment by djpimp2010** [comment]
Sorry, the reply was sat in my outbox since I tried to send it.

I will look at modding the code later, but I am not a C expert :)

Thanks

**Comment by m0yellow** [comment]
Just push the header in there static,
I don’t think of a reason why it shouldn’t be there all the time.
M

**Comment by braice** [comment]
Hello

I just commited
https://github.com/braice/MuMuDVB/commit/c3cd000725d9b1ff7aef39cb4a2b6512cb605df6

Can you give it a try ?

Brice

2016-08-01 15:34 GMT-04:00 Matthias Šubik notifications@github.com:

> Just push the header in there static,
> I don’t think of a reason why it shouldn’t be there all the time.
> M
>
