### ISSUE TITLE
MUMUDVB Newbe

### ISSUE THREAD

**Issue by baron101** [braice/MuMuDVB#112]
Hi i have a Ubuntu 14.04 Server up and running, want to start my MUMUDVB Expirence but get the folling error.

the config looks like

Quattro LNB and 24 Multiswitch:

 autoconfiguration=full
freq=12187.50
pol=h
srate=27500
lnb_voltage_off=1
card=0
tuner=0

Info:  Main:  Full autoconfiguration, we activate SAP announces. if you want to deactivate them see the README.
Info:  Main:  Full autoconfiguration, we activate PAT rewritting. if you want to deactivate it see the README.
Info:  Main:  Full autoconfiguration, we activate SDT rewritting. if you want to deactivate it see the README.
Info:  Main:  Full autoconfiguration, we activate sorting of the EIT PID. if you want to deactivate it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 1.7.1 is starting ==========
Info:  Autoconf:  The autoconfiguration auto update is enabled. If you want to disable it put "autoconf_pid_update=0" in your config file.
Info:  Main:  Streaming. Freq 12187500
Info:  Tune:  Using DVB card "Montage Technology M88RS6000" tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1587500 kHz, LO frequency 10600000 kHz Pol:H Srate=27500000, LNB number: 0
Info:  Tune:  LNB voltage 0V
WARN:  Tune:  problem to set the LNB voltage
WARN:  Tune:  DISEQC SETTING FAILED
Info:  Main:  Tunning issue, card 0
Info:  Main:  Closing cleanly. Error 7
Info:  Main:  ========== MuMuDVB version 1.7.1 is stopping with ExitCode 7 ==========

thanks for helping me...

philipp

**Comment by medismail** [comment]
You tuner card didn't accept to put the "LNB voltage" to 0V, this is the problem !
Also the Multiswitch need to know lnb_voltage, so you should delete  "lnb_voltage_off=1" and it will work.

**Comment by baron101** [comment]
thanks for your reply, i solved this problem but now i get this error 

Info:  Main:  Full autoconfiguration, we activate SAP announces. if you want to deactivate them see the README.
Info:  Main:  Full autoconfiguration, we activate PAT rewritting. if you want to deactivate it see the README.
Info:  Main:  Full autoconfiguration, we activate SDT rewritting. if you want to deactivate it see the README.
Info:  Main:  Full autoconfiguration, we activate sorting of the EIT PID. if you want to deactivate it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 1.7.1 is starting ==========
Info:  Autoconf:  The autoconfiguration auto update is enabled. If you want to disable it put "autoconf_pid_update=0" in your config file.
WARN:  Logs:  saving_filename /var/run/mumudvb/mumudvb_generated_conf_card0_tuner0: No such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
Info:  Main:  Streaming. Freq 12187000
Info:  Tune:  Using DVB card "Montage RS6000(DVBSky)" tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1587000 kHz, LO frequency 10600000 kHz Pol:H Srate=27500000, LNB number: 0
Info:  Tune:  LNB voltage 18V
Info:  Tune:  DISEQC SETTING SUCCEDED
Info:  Tune:  FE_STATUS:
Info:  Main:  Card not tuned after timeout - exiting

whats wrong?

thanks for your Help

**Comment by m0yellow** [comment]
leave the decimal digits off and try again. What transponder are you trying to reach (and on what position)?
