### ISSUE TITLE
Support in MuMuDVB for Android OS native TIF (TV Input Framework)?

### ISSUE THREAD

**Issue by Hedda** [braice/MuMuDVB#113]
Appently from Android 5.0 (API level 21 and later) the OS have an integrated TV Input Framework (TIF) with built-in tuner input support.

Wondering if it would be a good idea to add support for Android TIF into MuMuDVB to access TV tuners when MuMuDVB is running on Android?

http://source.android.com/devices/tv/
http://developer.android.com/training/tv/tif/index.html
https://developer.android.com/reference/android/media/tv/package-summary.html
https://github.com/googlesamples/androidtv-sample-inputs

Point is it would be very nice have MuMuDVB accessing built-in TV tuners through Android TIF when running MuMuDVB nativly on Android.

**Comment by m0yellow** [comment]
Is there sample hardware available? Testing such a implementation is only possible if there is an actual piece of hardware, b/c API might not work at all, and nobody knows.

**Comment by Hedda** [comment]
You can use the newer tuners from Geniatech (or MyGica as just rebranded) that supports Android TV (5.0) or later

http://www.geniatech.com/tv-tuner-for-android-tablet.asp

http://mygica.com/TV-Tuner/

But important is that you need an Android TV device such as Google Nexus Player, Nvidia SHIELD TV, or Razor Forge TV.

If you want to get a cheaper device with built-in tuner then you could try to get the Rho Board by Futarque A/S

https://www.kickstarter.com/projects/928812975/rho-board/description

For referenece you can should be able to use Google's Sample Channel App (TV Input Service) on Android TV using TIF

https://github.com/googlesamples/androidtv-sample-inputs

There are a few more tips regarding tuner hardware here on Reddit:

https://www.reddit.com/r/AndroidTV/comments/3n7uhv/live_channels_usbtuner/

**Comment by m0yellow** [comment]
If you have fitting hardware, please feel free to try it. I don't have any android device besides a firetv stick.
