### ISSUE TITLE
Channels randomly scrambled

### ISSUE THREAD

**Issue by lobeck** [braice/MuMuDVB#116]
I'm currently descrambling various Sky UK channels in combination with OSCAM. This worked reliably for a couple of months, but suddenly the channels randomly switch to scrambled but are unscrambled again after a restart of mumudvb. There seems to be no pattern, sometimes the channels are scrambled after a couple of minutes, sometimes they are up for over a month. Even the time of day is different.

When this happens, i still see "found" messages in oscam, so cws are still requested and returned by oscam.

This issues does not exist on all channels, i've only seen it on some like Sky 1, Discovery, MTV

Here is a random config, they are all equal, just the frequency and filters differ:

```
    card                 = 4
    autoconfiguration    = full
    freq                 = 11876
    pol                  = h
    srate                = 27500
    autoconf_scrambled   = 1
    scam_support         = 1
    unicast              = 1
    multicast_iface4     = eth1
    port_http            = 2000+%card
    log_type             = syslog
    autoconf_ip4         = 239.12.%card.%number
    autoconf_sid_list    = 6201
# Configured Channels:
#  SID 6201 => Discovery

    new_channel
        # don't set the name, as this will overwrite the name we get from the satellite
        #name       = Discovery
        service_id = 6201
        oscam      = 1
        ip         = 239.12.4.0
```

I checked the logs and found this combination of messages, which seem to cause the blackout

```
Mar 31 10:21:55 receiver MUMUDVB[12252]: Info:  SCAM_GETCW:  Got CA_SET_PID removal request: 579 setting channel Sky Sports 1 with ca_idx to 0 0
Mar 31 10:21:56 receiver MUMUDVB[12252]: Info:  Main:  Channel "Sky Sports 1" is now partially unscrambled (28% of scrambled packets). Card 0
Mar 31 10:21:57 receiver MUMUDVB[12252]: Info:  Main:  Channel "Sky Sports 1" is now highly scrambled (97% of scrambled packets). Card 0
Mar 31 10:21:58 receiver MUMUDVB[12252]: Info:  SCAM_GETCW:  Got CA_SET_PID removal request: 647 setting channel ComedyCentral with ca_idx to 0 0
Mar 31 10:21:59 receiver MUMUDVB[12252]: Info:  Main:  Channel "ComedyCentral" is now partially unscrambled (25% of scrambled packets). Card 0
Mar 31 10:22:00 receiver MUMUDVB[12252]: Info:  Main:  Channel "ComedyCentral" is now highly scrambled (96% of scrambled packets). Card 0
Mar 31 10:22:10 receiver MUMUDVB[12252]: Info:  SCAM_GETCW:  Got CA_SET_PID removal request: 586 setting channel Sky1 with ca_idx to 0 0
Mar 31 10:22:11 receiver MUMUDVB[12252]: Info:  Main:  Channel "Sky1" is now partially unscrambled (41% of scrambled packets). Card 0
Mar 31 10:22:12 receiver MUMUDVB[12252]: Info:  Main:  Channel "Sky1" is now highly scrambled (94% of scrambled packets). Card 0
```

I guess the main issue here is the `CA_SET_PID` request, which removes the caid, i even checked the code bug i don't fully understand whats happening there. In very rare cases there follows another `CA_SET_PID` request which sets the CAID again, but just sometimes.

Do you have any clue or a possible fix?

Thank you!

**Comment by yo2loj** [comment]
The probable cause of this is the overrun on camd socket read, missing the second CA_SET_PID message just after the one removing the PID.
See #128 and #130 for a possible fix.

**Comment by lobeck** [comment]
I'm currently waiting for the issue to reappear, as i haven't noticed it in a while but i'll try the patch once i can reproduce it again.

**Comment by yo2loj** [comment]
The problem is with the 21byte reception buffer, the size of CA_SET_DESCR.
A CA_SET_SID is 13bytes long, and if sent one after another (a clear PID and then a set_PID), the beginning of the second one will land in end of the reception buffer of the first, up to 21 bytes.
This means that the actual SET_PID will be lost, and the channel stays scrambled untill next PID change, which is actually a rare event.
This condition will only appear on a PID change by the provider, which is not very often, and, more important, on mumudvb startup, resulting in ocasional failure of decryption after startup.
The patch has presumably no other side effects than solving this issue.
