### ISSUE TITLE
list cards error

### ISSUE THREAD

**Issue by YaPaY** [braice/MuMuDVB#117]
I have 16 tuner cards but when I enter l I see only these cards:

Info:  DVB:  ==================================
Info:  DVB:          DVB CARDS LISTING
Info:  DVB:  ==================================
Info:  DVB:  =========== Card 0 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 1 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 2 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 3 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 4 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 5 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 6 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 7 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 8 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 9 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 10 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:
Info:  DVB:  =========== Card 11 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6904 DVBS/S2 frontend
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:

the other 4 cards is doesn't seem. What is the problem?

**Comment by braice** [comment]
Hello

I am not sure this is MuMuDVB related, can you do "ls -l /dev/dvb"

It can be a driver issue, an hardware issue, a BIOS issue . . .

Brice

2016-04-19 18:02 GMT-04:00 YaPaY notifications@github.com:
