### ISSUE TITLE
mumudvb process shutdown itself after 24-36 hours

### ISSUE THREAD

**Issue by YaPaY** [braice/MuMuDVB#118]
`[root@localhost ~]# mumudvb -d -c /root/42/11557 -v
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.10.
## Built with support for DVB-T2.

Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

WARN:  Main:  Config issue : unknow symbol : multicast

Info:  Main:  New channel, current number 0
Info:  Main:  New channel, current number 1
Info:  Main:  New channel, current number 2
Info:  Main:  New channel, current number 3
Info:  Main:  New channel, current number 4
Info:  Main:  New channel, current number 5
Info:  Main:  New channel, current number 6
Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mu                                                                                                                                   mudvb2 is starting ==========
WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter6_tuner0: N                                                                                                                                   o such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter6_tuner0:                                                                                                                                    No such file or directory
Info:  Main:  Streaming. Freq 11557000
Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVBS/S2 frontend" tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1807000 kHz, LO frequency 9750000 kHz Pol:V                                                                                                                                    Srate=30000000, LNB number: 0
Info:  Tune:  LNB voltage 13V
Info:  Tune:  DISEQC SETTING SUCCEDED
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:       FE_HAS_VITERBI : FEC is stable
Info:  Tune:       FE_HAS_SYNC : found sync bytes
Info:  Tune:       FE_HAS_LOCK : everything's working...
Info:  Tune:  Event:  Frequency: 11557000 (or 7943000)
Info:  Tune:          SymbolRate: 30000000
Info:  Tune:          FEC_inner:  2
Info:  Tune:  Bit error rate: 67108608
Info:  Tune:  Signal strength: 32327
Info:  Tune:  SNR: 50680
Info:  Main:  Card 6, tuner 0 tuned
main 0x7fff43554ba0
Info:  Common chan:  Looking through all services to update their filters
Deb0:  Common chan:   pid 2000 added
Deb0:  Common chan:   pid 2001 added
Deb0:  Common chan:   pid 2002 added
Deb0:  Common chan:   pid 2003 added
Deb0:  Common chan:   pid 2004 added
Deb0:  Common chan:   pid 2007 added
Deb0:  Common chan:   pid 2009 added
Deb0:  Common chan:   pid 6000 added
Deb0:  Common chan:   pid 6001 added
Deb0:  Common chan:   pid 6002 added
Deb0:  Common chan:   pid 6003 added
Deb0:  Common chan:   pid 6004 added
Deb0:  Common chan:   pid 6007 added
Deb0:  Common chan:   pid 6009 added
Deb0:  Common chan:   pid 6100 added
Deb0:  Common chan:   pid 6101 added
Deb0:  Common chan:   pid 6102 added
Deb0:  Common chan:   pid 6103 added
Deb0:  Common chan:   pid 6104 added
Deb0:  Common chan:   pid 6107 added
Deb0:  Common chan:   pid 6109 added
Deb0:  Common chan:  Open the new filters
Info:  Unicast:  We open the Master http socket for address 0.0.0.0:4256
Info:  Main:  Diffusion 7 channels
Info:  Main:  Channel number :   0,   service id 51000  name : "World Travel Cha                                                                                                                                   nnel"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6000 (Unknown ), 6100 (Unknown ), 2000 (Unknown ),                                                                                                                                    6000 (Unknown ),
Info:  Main:  Channel number :   1,   service id 51001  name : "viva (Turkey)"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6001 (Unknown ), 6101 (Unknown ), 2001 (Unknown ),                                                                                                                                    6001 (Unknown ),
Info:  Main:  Channel number :   2,   service id 51002  name : "Planet Mutfak"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6002 (Unknown ), 6102 (Unknown ), 2002 (Unknown ),                                                                                                                                    6002 (Unknown ),
Info:  Main:  Channel number :   3,   service id 51003  name : "Planet Turk"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6003 (Unknown ), 6103 (Unknown ), 2003 (Unknown ),                                                                                                                                    6003 (Unknown ),
Info:  Main:  Channel number :   4,   service id 51004  name : "Planet Pembe"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6004 (Unknown ), 6104 (Unknown ), 2004 (Unknown ),                                                                                                                                    6004 (Unknown ),
Info:  Main:  Channel number :   5,   service id 51007  name : "Semerkand TV"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6007 (Unknown ), 6107 (Unknown ), 2007 (Unknown ),                                                                                                                                    6007 (Unknown ),
Info:  Main:  Channel number :   6,   service id 51009  name : "Planet Çocuk"
Info:  Main:    Unicast : Channel accessible via the master connection, 0.0.0.0:                                                                                                                                   4256
Deb0:  Main:          pids : 6009 (Unknown ), 6109 (Unknown ), 2009 (Unknown ),                                                                                                                                    6009 (Unknown ),
Info:  Unicast :  We add the client 192.168.1.46:31431 to the channel "World Travel Channel"
Info:  Unicast :  We add the client 192.168.1.46:31943 to the channel "Planet Mutfak"
Info:  Unicast :  We add the client 192.168.1.46:32455 to the channel "Planet Turk"
Info:  Unicast :  We add the client 192.168.1.46:32967 to the channel "Planet Çocuk"
Info:  Unicast :  We add the client 192.168.1.46:45767 to the channel "World Travel Channel"
Info:  Unicast :  We add the client 192.168.1.46:46279 to the channel "Planet Mutfak"
Info:  Unicast :  We add the client 192.168.1.46:46791 to the channel "Planet Turk"
Info:  Unicast :  We add the client 192.168.1.46:47303 to the channel "Planet Çocuk"
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Interrupted system call
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Interrupted system call
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:45767
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:46279
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:47303
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:45767
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:45767 : Resource temporarily unavailable
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:45767
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  The queue is full, we now throw away new packets for client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46279 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46279
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  Error when writing to client 192.168.1.46:46791 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  We can write again to client 192.168.1.46:46791
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Main:  Average packets in the buffer 10
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
Deb0:  Unicast :  Error when writing to client 192.168.1.46:47303 : Resource temporarily unavailable
Deb0:  Unicast :  We can write again to client 192.168.1.46:47303
`

config file
card=6
multicast=0
multicast_ipv4=0
multicast_ipv6=0
port_http=4256
unicast=1
freq=11557
pol=v
srate=30000
dvr_buffer_size=11
ip_http=0.0.0.0
new_channel
name=World Travel Channel
service_id=51000
pids=6000 6100 2000 6000
new_channel
name=viva (Turkey)
service_id=51001
pids=6001 6101 2001 6001
new_channel
name=Planet Mutfak
service_id=51002
pids=6002 6102 2002 6002
new_channel
name=Planet Turk
service_id=51003
pids=6003 6103 2003 6003
new_channel
name=Planet Pembe
service_id=51004
pids=6004 6104 2004 6004
new_channel
name=Semerkand TV
service_id=51007
pids=6007 6107 2007 6007
new_channel
name=Planet Çocuk
service_id=51009
pids=6009 6109 2009 6009

**Comment by braice** [comment]
Hello

I don't see a clue on why it stops in your log can you try
- run in more verbose mode
- run in gdb ("gdb ./src/mumudvb" then "run 'commandlinearguments'")

Thank you

2016-04-25 4:52 GMT-04:00 YaPaY notifications@github.com:

**Comment by YaPaY** [comment]
I set up again for buffer sizes according to the -v parameter and It works without any problem. Thanks

**Comment by braice** [comment]
Perfect
