### ISSUE TITLE
Need Help: DVB-S2 Multistream reception

### ISSUE THREAD

**Issue by Bairavan** [braice/MuMuDVB#120]
Hi, 

I`m trying receive dvb-s2 multistream from "Hot Bird 13C" satillite. but its not working.. please help me..

log msg::
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.4.
## Built with support for DVB-T2.

Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 card=3
Deb2:  Main:  002 ####
Deb2:  Main:  003 delivery_system=DVBS2
Deb2:  Main:  004 autoconfiguration=full
Deb2:  Main:  005 autoconf_scrambled=1
Deb2:  Main:  006 dvr_buffer_size=500
Deb2:  Main:  007 unicast=1
Deb2:  Main:  008 ####
Deb2:  Main:  009 ip_http=0.0.0.0
Deb2:  Main:  010 ######
Deb2:  Main:  011 freq=12585
Deb2:  Main:  012 pol=h
Deb2:  Main:  013 srate=35000
Deb2:  Main:  014 port_http=8700
Deb2:  Main:  015 ####
Deb2:  Main:  ============ done ===========
Info:  Tune:  You will use DVB API version 5 for tuning your card.
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
Info:  Main:  Streaming. Freq 12585000
Info:  Tune:  Using DVB card "TurboSight TBS 6908 DVBS/S2 frontend" tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1985000 kHz, LO frequency 10600000 kHz Pol:H Srate=35000000, LNB number: 0
Info:  Tune:  LNB voltage 18V
Info:  Tune:  DISEQC SETTING SUCCEDED
Info:  Tune:  Tuning With DVB-API version 5. delivery system : 6
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:       FE_HAS_SYNC : found sync bytes
Info:  Tune:       FE_HAS_LOCK : everything's working...
Info:  Tune:  Event:  Frequency: 12584252 (or 8615748)
Info:  Tune:          SymbolRate: 34995830
Info:  Tune:          FEC_inner:  2050
Info:  Tune:  Bit error rate: 0
Info:  Tune:  Signal strength: 37252
Info:  Tune:  SNR: 6990
Info:  Main:  Card 3, tuner 0 tuned
main 0x7fff67c8c760
Info:  Common chan:  Looking through all services to update their filters
Deb0:  Common chan:  Open the new filters
Deb1:  DVB:  Setting filter for PID 0
Deb1:  DVB:  Setting filter for PID 1
Deb1:  DVB:  Setting filter for PID 16
Deb1:  DVB:  Setting filter for PID 17
Deb1:  DVB:  Setting filter for PID 18
Deb1:  DVB:  Setting filter for PID 20
Info:  Unicast:  We open the Master http socket for address 0.0.0.0:8700
Deb1:  Unicast :  unicast : unicast_vars->pfdsnum : 1
Deb0:  SAP:  init sap v4
Info:  Autoconf:  Autoconfiguration is now ready to work for you !
Deb2:  Unicast :  New client
Deb2:  Unicast :  New connection from 127.0.0.1:50147 to 127.0.0.1:64545
Deb2:  Unicast :  We create a client associated with the socket 14
Deb2:  Unicast :  first client
Deb2:  Unicast :  Actual SO_SNDBUF size : 663750
Deb2:  Unicast :  Number of clients : 1
Deb2:  Unicast :  New message for socket 14

Thanks

**Comment by braice** [comment]
Hello

I cannot find your transponder (12585) here
http://en.kingofsat.net/pos-13E.php

Can you tell me where you got the transponder information so I can check
the parameters ?

Thank you

2016-05-13 12:20 GMT-04:00 Bairavan notifications@github.com:

**Comment by Bairavan** [comment]
Sorry @braice, its not in hobird satellite..  

http://www.lyngsat.com/Eutelsat-5-West-A.html..

**Comment by braice** [comment]
Hello

Your stream is using DVB-S2 stream ID
DVB-S2
PLS: Root+88PSK ACM/VCM
Stream 1
See http://en.kingofsat.net/pos-5W.php

See also http://www.mumudvb.net/doc/mumudvb-2.0.0/README_CONF.html for the
proper options

2016-05-16 13:18 GMT-04:00 Bairavan notifications@github.com:

**Comment by Bairavan** [comment]
Thanks for your support @braice
