### ISSUE TITLE
no pid information in web interface when limiting `pids`

### ISSUE THREAD

**Issue by lobeck** [braice/MuMuDVB#123]
I've noticed, that the `type` and `language` fields are omitted when the streamed pids are limited using the `pids` config option.

Config:

```
card                 = 5
autoconfiguration    = full
freq                 = 10744
pol                  = h
srate                = 22000
autoconf_scrambled   = 1
scam_support         = 1
unicast              = 1
multicast_iface4     = eth1
port_http            = 2000+%card
log_type             = syslog
autoconf_ip4         = 239.12.%card.%number
autoconf_sid_list    = 28724
#  Configured Channels:
#  SID 28724 => arte

new_channel
    #name       = arte
    service_id = 28724
    oscam      = 1
    ip         = 239.12.5.0
    pids       = 402
```

Content of `channels_list.json`:

```
    {
    "number": 1,
    "lcn": 0,
    "name": "arte",
    "sap_group": "",
    "ip_multicast": "239.12.5.0",
    "port_multicast": 1234,
    "num_clients": 0,
    "ratio_scrambled": 0,
    "is_up": 1,
    "pcr_pid": 401,
    "pmt_version": 3,
    "unicast_port": 0,
    "service_id": 28724,
    "service_type": "Television",
    "pids_num": 2,
        "scam": {
             "descrambled": 1,
            "ring_buffer_size": 32768,
            "decsa_delay": 500000,
            "send_delay": 1500000,
            "num_packets": 1303
        },
    "pids":[
        {
             "number": 402,
             "type": "Unknown",
             "language": ""
             },
        {
             "number": 400,
             "type": "PMT",
             "language": "---"
             }
        ],
    "clients": [
        ]
    },
```

However, if `pids` is not specified, the `type` and `language` are available as well:

```
    "pids":[
        {
             "number": 400,
             "type": "PMT",
             "language": "---"
             },
        {
             "number": 401,
             "type": "Video (MPEG2)",
             "language": "---"
             },
        {
             "number": 402,
             "type": "Audio (MPEG1)",
             "language": "deu"
             },
        {
             "number": 403,
             "type": "Audio (MPEG1)",
             "language": "mis"
             },
        {
             "number": 407,
             "type": "Audio (MPEG1)",
             "language": "mul"
             },
        {
             "number": 408,
             "type": "Audio (MPEG1)",
             "language": "fra"
             },
        {
             "number": 404,
             "type": "Teletext",
             "language": "---"
             }
        ],
```

**Comment by braice** [comment]
Hi,

This is "normal", when you use pids, you bypass the autoconfiguration thus
the detection of the information about the pids in question

This is possible to detect it when setting pids by hand, personnally I
would prefer that the autoconfiguration covers the case for which you have
to set the pids by hand

So I would be happy to hear more about your use case to find the best
solution

Brice

2016-06-09 8:01 GMT-04:00 Christian Becker notifications@github.com:

**Comment by lobeck** [comment]
Hi,

thanks for the reply.

The pid filter here is to stream just the audio part, as it's my only chance to get a clean Signal.

I already try to get the most out of autoconf, but unfortunately, i have two channels which only produce a good stream, when video is stripped.

This issue came up, as we've setup a monitoring for the streams and it also covers the pids streamed, to make sure we always have audio/video. I've already seen in the code, that this manual configuration takes a huge detour in the code and omits many things. So unless you see a easy solution for this, i'll just patch the monitoring to ignore these special channels.

Cheers,
Christian

**Comment by braice** [comment]
Hi,

This is unfortunate, do you have an idea why such channels are not working
with the video ?

Brice

2016-07-17 17:00 GMT-04:00 Christian Becker notifications@github.com:
