### ISSUE TITLE
install doesn't work

### ISSUE THREAD

**Issue by YaPaY** [braice/MuMuDVB#124]
I am trying to install v2 to Ubuntu 12.04 ./configure is okey after the make command I dont get any error message the problem is installation is continues to forever. (after 5 hours I interrupted) I am seeing always same messages in vertical scrolling texts. I tried it many times.

**Comment by braice** [comment]
Hello
Did you did the autoreconf ?

Can you give me the output of the ./configure ?

2016-06-11 19:11 GMT-04:00 YaPaY notifications@github.com:

**Comment by YaPaY** [comment]
Hello

I copied source to /home from /root it worked this time

thanks for great program

**Comment by braice** [comment]
Ok perfect
