### ISSUE TITLE
scrambling issue

### ISSUE THREAD

**Issue by YaPaY** [braice/MuMuDVB#126]
Dear all,

Some channels works with many days without scrambling but some channels scrambling in a day 2-3 times without any reason. Sometimes all transporder channels scrambling sometimes only a single channel. I am not using OSCAM. Here is the config file:

Edit: I am not so good with this technlogy and I would use a wrong term. I mean sometimes the stream of mumudvb interrupting and starting again in a few seconds later. I don'T know it means "scrambling" How I can get the data without any interrupt?
sat_number=2
card=12
multicast=0
multicast_ipv4=0
multicast_ipv6=0
port_http=4271
unicast=1
freq=12187.50
pol=h
srate=27500
dvr_buffer_size=8
ip_http=0.0.0.0
new_channel
name=RTL
service_id=12003
pids=163 104 44 163
new_channel
name=RTL 2
service_id=12020
pids=166 128 46 166
new_channel
name=VOX
service_id=12060
pids=167 136 47 167
new_channel
name=RTL Nitro
service_id=12061
pids=173 146 53 173
new_channel
name=Super RTL
service_id=12040
pids=165 120 45 165
new_channel
name=n-tv
service_id=12090
pids=169 73 48 169

**Comment by braice** [comment]
Hello

Can you use autoconfiguration ?

The service provider can update the PIDs sometimes which could then appear
as "scrambled". Autoconfiguration would follow such changes

Brice

2016-06-20 13:00 GMT-04:00 YaPaY notifications@github.com:
