### ISSUE TITLE
Does monitor/signal_power.json work with Multicast? Also whats the best protocol.

### ISSUE THREAD

**Issue by nightshadow36** [braice/MuMuDVB#131]
Does monitor/signal_power.json work with multicast?
I use Monit to start my streams & I am trying to find out how to look at signal / SNR and BER

Also at the moment I have this.
MuMudvb UDP / add MuMudvb stream to xtreamcodes  / xtream codes FFmpeg UDP to HTTP/
What would be the best protocol to use in MuMudvb. UDP or HTTP?
Is one more stable that the other?
Thank you.

**Comment by braice** [comment]
Le 7 sept. 2016 17:10, "nightshadow36" notifications@github.com a écrit :

> Does monitor/signal_power.json work with multicast?
> 
> Also at the moment I have this.
> MuMudvb UDP / add MuMudvb stream to xtreamcodes / xtream codes FFmpeg UDP
> to HTTP/
> What would be the best protocol to use in MuMudvb. UDP or HTTP?
> Is one more stable that the other?
> Thank you.

Hello

You have to enable unicast to have access to the monitor over http BUT all
your clients can use multicast, this is per design to enable easy
monitoring.

Concerning your question on the stability, as soon as you have hardware
which supports it multicast is more stable and put less load on the
streaming server as the streams will be sent once independently of the
number of clients.

Brice

**Comment by m0yellow** [comment]
Note as plus for multicast:
even with one client this puts less load on the streaming server, as it is timing independent from the client. And you can test the stream in the same LAN.
