### ISSUE TITLE
noise levels comments

### ISSUE THREAD

**Issue by YaPaY** [braice/MuMuDVB#132]
Bit error rate: 67108608
Info:  Tune:  Signal strength: 29318
Info:  Tune:  SNR: 63350
FE_HAS_SIGNAL : found something above the noise level

It is a transporder levels.
what is your opinions about the levels, bad, avarage or good?

Thanks in advance

**Comment by braice** [comment]
Le 9 sept. 2016 11:15, "YaPaY" notifications@github.com a écrit :

> Bit error rate: 67108608
> Info: Tune: Signal strength: 29318
> Info: Tune: SNR: 63350
> FE_HAS_SIGNAL : found something above the noise level
> 
> It is a transporder levels.
> what is your opinions about the levels, bad, avarage or good?
> 
> Thanks in advance

Hello

These noise levels are the one reported by the driver which are usually the
one reported by the chip.

There is a will in the Linux TV driver community to unify these but it
seems it didn't went very far.

So for the moment I would advise to search in your driver
source/documentation and/or make yourself a list of values which works for
you.

Best

Brice
