### ISSUE TITLE
Symbol rate 30000 Something above the noise level.

### ISSUE THREAD

**Issue by nightshadow36** [braice/MuMuDVB#134]
@braice 
Hello. Sorry to ask but this has been driving me mad and I dont know what i am doing wrong.
I have the TBS6909 and i am trying to get a lock on the transponder with the details below.
Would you mind telling me the correct settings i should put to be able to get a lock.
At least this way i will know if its possible or not. I have tried almost all transponder with no lock.
I am getting a message something above the noise level? all the channels seem to be moving to 3000.
For an example I am trying to get a lock onto 11265 V 30000
http://en.kingofsat.net/pos-4.8E.php
Thank you.

**Comment by braice** [comment]
Hello

Can you provide your latest trial config and the result of "MuMuDVB -lvvv"

Thank you

**Comment by nightshadow36** [comment]
@braice Hello again.
I am unable to to provide the -lvvv at the moment becuase i am waiting for my extra 6909s to arrive and have clients watching TV and no spare tuners. I will have to wait till 4am. Last config i tried was...

card=2
freq=11265
strate=30000
pol=V
coderate=auto
autoconfiguration=full
modulation=8PSK

Mumudvb keeps showing.
"something above the noise level" Does DVB-S2 have the same signal strength as DVB-S?
All the DVB-S works just not DVB-S2. Maybe I am missing siomething simple.

**Comment by braice** [comment]
Hello

Try to set the delivery system also.

Brice

**Comment by nightshadow36** [comment]
Fogot tried that also made no difference. Is there anything else i should try or should that be enough? I just dont understand why, its a shame because all the transponders are starting to change to dvb-s2

**Comment by braice** [comment]
Hello

Give me the logs with the dvbs2 delivery system and the vvvv flag

Thank you

Brice

**Comment by nightshadow36** [comment]
@braice 
Hi i will wait for my new cards to arrive maybe tomorrow or latest wednesday.
I tried on the sky sat and i could get a lock on 8PSK its only the Norwegian that does not work.
The only difference between the two is the symbol rate english is maximum 29500 but all the norwegian has 30000. Could it be the software or the cards that can not go upto 30000?

**Comment by braice** [comment]
Hello,

The software can go to 30000 the card can be limited (thus the test with
-lvvv ). And also higher srate can need better signal/reception

Brice

**Comment by nightshadow36** [comment]
@braice 
I am unable to find the logs, but i have made some screen shots.
![config](https://cloud.githubusercontent.com/assets/10221926/18839337/e48016b8-840a-11e6-9266-361d732bcf25.png)
![lvvv](https://cloud.githubusercontent.com/assets/10221926/18839338/e480d8a0-840a-11e6-85b6-0df181331477.png)
![terminal](https://cloud.githubusercontent.com/assets/10221926/18839336/e47b3440-840a-11e6-8244-0ee9ead45cb8.png)

**Comment by braice** [comment]
Hello

Can you try to specify the coderate (fec) by hand ?

Brice

**Comment by nightshadow36** [comment]
Did not work maybe i am just on the frindge of reception.
Thank you for your time
