### ISSUE TITLE
Autoconfiguration rearrange audio pids

### ISSUE THREAD

**Issue by nightshadow36** [braice/MuMuDVB#136]
@braice 
Hi i am using mumudvb with a middleware.
I have some channels that dont work unless i use autoconfiguration.

autoconfiguration=full
autoconf_sid_list=4221
# Sky-Sports-1

new_channel
name=SkySports1
service_id=4221
# pmt_pid=260
# pids=515 643 8190

oscam=1

The problem is it always uses the NAR first, is it possible to re arrange the audio pid so the english is first not the narration?
Thank you.

**Comment by braice** [comment]
Hello

I suppose the NAR pid is the first in the table, I can think of a
"preferred language"  in the rewrite of the table.

To check my hypothesis, can you give me the very verbose logs (-vvv)

Thank you

**Comment by lobeck** [comment]
According to kingofsat, Sky Sports 1 (http://de.kingofsat.net/tp.php?tp=521) just has audio pid 643 with english audio. Additionally from my experience, the Sky UK Channels have "NAR" as first audio pid, but usually it's the normal audio and nothing special, other english pids are often dolby (http://de.kingofsat.net/tp.php?tp=367)
