### ISSUE TITLE
INFO - MUMUDVB - RTL2832U

### ISSUE THREAD

**Issue by fabri8bit** [braice/MuMuDVB#143]
the software mumudvb work on "RTL2832U OEM" for RADIO FM?  there are similar software mumudvb for FM radio streamer?

**Comment by braice** [comment]
hello

the rtl2832 does not demoduate the fm, you need an SDR software to do that

On his side MuMu is designed for handling dvb streams, so radio over
satellite ok, fm nok.

for digital radio i am not aware of linux solutions but i would be glad to
hear more
