### ISSUE TITLE
No data comes out of card?

### ISSUE THREAD

**Issue by Cylinder** [braice/MuMuDVB#151]
I setup Mumudvb, but I must be doing something wrong.  My config file and the output from Mumudvb -d -c config -vvv are attached.
1.  Digital video is working.  I can use mplayer and vlc to watch video.
2.  Firewall is open.  vlc and mplayer attach to Mumudvb server on specified port, but no data comes through.  When I attach to a non-existant SID, it gives an error. "vlc http://192.168.0.3:4028/bysid/1" gives an error.  "vlc http://192.168.0.3:4028/bysid/3" does not give an error.  It just sits waiting for data.
3.  The channel list http://192.168.0.3:4028/channels_list.html gives a web page, but no channels.
4. Mumudvb appears to find the same SIDs that w_scan found: 3,4,5.
5. Mumudvb says no data is coming from the card (only one card, card 0).
6. The instructions http://mumudvb.net/documentation/asciidoc/mumudvb-2.0.0/README_CONF.html say that the freq should be specified in MHz, but that did not work, nor did Hz.  I had to specify frequency in kHz.
Thanks for any help.

[mumudvb.txt](https://github.com/braice/MuMuDVB/files/679120/mumudvb.txt)
[ERROR.txt](https://github.com/braice/MuMuDVB/files/679122/ERROR.txt)

**Comment by braice** [comment]
hello

are you using atsc ?

can you try specify the delivery_system and modulation ?

thank you

**Comment by Cylinder** [comment]
I added those fields.  I get the same  results.  VSB8 is what w_scan output.
[mumudvb.txt](https://github.com/braice/MuMuDVB/files/679386/mumudvb.txt)
I am having a heck of a time getting any kind of streaming to work... vlc no, dvbstreamer no...

**Comment by braice** [comment]
Hello

I am not super familiar with ATSC cards, some have an hardware decoder
which may take the stream and not give it to MuMuDVB.

There can be module parameters that could influence the behavior too. You
can do lsmod then modinfo the name of the module of the card.

Another check is to make a channel with the 8192 PID and see if you get
anything there (mumudvb -t should help)

Last advice, have a look to the linuxtv wiki and search for your card. If
you don't understand the page, please send me the link

Best

Brice
