### ISSUE TITLE
mumudvb acm/vcm

### ISSUE THREAD

**Issue by sofiane55** [braice/MuMuDVB#159]
hello 
i have  tbs 6908 driver installed , all information about multistream ok but when i lunch mumudvb he said no signal, i install tvheadend all workfine .
please can you tell me whats wrong

**Comment by kslimani** [comment]
Hello @sofiane55

could you please run MuMuDVB with the `-v` option and post log messages here.
Also post your configuration file may be usefull.

**Comment by sofiane55** [comment]
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built without CAM support.
Built without SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Info:  DVB:  ==================================
Info:  DVB:          DVB CARDS LISTING
Info:  DVB:  ==================================
Deb1:  DVB:  found adapter 3
Deb1:  DVB:  found adapter 2
Deb1:  DVB:  found adapter 1
Deb1:  DVB:  found adapter 0
Deb1:  DVB:     Card 0 found Frontend 0
Info:  DVB:  =========== Card 0 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6908 DVB-S/S2
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 70000 k symbols/s
Deb0:  DVB:   == Card capabilities ==
Deb1:  DVB:  caps 0x14000601
Deb0:  DVB:  FE_CAN_INVERSION_AUTO
Deb0:  DVB:  FE_CAN_FEC_AUTO
Deb0:  DVB:  FE_CAN_QPSK
Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
Info:  DVB:
Deb1:  DVB:     Card 1 found Frontend 0
Info:  DVB:  =========== Card 1 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6908 DVB-S/S2
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 70000 k symbols/s
Deb0:  DVB:   == Card capabilities ==
Deb1:  DVB:  caps 0x14000601
Deb0:  DVB:  FE_CAN_INVERSION_AUTO
Deb0:  DVB:  FE_CAN_FEC_AUTO
Deb0:  DVB:  FE_CAN_QPSK
Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
Info:  DVB:
Deb1:  DVB:     Card 2 found Frontend 0
Info:  DVB:  =========== Card 2 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6908 DVB-S/S2
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 70000 k symbols/s
Deb0:  DVB:   == Card capabilities ==
Deb1:  DVB:  caps 0x14000601
Deb0:  DVB:  FE_CAN_INVERSION_AUTO
Deb0:  DVB:  FE_CAN_FEC_AUTO
Deb0:  DVB:  FE_CAN_QPSK
Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
Info:  DVB:
Deb1:  DVB:     Card 3 found Frontend 0
Info:  DVB:  =========== Card 3 - Tuner 0 ===========
Info:  DVB:   Frontend : TurboSight TBS 6908 DVB-S/S2
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 70000 k symbols/s
Deb0:  DVB:   == Card capabilities ==
Deb1:  DVB:  caps 0x14000601
Deb0:  DVB:  FE_CAN_INVERSION_AUTO
Deb0:  DVB:  FE_CAN_FEC_AUTO
Deb0:  DVB:  FE_CAN_QPSK
Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
Info:  DVB:

**Comment by sofiane55** [comment]
when i run mumudvb and add -s ihave this
Info:  Tune:  You will use DVB API version 5 for tuning your card.
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
Info:  Main:  Streaming. Freq 11509000
Info:  Tune:  Using DVB card "TurboSight TBS 6908 DVB-S/S2 " tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1759000 kHz, LO frequency 9750000 kHz Pol:H Srate=29500000, LNB number: 0
Info:  Tune:  LNB voltage 18V
Info:  Tune:  DISEQC SETTING SUCCEDED
Info:  Tune:  Tuning With DVB-API version 5. delivery system : 6
Info:  Tune:  Stream_id = 4, stream id with PLS parameters 46460932
Info:  Tune:  FE_STATUS:
Info:  Tune:  Strength:      41984
Info:  Tune:  SNR:      35096
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:  Strength:      41328
Info:  Tune:  SNR:      35096
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:  Strength:      41328
Info:  Tune:  SNR:          0
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:  Strength:      41328
Info:  Tune:  SNR:          0
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:  Strength:      41328
Info:  Tune:  SNR:          0
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:  Strength:      41328
Info:  Tune:  SNR:          0
^C

**Comment by sofiane55** [comment]
config file:
autoconfiguration =full
card=0
freq = 11509
modulation=8PSK
pol =H
srate = 29500
coderate= 8/9
delivery_system=DVBS2
lnb_type= universal
stream_id = 1
pls_type = gold
pls_code = 50416

**Comment by kslimani** [comment]
_EDIT:_ __it seems my card does not support multisteam input and is why it is not working. Thought, it should work with your card (TBS 6908) which support it...__

@sofiane55 My hardware (TBS 6905) behave the same and i have same results as yours.

It seems this Eutelsat 5W frequency use DVB-S2 multistream (Newtek technology ?).

I don't know if it is a MumuDVB bug, it never used multistream before.

Here the log using `-vvv` option (configuration is dumped in log) :

```
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 card=1
Deb2:  Main:  002 tuner=0
Deb2:  Main:  003 sat_number=1
Deb2:  Main:  004 
Deb2:  Main:  005 delivery_system=DVBS2
Deb2:  Main:  006 freq=11509
Deb2:  Main:  007 pol=h
Deb2:  Main:  008 srate=29500
Deb2:  Main:  009 
Deb2:  Main:  010 timeout_no_diff=0
Deb2:  Main:  011 common_port=2000
Deb2:  Main:  012 sap=0
Deb2:  Main:  013 cam_support=0
Deb2:  Main:  014 rewrite_pat=1
Deb2:  Main:  015 rewrite_sdt=1
Deb2:  Main:  016 rewrite_eit=1
Deb2:  Main:  017 sort_eit=1
Deb2:  Main:  018 
Deb2:  Main:  019 unicast=1
Deb2:  Main:  020 ip_http=0.0.0.0
Deb2:  Main:  021 port_http=8010
Deb2:  Main:  022 store_eit=1
Deb2:  Main:  023 
Deb2:  Main:  024 new_channel
Deb2:  Main:  025 ip=224.4.2.2
Deb2:  Main:  026 name=France 2 HD
Deb2:  Main:  027 service_id=257
Deb2:  Main:  028 pmt_pid=110
Deb2:  Main:  029 pids=120 130
Deb2:  Main:  030 stream_id=1
Deb2:  Main:  031 pls_code=50416
Deb2:  Main:  032 pls_type=gold
Deb2:  Main:  ============ done ===========
Info:  Tune:  You will use DVB API version 5 for tuning your card.
Info:  Rewrite:  You have enabled the PAT Rewriting
Info:  Rewrite:  You have enabled the SDT Rewriting
Info:  Rewrite:  You have enabled the EIT rewriting
Info:  Rewrite:  You have enabled the EIT rewriting
Info:  Rewrite:  You have enabled the EIT (EPG) storage for webservices
Info:  Main:  New channel, current number 0
WARN:  Main:  Config issue : unknow symbol : pls_code

WARN:  Main:  Config issue : unknow symbol : pls_type

Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
Info:  Main:  Streaming. Freq 11509000
Info:  Tune:  Using DVB card "TurboSight TBS 6905 DVB-S/S2 " tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1759000 kHz, LO frequency 9750000 kHz Pol:H Srate=29500000, LNB number: 1
Info:  Tune:  LNB voltage 18V
Deb0:  Tune:  Test Diseqc message e0 10 38 f2 00 00 len 4
Deb0:  Tune:  Sending first Diseqc message e0 10 38 f2 00 00 len 4
Info:  Tune:  DISEQC SETTING SUCCEDED
Info:  Tune:  Tuning With DVB-API version 5. delivery system : 6
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
^C
```

**Comment by sofiane55** [comment]
i test every think possible , and i compare with tvheadend (workfine) , but i need multicast streaming :) 
hope Braice see what What does not turn round

**Comment by sofiane55** [comment]
hello kslimani
you have this error:


WARN:  Main:  Config issue : unknow symbol : pls_code

WARN:  Main:  Config issue : unknow symbol : pls_type

have you see this .
probleme is i can't to lock tp . 
thank you

**Comment by kslimani** [comment]
@sofiane55 yes i have seen them, thank you. _(this may be because it is not latest version compiled on this server)_

Anyway my card does not support multistream input.

**Comment by braice** [comment]
Hello

Yes multistream has been added relatively recently so make sure you check
out the latest git

If tvheadend succed to tune your card probably supports it, i don't
remember which exact tbs card supports it.

Brice

**Comment by sofiane55** [comment]
hello brice 
I just back home now , tomorow i trie a new machine with debian and  tell you ,  normaly i have compiled a last driver with no error.
think's in advance

**Comment by tazootv** [comment]
Hi, 

I have same issue. producing exactly the same results. I am using TBS5927 USB, which works fine in TV Headend.

I can lock on to RTL channels no problem, using pls_type=root

When I try french with pls_type=gold, i get same out as above

Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal

I did a bit of digging and found this - 

> for french channels of 11509H stream PLS params are 80015361 (4C4F001) when using MuMuDVB the stream params are 46460929 (2C4F001)

Update > I modified the source to set the tune_stream_id=80015361 and this didn't work either, I've tried several different values for gold 0x4, 0x2, 0x1, non of them seam to work?

Any ideas

many thanks

Steven

**Comment by tazootv** [comment]
Attached is the Scan results from tuner when TVH has signal locked

`root@ubuntu:~/Scan# scan-s2 -c
API major 5, minor 10
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
>>> parse_section, section number 0 out of 0...!
service_id = 0x0
service_id = 0x101
pmt_pid = 0x6E
service_id = 0x104
pmt_pid = 0x136
service_id = 0x105
pmt_pid = 0x1FE
service_id = 0x106
pmt_pid = 0x262
service_id = 0x110
pmt_pid = 0xD2
>>> parse_section, section number 0 out of 0...!
  VIDEO     : PID 0x00DC
  AUDIO     : PID 0x00E6
  AUDIO     : PID 0x00E7
  SUBTITLING: PID 0x00F0
  OTHER     : PID 0x0104 TYPE 0x86
>>> parse_section, section number 0 out of 0...!
  VIDEO     : PID 0x0078
  OTHER     : PID 0x0082 TYPE 0x06
  OTHER     : PID 0x0083 TYPE 0x06
  OTHER     : PID 0x0084 TYPE 0x06
  SUBTITLING: PID 0x008C
  SUBTITLING: PID 0x008E
>>> parse_section, section number 0 out of 0...!
  VIDEO     : PID 0x026C
  OTHER     : PID 0x0276 TYPE 0x06
  SUBTITLING: PID 0x0280
>>> parse_section, section number 0 out of 0...!
  VIDEO     : PID 0x0208
  OTHER     : PID 0x0212 TYPE 0x06
  OTHER     : PID 0x0213 TYPE 0x06
  SUBTITLING: PID 0x021C
>>> parse_section, section number 0 out of 0...!
  VIDEO     : PID 0x0140
  OTHER     : PID 0x014A TYPE 0x06
  OTHER     : PID 0x014B TYPE 0x06
  OTHER     : PID 0x014C TYPE 0x06
  SUBTITLING: PID 0x0154
  SUBTITLING: PID 0x0156
>>> parse_section, section number 0 out of 0...!
0x0001 0x0101: pmt_pid 0x006E GR1 A -- France 2 (running)
0x0001 0x0104: pmt_pid 0x0136 GR1 A -- France 4 (running)
0x0001 0x0105: pmt_pid 0x01FE GR1 A -- France Ô (running)
0x0001 0x0106: pmt_pid 0x0262 GR1 A -- franceinfo: (running)
0x0001 0x0110: pmt_pid 0x00D2 GR1 -- France 3 (running)
dumping lists (5 services)
France 2;GR1 A:1759:HC89M5S1P80015361:S0.0W:29500:120:0:0:0:257:8442:1:0
France 4;GR1 A:1759:HC89M5S1P80015361:S0.0W:29500:320:0:0:0:260:8442:1:0
France Ô;GR1 A:1759:HC89M5S1P80015361:S0.0W:29500:520:0:0:0:261:8442:1:0
franceinfo ;GR1 A:1759:HC89M5S1P80015361:S0.0W:29500:620:0:0:0:262:8442:1:0
France 3;GR1:1759:HC89M5S1P80015361:S0.0W:29500:220:230=fre,231=qad:0:0:272:8442:1:0
Done.`

**Comment by braice** [comment]
Hello

Maybe I have something wrong with the calculation,

To double check my calculations can you give me the source of these
numbers?

Brice

**Comment by tazootv** [comment]
Hi Brice, 

Thank you

This is the source code for TV Headend

  /* DVB-S */
  } else if (lfe->lfe_type == DVB_TYPE_S) {
    S2CMD(DTV_SYMBOL_RATE,       p.u.qpsk.symbol_rate);
    S2CMD(DTV_INNER_FEC,         p.u.qpsk.fec_inner);
    S2CMD(DTV_MODULATION,        TR(modulation, mod_tbl, QPSK));
    if (lm->lm_tuning.dmc_fe_delsys == DVB_SYS_DVBS) {
      S2CMD(DTV_ROLLOFF,         ROLLOFF_35);
    } else {
      S2CMD(DTV_PILOT,           TR(pilot, pilot_tbl, PILOT_AUTO));
      S2CMD(DTV_ROLLOFF,         TR(rolloff, rolloff_tbl, ROLLOFF_AUTO));
      r = dmc->dmc_fe_stream_id != DVB_NO_STREAM_ID_FILTER ? (dmc->dmc_fe_stream_id & 0xFF) |
          ((dmc->dmc_fe_pls_code & 0x3FFFF)<<8) | ((dmc->dmc_fe_pls_mode & 0x3)<<26) :
          DVB_NO_STREAM_ID_FILTER;
#if DVB_VER_ATLEAST(5,9)
      S2CMD(DTV_STREAM_ID,       r);
#elif DVB_VER_ATLEAST(5,3)
      S2CMD(DTV_DVBT2_PLP_ID,    r);
#endif
    }

Steven

**Comment by braice** [comment]
Hello

Indeed it seems that MuMuDVB's calculation was broken

I have pushed a fix, can you give it a try ?

Thank you

Brice

2017-02-18 3:59 GMT-05:00 Steven Matthews <notifications@github.com>:

**Comment by braice** [comment]
Hello,
 Please reopen the issue if it is still broken

Brice
