### ISSUE TITLE
Error : DVR buffer overrun

### ISSUE THREAD

**Issue by mathiasimmer** [braice/MuMuDVB#162]
This is my first time using MuMuDVB but I keep getting the "DVR buffer overrun" error after a little while. I have tried messing with various buffer-related configuration settings but nothing seems to fix it.
Here is the result of the command (output contains the configuration file as well).
````
~$ : mumudvb -d -vvvv -c mumuconf
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built without CAM support.
Built without SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 autoconfiguration=full
Deb2:  Main:  002 freq=650000
Deb2:  Main:  003 log_file=/tmp/mumu.log
Deb2:  Main:  004 delivery_system=DVBT
Deb2:  Main:  005 
Deb2:  Main:  ============ done ===========
Info:  Tune:  You will use DVB API version 5 for tuning your card.
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
main 0x7ffce7163840
````
The content of the log file can be seen here: http://pastebin.com/pDuAiEpi
Few things I have observed: If I do a tail -f on the log file and follow the output as it is being produced, the output will hang just before the overflow errors occurs.
If I try to browse the internet while the command is running, the speed is very slow to the point where it would often fail to load a page.
If I load VLC, I can see a few of the channels in the SAP explorer and I can see a stuttering image with a lot of artifacts.

I'm trying to access free unencrypted channels through DVB-T (appears to also be a problem with DVB-C) with an Elgato EyeTV Hybrid.

**Comment by braice** [comment]
Hello

Can you describe your network configuration?

Thanks

**Comment by mathiasimmer** [comment]
I was just using my laptop to get to a point in the house where I knew I could get good DVB-T reception. So it was connected wirelessly to my 802.11ac router but I guess that might be the problem considering the unicast traffic. My only goal was to see whether or not VLC on my laptop would pick up the channels. I guess I could try to connect to the network using a cable if that could fix it. Alternatively, is there a way to disable multicast and maybe just use send to 127.0.0.1 ?

**Comment by mathiasimmer** [comment]
I disconnected from wireless and used a wired connection instead and that fixed it so the problem was definitely network-related.
