### ISSUE TITLE
mumudvb ignores SIGINT?

### ISSUE THREAD

**Issue by m0yellow** [braice/MuMuDVB#165]
I tried a version from git,
and it ignores SIGINT/SIGTERM. 

Any changes recently that could have caused that?

It also ignores the config 
timeout_no_diff=60.

**Comment by braice** [comment]
Hello

Can you try to identify the faulty commit using git bissect ?

Thanks


2017-03-26 16:56 GMT-04:00 Matthias Šubik <notifications@github.com>:
