### ISSUE TITLE
homepage in the sources http://mumudvb.braice.net -> http://mumudvb.net/

### ISSUE THREAD

**Issue by noelk** [braice/MuMuDVB#172]
Hello,

right now I cannot connect to http://mumudvb.braice.net/. The official homepage seems to be now mumudvb.net which should be updated in the source code, manpages, documentation.
e.g. the channel_list.html points to the old URL

src/unicast_http.h
...
#define HTTP_INDEX_REPLY_END "<hr />\r\n"\
                            "See <a href=\"http://mumudvb.braice.net\">MuMuDVB</a> website for more details.\r\n"\
...

Thanks for your work.

**Comment by braice** [comment]
Merged the commit. Thank you
