### ISSUE TITLE
multicast problem

### ISSUE THREAD

**Issue by azzahrah** [braice/MuMuDVB#174]
Hello,
i have problem receive multicast stream from vlc,  udp://@239.100.1.0:1234, no audio/video displayed, but when transcode to ffserver i can receive from my vlc, what main problem?

**Comment by lobeck** [comment]
If it's multicast, you don't need the @, that might be the issue.

**Comment by azzahrah** [comment]
hello
i try remove @, but still wan't receive stream..., i wonder why udp://@239.100.1.0:1234 can transcode using ffmpeg and ffserver, ffmpeg -i udp://@239.100.1.0:1234 http://xxxx:port/stream.ffm, but problem with vlc..

**Comment by m0yellow** [comment]
one step after another ...

1.  can you watch the stream connecting VLC directly to MuMuDVB? (Multicast/Unicast)
2. does `ffmpeg -i udp://239.100.1.0:1234` give you any output?
3. what ist your ffserver config, does it work with static files?

And such a question without logs, is hard to tell.

**Comment by azzahrah** [comment]
Helo

I can access streaming through ffserver, but i can't access stream (multicast) directly to mumudvb vlc udp://@239.100.2.0:1234
 
#ffserver.conf example
HTTPPort 8181
RTSPPort 554
#bind FFserver to a specific interface, better to be same as MuMu Interface
#BindAddress 192.168.100.100
#Max http connection limitation
MaxHTTPConnections 1000
#how much IPTV client you want at the same time ?
MaxClients 200
#max bandwith to process
MaxBandwidth 2048000
CustomLog -

<Feed indosiar.ffm>
    #specify the temporary file to use to dump the stream to FFserver
    File /tmp/indosiar.ffm
    FileMaxSize 20000K
    launch ffmpeg -i udp://@239.100.2.0:1234
</Feed>
<Stream indosiar.asf>
Feed indosiar.ffm
Format asf
NoLoop
VideoCodec mpeg4
VideoFrameRate 25
VideoBufferSize 100000
VideoBitRate 512
VideoQMin 1
VideoQMax 31
VideoSize 352x240
AVOptionVideo flags +global_header
PreRoll 0
AudioCodec libmp3lame
AudioBitRate 48
AudioChannels 2
AudioSampleRate 24000
AVOptionAudio flags +global_header
</Stream>


#Mumudvb configuration
#TVONE
unicast=1
port_http=8002
card=2
freq=3786
srate=5632
pol=h
dvr_thread=1
lnb_slof=5150
lnb_lof_low=5150
lnb_lof_high=5150
autoconfiguration=full
autoconf_scrambled=1
store_eit=1
rewrite_eit=1

#new_channel
#ip=239.100.2.0
#port=1234
#name=TV One
#pids=131

/******************* Log VLC ******************************/

main debug: processing request item: udp://239.100.2.0:1234, node: Playlist, skip: 0
main debug: resyncing on udp://239.100.2.0:1234
main debug: udp://239.100.2.0:1234 is at 1
main debug: starting playback of the new playlist item
main debug: resyncing on udp://239.100.2.0:1234
main debug: udp://239.100.2.0:1234 is at 1
main debug: creating new input thread
main debug: Creating an input for 'udp://239.100.2.0:1234'
main debug: using timeshift granularity of 50 MiB, in path 'C:\Users\User\AppData\Local\Temp'
main debug: `udp://@239.100.2.0:1234' gives access `udp' demux `' path `@239.100.2.0:1234'
main debug: creating demux: access='udp' demux='' location='@239.100.2.0:1234' file='\\@239.100.2.0:1234'
main debug: looking for access_demux module matching "udp": 12 candidates
main debug: no access_demux modules matched
main debug: creating access 'udp' location='@239.100.2.0:1234', path='\\@239.100.2.0:1234'
main debug: looking for access module matching "udp": 20 candidates
access_udp debug: opening server=:0 local=239.100.2.0:1234
main debug: net: opening 239.100.2.0 datagram port 1234
main debug: using access module "access_udp"
main debug: Using block method for AStream*
main debug: starting pre-buffering
qt4 debug: IM: Setting an input

**Comment by kslimani** [comment]
Does  `ffprobe udp://239.100.2.0:1234` output something ? Also is the multicast stream incoming from main network interface ? (_because otherwise you may need to add a multicast static route_).

**Comment by azzahrah** [comment]
#FFprobe result

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\User>ping 10.0.20.99 -t

Pinging 10.0.20.99 with 32 bytes of data:
Reply from 10.0.20.99: bytes=32 time=28ms TTL=126
Reply from 10.0.20.99: bytes=32 time=9ms TTL=126
Reply from 10.0.20.99: bytes=32 time=17ms TTL=126
Reply from 10.0.20.99: bytes=32 time=31ms TTL=126
Reply from 10.0.20.99: bytes=32 time=20ms TTL=126
Reply from 10.0.20.99: bytes=32 time=65ms TTL=126
Reply from 10.0.20.99: bytes=32 time=51ms TTL=126
Reply from 10.0.20.99: bytes=32 time=16ms TTL=126
Reply from 10.0.20.99: bytes=32 time=30ms TTL=126
Reply from 10.0.20.99: bytes=32 time=27ms TTL=126
Reply from 10.0.20.99: bytes=32 time=32ms TTL=126
Reply from 10.0.20.99: bytes=32 time=3ms TTL=126
Reply from 10.0.20.99: bytes=32 time=42ms TTL=126
Reply from 10.0.20.99: bytes=32 time=50ms TTL=126
Reply from 10.0.20.99: bytes=32 time=31ms TTL=126
Reply from 10.0.20.99: bytes=32 time=23ms TTL=126
Reply from 10.0.20.99: bytes=32 time=30ms TTL=126
Reply from 10.0.20.99: bytes=32 time=45ms TTL=126
Reply from 10.0.20.99: bytes=32 time=32ms TTL=126
Reply from 10.0.20.99: bytes=32 time=39ms TTL=126
Reply from 10.0.20.99: bytes=32 time=14ms TTL=126
Reply from 10.0.20.99: bytes=32 time=63ms TTL=126
Reply from 10.0.20.99: bytes=32 time=51ms TTL=126
Reply from 10.0.20.99: bytes=32 time=48ms TTL=126
Reply from 10.0.20.99: bytes=32 time=53ms TTL=126
Reply from 10.0.20.99: bytes=32 time=57ms TTL=126
Reply from 10.0.20.99: bytes=32 time=27ms TTL=126
Reply from 10.0.20.99: bytes=32 time=43ms TTL=126
Reply from 10.0.20.99: bytes=32 time=12ms TTL=126

Ping statistics for 10.0.20.99:
    Packets: Sent = 29, Received = 29, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 65ms, Average = 34ms
Control-C
^C
C:\Users\User>ping 192.168.0.81 -t

Pinging 192.168.0.81 with 32 bytes of data:
Reply from 192.168.0.81: bytes=32 time=6ms TTL=63
Reply from 192.168.0.81: bytes=32 time=35ms TTL=63
Reply from 192.168.0.81: bytes=32 time=56ms TTL=63
Reply from 192.168.0.81: bytes=32 time=54ms TTL=63
Reply from 192.168.0.81: bytes=32 time=43ms TTL=63

Ping statistics for 192.168.0.81:
    Packets: Sent = 5, Received = 5, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 6ms, Maximum = 56ms, Average = 38ms
Control-C
^C
C:\Users\User>ping 192.168.0.82 -t

Pinging 192.168.0.82 with 32 bytes of data:
Reply from 192.168.0.82: bytes=32 time=9ms TTL=63
Reply from 192.168.0.82: bytes=32 time=57ms TTL=63
Reply from 192.168.0.82: bytes=32 time=38ms TTL=63
Reply from 192.168.0.82: bytes=32 time=8ms TTL=63
Reply from 192.168.0.82: bytes=32 time=27ms TTL=63

Ping statistics for 192.168.0.82:
    Packets: Sent = 5, Received = 5, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 8ms, Maximum = 57ms, Average = 27ms
Control-C
^C
C:\Users\User>ping 192.168.0.83 -t

Pinging 192.168.0.83 with 32 bytes of data:
Reply from 192.168.0.83: bytes=32 time=284ms TTL=63
Reply from 192.168.0.83: bytes=32 time=75ms TTL=63
Reply from 192.168.0.83: bytes=32 time=37ms TTL=63
Reply from 192.168.0.83: bytes=32 time=4ms TTL=63
Reply from 192.168.0.83: bytes=32 time=14ms TTL=63
Reply from 192.168.0.83: bytes=32 time=20ms TTL=63

Ping statistics for 192.168.0.83:
    Packets: Sent = 6, Received = 6, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 4ms, Maximum = 284ms, Average = 72ms
Control-C
^C
C:\Users\User>ping 192.168.0.84 -t

Pinging 192.168.0.84 with 32 bytes of data:
Control-C
^C
C:\Users\User>ping 192.168.0.83 -t

Pinging 192.168.0.83 with 32 bytes of data:
Reply from 192.168.0.83: bytes=32 time=21ms TTL=63
Reply from 192.168.0.83: bytes=32 time=8ms TTL=63
Reply from 192.168.0.83: bytes=32 time=7ms TTL=63

Ping statistics for 192.168.0.83:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 7ms, Maximum = 21ms, Average = 12ms
Control-C
^C
C:\Users\User>ping 192.168.0.82 -t

Pinging 192.168.0.82 with 32 bytes of data:
Reply from 192.168.0.82: bytes=32 time=32ms TTL=63
Reply from 192.168.0.82: bytes=32 time=49ms TTL=63

Ping statistics for 192.168.0.82:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 32ms, Maximum = 49ms, Average = 40ms
Control-C
^C
C:\Users\User>ping 192.168.0.82 -t

Pinging 192.168.0.82 with 32 bytes of data:
Reply from 192.168.0.82: bytes=32 time=25ms TTL=63
Reply from 192.168.0.82: bytes=32 time=15ms TTL=63
Reply from 192.168.0.82: bytes=32 time=58ms TTL=63

Ping statistics for 192.168.0.82:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 15ms, Maximum = 58ms, Average = 32ms
Control-C
^C
C:\Users\User>ping 192.168.0.82 -t

Pinging 192.168.0.82 with 32 bytes of data:
Reply from 192.168.0.82: bytes=32 time=67ms TTL=63
Reply from 192.168.0.82: bytes=32 time=4ms TTL=63
Reply from 192.168.0.82: bytes=32 time=12ms TTL=63
Reply from 192.168.0.82: bytes=32 time=1ms TTL=63
Reply from 192.168.0.82: bytes=32 time=10ms TTL=63

Ping statistics for 192.168.0.82:
    Packets: Sent = 5, Received = 5, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 67ms, Average = 18ms
Control-C
^C
C:\Users\User>vlc
'vlc' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User>cd \

C:\>cd "Program Files"

C:\Program Files>cd VideoLAN

C:\Program Files\VideoLAN>dir
 Volume in drive C is Acer
 Volume Serial Number is CCAD-618B

 Directory of C:\Program Files\VideoLAN

05/10/2017  09:49 AM    <DIR>          .
05/10/2017  09:49 AM    <DIR>          ..
05/10/2017  09:50 AM    <DIR>          VLC
               0 File(s)              0 bytes
               3 Dir(s)  117,740,908,544 bytes free

C:\Program Files\VideoLAN>cd VLC

C:\Program Files\VideoLAN\VLC>dir
 Volume in drive C is Acer
 Volume Serial Number is CCAD-618B

 Directory of C:\Program Files\VideoLAN\VLC

05/10/2017  09:50 AM    <DIR>          .
05/10/2017  09:50 AM    <DIR>          ..
09/23/2013  06:18 AM            15,480 AUTHORS.txt
09/23/2013  06:18 AM           498,176 axvlc.dll
09/23/2013  06:18 AM               294 axvlc.dll.manifest
09/23/2013  06:18 AM            18,092 COPYING.txt
05/10/2017  09:50 AM                55 Documentation.url
09/23/2013  06:18 AM           113,664 libvlc.dll
09/23/2013  06:19 AM         2,341,888 libvlccore.dll
05/10/2017  09:50 AM    <DIR>          locale
05/10/2017  09:50 AM    <DIR>          lua
09/23/2013  06:18 AM           138,679 NEWS.txt
05/10/2017  09:50 AM                64 New_Skins.url
09/23/2013  06:18 AM           353,280 npvlc.dll
09/23/2013  06:18 AM               294 npvlc.dll.manifest
05/10/2017  09:50 AM    <DIR>          plugins
09/23/2013  06:18 AM             2,759 README.txt
05/10/2017  09:50 AM    <DIR>          sdk
05/10/2017  09:50 AM    <DIR>          skins
09/23/2013  06:18 AM             5,540 THANKS.txt
05/10/2017  09:50 AM           223,622 uninstall.exe
05/10/2017  09:50 AM                50 VideoLAN Website.url
09/23/2013  06:19 AM           114,176 vlc-cache-gen.exe
09/23/2013  06:18 AM           126,464 vlc.exe
09/23/2013  06:18 AM               825 vlc.exe.manifest
              18 File(s)      3,953,402 bytes
               7 Dir(s)  117,740,908,544 bytes free

C:\Program Files\VideoLAN\VLC>vlc

C:\Program Files\VideoLAN\VLC>vlc udp://239.100.2.0:1234

C:\Program Files\VideoLAN\VLC>d:

D:\>cd ffmpeg

D:\ffmpeg>cd bin

D:\ffmpeg\bin>ffprob udp://@239.100.2.0:1234
'ffprob' is not recognized as an internal or external command,
operable program or batch file.

D:\ffmpeg\bin>dir
 Volume in drive D is DATA
 Volume Serial Number is 3E89-E254

 Directory of D:\ffmpeg\bin

05/02/2017  07:06 PM    <DIR>          .
05/02/2017  07:06 PM    <DIR>          ..
05/02/2017  07:06 PM        36,192,256 ffmpeg.exe
05/02/2017  07:06 PM        36,078,080 ffplay.exe
05/02/2017  07:06 PM        36,096,512 ffprobe.exe
               3 File(s)    108,366,848 bytes
               2 Dir(s)  70,482,223,104 bytes free

D:\ffmpeg\bin>ffprobe udp://@239.100.2.0:1234
ffprobe version N-85750-ga75ef15 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 61.100 / 55. 61.100
  libavcodec     57. 93.100 / 57. 93.100
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 88.100 /  6. 88.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100

**Comment by kslimani** [comment]
@azzahrah can you please run `ffprobe udp://239.100.2.0:1234` (without the __@__).

**Comment by kslimani** [comment]
if ffprobe without @ does not output anything, then try to add the following route (_from command line_) :

```
route add 239.0.0.0 mask 240.0.0.0 10.0.20.99
```
(edit: replace 10.0.20.99 by ip address or name of network interface where multicast is coming from)

**Comment by azzahrah** [comment]
finally problem solve, second router multicast not enable...
