### ISSUE TITLE
Unable to get all T2  Transport_stream in one frequency  

### ISSUE THREAD

**Issue by i-Apps** [braice/MuMuDVB#182]
There are three transport stream IDs on one frequency. MuMuDVB works only with Transport_stream_ID: 1 (0x0001)

dvbsnoop -adapter 0 -n 1 16
dvbsnoop V1.4.50 -- http://dvbsnoop.sourceforge.net/
 
------------------------------------------------------------
SECT-Packet: 00000001   PID: 16 (0x0010), Length: 161 (0x00a1)
Time received: Thu 2017-08-03  19:02:54.013
------------------------------------------------------------
  0000:  40 f0 9e 35 79 d5 00 00  f0 06 40 04 52 54 52 4e   @..5y.....@.RTRN
  0010:  f0 8b 00 01 22 83 f0 50  41 1e 03 f2 01 04 06 01   ...."..PA.......
  0020:  04 10 01 04 1a 01 04 24  01 04 38 01 04 42 01 04   .......$..8..B..
  0030:  4c 01 04 56 02 04 60 02  04 04 04 00 22 83 83 28   L..V..`....."..(
  0040:  03 f2 c0 01 04 06 c0 03  04 10 c0 04 04 1a c0 05   ................
  0050:  04 24 c0 06 04 38 c0 08  04 42 c0 09 04 4c c0 0a   .$...8...B...L..
  0060:  04 56 c0 0b 04 60 c0 0c  00 02 22 83 f0 18 41 06   .V...`...."...A.
  0070:  03 fc 01 04 6a 02 04 04  04 01 22 83 83 08 03 fc   ....j.....".....
  0080:  c0 02 04 6a c0 0d 00 03  22 83 f0 11 41 03 04 2e   ...j...."...A...
  0090:  01 04 04 04 02 22 83 83  04 04 2e c0 07 c2 c2 a0   ....."..........
  00a0:  d7                                                 .
 
PID:  16 (0x0010)  [= assigned for: DVB Network Information Table (NIT), Stuffing Table (ST)]
 
Guess table from table id...
NIT-decoding....
Table_ID: 64 (0x40)  [= Network Information Table (NIT) - actual network]
section_syntax_indicator: 1 (0x01)
reserved_1: 1 (0x01)
reserved_2: 3 (0x03)
Section_length: 158 (0x009e)
Network_ID: 13689 (0x3579)  [= --> please lookup at http://www.dvb.org]
reserved_3: 3 (0x03)
Version_number: 10 (0x0a)
current_next_indicator: 1 (0x01)  [= valid now]
Section_number: 0 (0x00)
Last_Section_number: 0 (0x00)
reserved_4: 15 (0x0f)
Network_descriptor_length: 6 (0x0006)
 
        DVB-DescriptorTag: 64 (0x40)  [= network_name_descriptor]
        descriptor_length: 4 (0x04)
        Network_name: "RTRN"  -- Charset: Latin alphabet
 
 
reserved_5: 15 (0x0f)
Transport_stream_loop_length: 139 (0x008b)
 
    Transport_stream_ID: 1 (0x0001)
    Original_network_ID: 8835 (0x2283)  [= >>ERROR: not (yet) defined... Report!<<]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 80 (0x0050)
 
            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 30 (0x1e)
               service_ID: 1010 (0x03f2)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1030 (0x0406)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1040 (0x0410)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1050 (0x041a)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1060 (0x0424)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1080 (0x0438)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1090 (0x0442)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1100 (0x044c)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1110 (0x0456)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]
 
               service_ID: 1120 (0x0460)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]
 
 
            MPEG-DescriptorTag: 4 (0x04)  [= hierarchy_descriptor]
            descriptor_length: 4 (0x04)
            reserved_1: 0 (0x00)
            hierarchy_type: 4 (0x04)  [= ITU-T Rec.H.262 | ISO/IEC 13818-2 Data partioning]
            reserved_2: 0 (0x00)
            hierarchy_layer_index: 0 (0x00)
            reserved_3: 0 (0x00)
            hierarchy_embedded_layer_index: 34 (0x22)
            reserved_4: 2 (0x02)
            hierarchy_channel: 3 (0x03)
 
            DVB-DescriptorTag: 131 (0x83)  [= User defined/ATSC reserved]
            descriptor_length: 40 (0x28)
            Descriptor-data:
                 0000:  03 f2 c0 01 04 06 c0 03  04 10 c0 04 04 1a c0 05   ................
                 0010:  04 24 c0 06 04 38 c0 08  04 42 c0 09 04 4c c0 0a   .$...8...B...L..
                 0020:  04 56 c0 0b 04 60 c0 0c                            .V...`..
 
 
    Transport_stream_ID: 2 (0x0002)
    Original_network_ID: 8835 (0x2283)  [= >>ERROR: not (yet) defined... Report!<<]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 24 (0x0018)
 
            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 6 (0x06)
               service_ID: 1020 (0x03fc)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
               service_ID: 1130 (0x046a)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]
 
 
            MPEG-DescriptorTag: 4 (0x04)  [= hierarchy_descriptor]
            descriptor_length: 4 (0x04)
            reserved_1: 0 (0x00)
            hierarchy_type: 4 (0x04)  [= ITU-T Rec.H.262 | ISO/IEC 13818-2 Data partioning]
            reserved_2: 0 (0x00)
            hierarchy_layer_index: 1 (0x01)
            reserved_3: 0 (0x00)
            hierarchy_embedded_layer_index: 34 (0x22)
            reserved_4: 2 (0x02)
            hierarchy_channel: 3 (0x03)
 
            DVB-DescriptorTag: 131 (0x83)  [= User defined/ATSC reserved]
            descriptor_length: 8 (0x08)
            Descriptor-data:
                 0000:  03 fc c0 02 04 6a c0 0d                            .....j..
 
 
    Transport_stream_ID: 3 (0x0003)
    Original_network_ID: 8835 (0x2283)  [= >>ERROR: not (yet) defined... Report!<<]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 17 (0x0011)
 
            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 3 (0x03)
               service_ID: 1070 (0x042e)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]
 
 
            MPEG-DescriptorTag: 4 (0x04)  [= hierarchy_descriptor]
            descriptor_length: 4 (0x04)
            reserved_1: 0 (0x00)
            hierarchy_type: 4 (0x04)  [= ITU-T Rec.H.262 | ISO/IEC 13818-2 Data partioning]
            reserved_2: 0 (0x00)
            hierarchy_layer_index: 2 (0x02)
            reserved_3: 0 (0x00)
            hierarchy_embedded_layer_index: 34 (0x22)
            reserved_4: 2 (0x02)
            hierarchy_channel: 3 (0x03)
 
            DVB-DescriptorTag: 131 (0x83)  [= User defined/ATSC reserved]
            descriptor_length: 4 (0x04)
            Descriptor-data:
                 0000:  04 2e c0 07                                        ....
 
CRC: 3267535063 (0xc2c2a0d7)
==========================================================

**Comment by braice** [comment]
Hello

DVB-T2 can encapsulate several TS streams in one frequency

So far I am not aware of a way through the DVB api to get them all at the
same time. If you find one I'll be glad to hear it.
I think the best route is to ask the card manufacturer as this is waht we
did to get TSID working in the first place.

Once we can get the streams we will need some rewrite to MuMuDVB to add an
extra layer to give each stream to a "child" process.

Brice
