### ISSUE TITLE
card is locked again !!

### ISSUE THREAD

**Issue by ghasemi2002123** [braice/MuMuDVB#185]
whats the solution when process and stream stopped with these messages : 
1- card is locked again 
2- no data from card 2 in 600 s , exiting
... and some similar crashed . 
is the solution that stream don't stop and if some error happened the mumudvb start stream again even from the first . 
![photo_2017-08-08_15-30-27](https://user-images.githubusercontent.com/4847656/29484944-7f182f2e-84de-11e7-8366-8aa7815d485a.jpg)
![photo_2017-08-08_15-14-55](https://user-images.githubusercontent.com/4847656/29484946-83828834-84de-11e7-9b0e-b567990cf277.jpg)

**Comment by braice** [comment]
Hello

You can run mumudvb in user space, it will be "safer".

Concerning your issue this is usually a driver bug. Do you have messages in
the kernel logs?

Brice

**Comment by braice** [comment]
Also give a try to the version 2 of MuMuDVB, v1,7 is pretty old.
