### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by ombreluckma** [braice/MuMuDVB#186]
Hi, I have a LNB Dur-line 124 UNICABLE and a DVBSat2 card from Digital device.( Max S8)
How are the best attitudes for it. I'm very bad in English.

**Comment by braice** [comment]
Hello,
There is no question in your message, can you please elaborate?

Thank you

**Comment by neidersun** [comment]
hello i can only slightly english.
My question is how does that adjust with my devices?
Have also found a small web https://github.com/OPENevents/OE-IPTV/tree/v1.1. Could this be further developed?

**Comment by braice** [comment]
Hello

Please try to describe your problem in length and use a translate tool, to improve the communication

Thank you

Brice

**Comment by malakudi** [comment]
Issue can be closed, no input from original author.

**Comment by braice** [comment]
Closes #186
