### ISSUE TITLE
MuMudvb - oscam dvbapi ???

### ISSUE THREAD

**Issue by apolo56** [braice/MuMuDVB#187]
hi
is it mumudvb only working with oscam connected with dvbapi ?

is it possible connect with oscam and newcamd line ??

i have 10 diferent servers and 3 servers with oscam 

please reply

**Comment by yo2loj** [comment]
Mumudvb does not implement any softcam protocol, so it only works via
dvbapi. You can install a local oscam instance and use that one to connect
to the other oscam servers.

**Comment by apolo56** [comment]
thanks for fast reply .
regards
