### ISSUE TITLE
AM_ICONV not found in library

### ISSUE THREAD

**Issue by hurenkam** [braice/MuMuDVB#189]
Just now, i tried to build mumudvb git repository (using an up-to-date ubuntu 17.10 beta), and it results in the following message:

root@cularin:~/MuMuDVB# autoreconf -i -f
configure.ac:27: warning: macro 'AM_ICONV' not found in library
configure.ac:27: error: possibly undefined macro: AM_ICONV
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Not sure if i'm missing a precondition here, but couldn't find an existing issue reflecting this problem.

**Comment by hurenkam** [comment]
Commenting out the offending line 27 in configure.ac makes it possible for me to configure and build mumudvb, not sure yet about the quality of that build, I'm still testing.

Update: After about a day of usage, i can't find a problem in the resulting build, so this workaround seems to work fine for me.

**Comment by braice** [comment]
Hello

Try to install the gettext package

Brice


2017-09-18 10:26 GMT-04:00 Mark Hurenkamp <notifications@github.com>:

**Comment by hurenkam** [comment]
That indeed fixes the problem. So I'm closing this.
