### ISSUE TITLE
mumudvb2: make check fails

### ISSUE THREAD

**Issue by ukleinek** [braice/MuMuDVB#211]
hello,

for me `make check` fails with

<pre>
$ make check
Making check in src
make[1]: Entering directory '/home/uwe/gsrc/MuMuDVB/src'
make  mumudvb_test
make[2]: Entering directory '/home/uwe/gsrc/MuMuDVB/src'
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -g -O2 -MT mumudvb_test.o -MD -MP -MF .deps/mumudvb_test.Tpo -c -o mumudvb_test.o mumudvb_test.c
mumudvb_test.c:72:1: error: unknown type name ‘multicast_parameters_t’; did you mean ‘unicast_parameters_t’?
 multicast_parameters_t multicast_vars;
 ^~~~~~~~~~~~~~~~~~~~~~
 unicast_parameters_t
mumudvb_test.c: In function ‘main’:
mumudvb_test.c:275:7: error: unknown type name ‘mumudvb_chan_and_pids_t’; did you mean ‘mumudvb_channel_t’?
       mumudvb_chan_and_pids_t chan_and_pids;
       ^~~~~~~~~~~~~~~~~~~~~~~
       mumudvb_channel_t
mumudvb_test.c:276:38: error: ‘mumudvb_chan_and_pids_t’ undeclared (first use in this function); did you mean ‘mumudvb_channel_t’?
       memset(&chan_and_pids,0,sizeof(mumudvb_chan_and_pids_t));
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      mumudvb_channel_t
mumudvb_test.c:276:38: note: each undeclared identifier is reported only once for each function it appears in
mumudvb_test.c:277:20: error: request for member ‘number_of_channels’ in something not a structure or union
       chan_and_pids.number_of_channels=0;
                    ^
mumudvb_test.c:280:7: error: unknown type name ‘autoconf_parameters_t’; did you mean ‘unicast_parameters_t’?
       autoconf_parameters_t autoconf_vars;
       ^~~~~~~~~~~~~~~~~~~~~
       unicast_parameters_t
mumudvb_test.c:281:38: error: ‘autoconf_parameters_t’ undeclared (first use in this function); did you mean ‘unicast_parameters_t’?
       memset(&autoconf_vars,0,sizeof(autoconf_parameters_t));
                                      ^~~~~~~~~~~~~~~~~~~~~
                                      unicast_parameters_t
mumudvb_test.c:282:20: error: request for member ‘autoconfiguration’ in something not a structure or union
       autoconf_vars.autoconfiguration=AUTOCONF_MODE_FULL;
                    ^
mumudvb_test.c:283:20: error: request for member ‘autoconf_radios’ in something not a structure or union
       autoconf_vars.autoconf_radios=1;
                    ^
mumudvb_test.c:284:20: error: request for member ‘autoconf_scrambled’ in something not a structure or union
       autoconf_vars.autoconf_scrambled=1;
                    ^
mumudvb_test.c:286:28: error: request for member ‘autoconf_ip4’ in something not a structure or union
       strcpy (autoconf_vars.autoconf_ip4,"239.100+3.%card+1.%number");
                            ^
mumudvb_test.c:287:20: error: request for member ‘transport_stream_id’ in something not a structure or union
       autoconf_vars.transport_stream_id=-1;
                    ^
mumudvb_test.c:295:7: error: unknown type name ‘multicast_parameters_t’; did you mean ‘unicast_parameters_t’?
       multicast_parameters_t multicast_vars;
       ^~~~~~~~~~~~~~~~~~~~~~
       unicast_parameters_t
mumudvb_test.c:296:39: error: ‘multicast_parameters_t’ undeclared (first use in this function); did you mean ‘unicast_parameters_t’?
       memset(&multicast_vars,0,sizeof(multicast_parameters_t));
                                       ^~~~~~~~~~~~~~~~~~~~~~
                                       unicast_parameters_t
mumudvb_test.c:297:21: error: request for member ‘multicast’ in something not a structure or union
       multicast_vars.multicast=0;
                     ^
mumudvb_test.c:301:7: error: unknown type name ‘tuning_parameters_t’; did you mean ‘unicast_parameters_t’?
       tuning_parameters_t tuneparams;
       ^~~~~~~~~~~~~~~~~~~
       unicast_parameters_t
mumudvb_test.c:302:35: error: ‘tuning_parameters_t’ undeclared (first use in this function); did you mean ‘unicast_parameters_t’?
       memset(&tuneparams,0,sizeof(tuning_parameters_t));
                                   ^~~~~~~~~~~~~~~~~~~
                                   unicast_parameters_t
mumudvb_test.c:304:55: error: request for member ‘channels’ in something not a structure or union
       iret=autoconf_init(&autoconf_vars, chan_and_pids.channels,chan_and_pids.number_of_channels);
                                                       ^
mumudvb_test.c:304:78: error: request for member ‘number_of_channels’ in something not a structure or union
 t=autoconf_init(&autoconf_vars, chan_and_pids.channels,chan_and_pids.number_of_channels);
                                                                     ^
mumudvb_test.c:304:26: warning: passing argument 1 of ‘autoconf_init’ from incompatible pointer type [-Wincompatible-pointer-types]
       iret=autoconf_init(&autoconf_vars, chan_and_pids.channels,chan_and_pids.number_of_channels);
                          ^
In file included from mumudvb_test.c:54:0:
autoconf.h:153:5: note: expected ‘auto_p_t * {aka struct auto_p_t *}’ but argument is of type ‘int *’
 int autoconf_init(auto_p_t *auto_p);
     ^~~~~~~~~~~~~
mumudvb_test.c:304:12: error: too many arguments to function ‘autoconf_init’
       iret=autoconf_init(&autoconf_vars, chan_and_pids.channels,chan_and_pids.number_of_channels);
            ^~~~~~~~~~~~~
In file included from mumudvb_test.c:54:0:
autoconf.h:153:5: note: declared here
 int autoconf_init(auto_p_t *auto_p);
     ^~~~~~~~~~~~~
mumudvb_test.c:321:59: warning: passing argument 3 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
         iret = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                           ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘auto_p_t * {aka struct auto_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:321:82: warning: passing argument 5 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘mumu_chan_p_t * {aka struct mumu_chan_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:321:98: warning: passing argument 6 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 acket(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘tune_p_t * {aka struct tune_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:321:111: warning: passing argument 7 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 tual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘multi_p_t * {aka struct multi_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:321:16: error: too few arguments to function ‘autoconf_new_packet’
         iret = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                ^~~~~~~~~~~~~~~~~~~
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: declared here
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:328:20: error: request for member ‘time_start_autoconfiguration’ in something not a structure or union
       autoconf_vars.time_start_autoconfiguration=1;
                    ^
mumudvb_test.c:329:29: warning: passing argument 2 of ‘autoconf_poll’ from incompatible pointer type [-Wincompatible-pointer-types]
       autoconf_poll(100000, &autoconf_vars, &chan_and_pids, &tuneparams, &multicast_vars, &fds, &unicast_vars, 0);
                             ^
In file included from mumudvb_test.c:54:0:
autoconf.h:157:5: note: expected ‘auto_p_t * {aka struct auto_p_t *}’ but argument is of type ‘int *’
 int autoconf_poll(long now, auto_p_t *auto_p, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p, fds_t *fds, unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~
mumudvb_test.c:329:45: warning: passing argument 3 of ‘autoconf_poll’ from incompatible pointer type [-Wincompatible-pointer-types]
       autoconf_poll(100000, &autoconf_vars, &chan_and_pids, &tuneparams, &multicast_vars, &fds, &unicast_vars, 0);
                                             ^
In file included from mumudvb_test.c:54:0:
autoconf.h:157:5: note: expected ‘mumu_chan_p_t * {aka struct mumu_chan_p_t *}’ but argument is of type ‘int *’
 int autoconf_poll(long now, auto_p_t *auto_p, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p, fds_t *fds, unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~
mumudvb_test.c:329:61: warning: passing argument 4 of ‘autoconf_poll’ from incompatible pointer type [-Wincompatible-pointer-types]
       autoconf_poll(100000, &autoconf_vars, &chan_and_pids, &tuneparams, &multicast_vars, &fds, &unicast_vars, 0);
                                                             ^
In file included from mumudvb_test.c:54:0:
autoconf.h:157:5: note: expected ‘tune_p_t * {aka struct tune_p_t *}’ but argument is of type ‘int *’
 int autoconf_poll(long now, auto_p_t *auto_p, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p, fds_t *fds, unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~
mumudvb_test.c:329:74: warning: passing argument 5 of ‘autoconf_poll’ from incompatible pointer type [-Wincompatible-pointer-types]
  autoconf_poll(100000, &autoconf_vars, &chan_and_pids, &tuneparams, &multicast_vars, &fds, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:157:5: note: expected ‘multi_p_t * {aka struct multi_p_t *}’ but argument is of type ‘int *’
 int autoconf_poll(long now, auto_p_t *auto_p, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p, fds_t *fds, unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~
mumudvb_test.c:329:7: error: too few arguments to function ‘autoconf_poll’
       autoconf_poll(100000, &autoconf_vars, &chan_and_pids, &tuneparams, &multicast_vars, &fds, &unicast_vars, 0);
       ^~~~~~~~~~~~~
In file included from mumudvb_test.c:54:0:
autoconf.h:157:5: note: declared here
 int autoconf_poll(long now, auto_p_t *auto_p, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p, fds_t *fds, unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~
mumudvb_test.c:341:59: warning: passing argument 3 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
         iret = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                           ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘auto_p_t * {aka struct auto_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:341:82: warning: passing argument 5 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘mumu_chan_p_t * {aka struct mumu_chan_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:341:98: warning: passing argument 6 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 acket(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘tune_p_t * {aka struct tune_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:341:111: warning: passing argument 7 of ‘autoconf_new_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
 tual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                                                                     ^
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: expected ‘multi_p_t * {aka struct multi_p_t *}’ but argument is of type ‘int *’
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:341:16: error: too few arguments to function ‘autoconf_new_packet’
         iret = autoconf_new_packet(pid, actual_ts_packet, &autoconf_vars,  &fds, &chan_and_pids, &tuneparams, &multicast_vars, &unicast_vars, 0);
                ^~~~~~~~~~~~~~~~~~~
In file included from mumudvb_test.c:54:0:
autoconf.h:156:5: note: declared here
 int autoconf_new_packet(int pid, unsigned char *ts_packet, auto_p_t *auto_p, fds_t *fds, mumu_chan_p_t *chan_p, tune_p_t *tune_p, multi_p_t *multi_p,  unicast_parameters_t *unicast_vars, int server_id, void *scam_vars);
     ^~~~~~~~~~~~~~~~~~~
mumudvb_test.c:347:23: error: request for member ‘services’ in something not a structure or union
       if(autoconf_vars.services)
                       ^
mumudvb_test.c:349:45: error: request for member ‘services’ in something not a structure or union
         autoconf_sort_services(autoconf_vars.services);
                                             ^
mumudvb_test.c:350:46: error: request for member ‘services’ in something not a structure or union
         autoconf_print_services(autoconf_vars.services);
                                              ^
mumudvb_test.c:356:23: error: request for member ‘number_of_channels’ in something not a structure or union
       if(chan_and_pids.number_of_channels)
                       ^
mumudvb_test.c:358:55: error: request for member ‘number_of_channels’ in something not a structure or union
         log_streamed_channels(log_module,chan_and_pids.number_of_channels, chan_and_pids.channels, 1, 0, 0, 0,"");
                                                       ^
mumudvb_test.c:358:89: error: request for member ‘channels’ in something not a structure or union
 _channels(log_module,chan_and_pids.number_of_channels, chan_and_pids.channels, 1, 0, 0, 0,"");
                                                                     ^
mumudvb_test.c:381:14: error: ‘rewrite_parameters_t {aka struct rewrite_parameters_t}’ has no member named ‘eit_sort’
             .eit_sort=OPTION_OFF,
              ^~~~~~~~
mumudvb_test.c:384:26: error: request for member ‘channels’ in something not a structure or union
             chan_and_pids.channels[curr_channel].generated_sdt_version=-1;
                          ^
mumudvb_test.c:403:74: error: request for member ‘number_of_channels’ in something not a structure or union
              for (int curr_channel = 0; curr_channel < chan_and_pids.number_of_channels; curr_channel++)
                                                                     ^
mumudvb_test.c:404:34: error: request for member ‘channels’ in something not a structure or union
                     chan_and_pids.channels[curr_channel].sdt_rewrite_skip=0;
                                  ^
mumudvb_test.c:406:72: error: request for member ‘number_of_channels’ in something not a structure or union
              for (int curr_channel = 0; curr_channel < chan_and_pids.number_of_channels; curr_channel++)
                                                                     ^
mumudvb_test.c:408:36: error: request for member ‘channels’ in something not a structure or union
                   if(!chan_and_pids.channels[curr_channel].sdt_rewrite_skip ) //AND the generation was successful
                                    ^
mumudvb_test.c:409:99: error: request for member ‘channels’ in something not a structure or union
 e_new_channel_packet(actual_ts_packet, &rewrite_vars, &chan_and_pids.channels[curr_channel], curr_channel);
                                                                     ^
mumudvb_test.c:423:24: warning: passing argument 1 of ‘autoconf_freeing’ from incompatible pointer type [-Wincompatible-pointer-types]
       autoconf_freeing(&autoconf_vars);
                        ^
In file included from mumudvb_test.c:54:0:
autoconf.h:154:6: note: expected ‘auto_p_t * {aka struct auto_p_t *}’ but argument is of type ‘int *’
 void autoconf_freeing(auto_p_t *);
      ^~~~~~~~~~~~~~~~
mumudvb_test.c:121:8: warning: unused variable ‘ipd’ [-Wunused-variable]
   char ipd[80];
        ^~~
mumudvb_test.c: In function ‘autoconf_print_services’:
mumudvb_test.c:455:34: error: ‘mumudvb_service_t {aka struct mumudvb_service_t}’ has no member named ‘running_status’
      act_service->id, act_service->running_status, act_service->free_ca_mode);
                                  ^~
Makefile:494: recipe for target 'mumudvb_test.o' failed
make[2]: *** [mumudvb_test.o] Error 1
make[2]: Leaving directory '/home/uwe/gsrc/MuMuDVB/src'
Makefile:590: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/uwe/gsrc/MuMuDVB/src'
Makefile:347: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
</pre>

**Comment by braice** [comment]
Hello

I Never used make check.

Why do you need it.

Looks like some basic flags and includes are not set making a cascade of
errors

**Comment by ukleinek** [comment]
I don't need it, but when I updated the debian packaging this target was called automatically.

I'd say it is good practice that this returns successfully if everything is in order. Otherwise its not helpful and should be removed.

**Comment by braice** [comment]
Hello

I don't really know how to remove it, it is made by the autotools. If
you have suggestions I'll be glad to hear them

Brice
