### ISSUE TITLE
http://mumudvb.braice.net/ dead?

### ISSUE THREAD

**Issue by ukleinek** [braice/MuMuDVB#212]
The source code references http://mumudvb.braice.net a few times, this seems to be dead though.
Maybe do

<pre>
git grep -l http://mumudvb.braice.net | xargs -r perl -p -i -e 's,http://mumudvb.braice.net/?,http://mumudvb.net/,'
</pre>

which seems to be only wrong for `openwrt/packages/mumudvb/Makefile`.

**Comment by braice** [comment]
Indeed I change the hosting.
Mumudvb.net should be working but I don't recall what files the openwrt
compile script was needing.

I have a public mumudvb s3 bucket to put such files if needed.

Brice
