### ISSUE TITLE
DiSEqC / sat_number

### ISSUE THREAD

**Issue by maldex** [braice/MuMuDVB#214]
i just noted that the sat_number is somehow confusing: while i specify '1' for wscan, i need to tell '4' in the mumudvb config. e.g:
```
w_scan -f s -s S13E0 -D1c
```
but
```
switch_type=c
sat_number=4
```
Is this intended or just some weird mixup on my infrastructure?

**Comment by maldex** [comment]
fresh compile, same behaviour. maybe it's just our EXR2908 DiSEqC-switch.

**Comment by braice** [comment]
Hello

I may start counting at 0, can you check

**Comment by maldex** [comment]
issue might relate to issue #203 tuning problem
