### ISSUE TITLE
Multicast static IP issue

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [braice/MuMuDVB#217]
hi guys

i have decided to stop using autoconf_ip4  because everytime channel restarted it changed the IP based on the autoconfiguration i had.

i tried using the following to set the static ip

ip=
service_id=
port=
name=

but when i start the mumudvb it gives me an error multicast ip , need to start with new_channel

i understood that part so i have added

#config channel
new_channel
ip= 239.106.1.0
service_id= ids of channels here
port= port for multicast here
name=name of the channel here

i tried to start mumudvb again, but keeps giving me the same error need to start with new_channel

i am using latest version 2.1.0

did it change anything on this channel parameters configuration on new version?

becasue channels do not start

`
Debug2:  Main:  005
Debug2:  Main:  006 card=26
Debug2:  Main:  007 freq=587
Debug2:  Main:  008
Debug2:  Main:  009
Debug2:  Main:  010 #multicast_ttl=10
Debug2:  Main:  011 #multicast_iface4=enp3s4f0
Debug2:  Main:  012 #dvr_thread_buffer_size=5000
Debug2:  Main:  013 #dvr_buffer_size=40
Debug2:  Main:  014 new_channel
Debug2:  Main:  015 ip=239.106.1.0
Debug2:  Main:  016 port=4100
Debug2:  Main:  017 name=TVM
Debug2:  Main:  018 service_id=13600
Debug2:  Main:  019 pids=257 273 274 275 256

ERROR:  Multicast:  ip : You have to start a channel first (using new_channel)

`

**Comment by kslimani** [comment]
You seems to have some syntax error in your configuration file.

If it can helps, here a complete example of configuration file using "static" channel configuration :

```
#
# Hotbird6 - 13° Est
#

log_header=%date %priority: %module
log_file=/var/log/mumudvb-manage/hotbird-11642.log
log_flush_interval=1

card=1
tuner=0
sat_number=2

delivery_system=DVBS2
freq=11642
pol=h
srate=27500

timeout_no_diff=0
common_port=2000
sap=0
cam_support=0
rewrite_pat=1
rewrite_sdt=1
rewrite_eit=1
sort_eit=1

unicast=1
ip_http=0.0.0.0
port_http=8010
store_eit=1

new_channel
ip=224.6.2.1
name=i24News HD English
service_id=1310
pmt_pid=1830
pids=1831 1832

new_channel
ip=224.6.2.2
name=i24News HD Français
service_id=1309
pmt_pid=1820
pids=1821 1822

```

For more details, see [readme conf](https://github.com/braice/MuMuDVB/blob/mumudvb2/doc/README_CONF.txt) file.

**Comment by AlbertEinsteinGlitchPoint** [comment]
ok fixed it

i was playing with the src code to patch it and made a mistake , all sorted now.. can close thread

**Comment by braice** [comment]
Hello

I think one solution for you could be to use the templates for the ip
address, so for example the ip address will be linked to the sid.

See the readme_conf

Brice
