### ISSUE TITLE
sat_number value for position C and position D when using two Unicable msw with combiner

### ISSUE THREAD

**Issue by gredek** [braice/MuMuDVB#219]
I'm using 2x Unicable msw together with a 2-way combiner. The first msw is programmed for sat A and sat B, the second msw is programmed for sat C and sat D. 

When using sat_number 0 or 1, I can tune sat A, when using sat_number 2, I can tune sat B, but when assuming that I can use sat_number 3 and 4 for sat C and sat D, that didn't work.

Now my question is, may I assume that sat_number 3 and 4 can be used as value to work with this kind of Unicable setup?

**Comment by braice** [comment]
Hello,

Can you please send me the reference of your equipment, I will have to look
at the unicable protocol for your case

Thank you

**Comment by gredek** [comment]
Hello Braice,

So I use 2x Inverto Unicable I / II Multiswitch 1-2/32/1 - IDLU-UWT110-CUO1O-32P, in combination with 4x wideband LNB's, the first MSW programmed for sat A and sat B, the second MSW for sat C and sat D, together with 1x Inverto Combiner for the combination of the UniCable lines.

I was able to tune sat A and sat B with the sat_number 1 and 2 value, together with the unicable options in the configuration:

sat_number=1 (or 2 for sat B)

unicable channel 1

switch_input=0
switch_type=n
uni_freq=1210

but I am unable to tune sat C and sat D via mumudvb.

thanks

**Comment by gredek** [comment]
Hello Braice,

The problem was that only the old Unicable (EN50494), who supports only 2 satellite positions and 8 user bands, was implemented into MuMuDVB and not JESS (also called EN50607 or Unicable 2), who supports 4 satellite positions and 32 user bands.

I implemented JESS into my own MuMuDVB fork (https://github.com/gredek/MuMuDVB/commit/16769081795566f26321a6feec2bcaec3903803d), using the new switch_type parameter 'J' and a larger field input (0-31) for the 32 userbands, it can now be used on the setup I described above.

**Comment by braice** [comment]
Thank you very much for your contribution !

2018-08-06 15:37 GMT-04:00 gredek <notifications@github.com>:

**Comment by c-o-m-m-a-n-d-e-r** [comment]
I have a Digital Devices Max S8 ... and a JESS Switch ... how can i access multiple Transponder at one card to the same time? 
Card is running correct and with tvheadend i can configure each of the 8 Tuner 4 subtuner A-D

not really sure how to do that with mumudvb (gredeks fork)

**Comment by braice** [comment]
Hello

Unless your card have multiple tuners/demuxers you cannot access more than
one transponder per card.
If it does have multiple tuners, it will appear at either multiple cards or
different tuner on the same card and you can configure the path for that.

BRice
