### ISSUE TITLE
different mumudvb instances how to stop specific instance without shutting down all the others

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [braice/MuMuDVB#221]
Hi guys

i have a strange issue, i cannot stop a specific mumudvb instance

i have 2 TBS6909 cards so 18 TPs,  running  total 18 instances of mumudvb

how can i stop for example mumudvb instance from card  tunner 4

because atm i am stopping all mumudvb instances using 

killall -9 mumudvb

but i need to stop specific instance..

when i restart all instances, some tunners fail to tune an lock channels.. i need to try at least 10x times to lock signal..

any ideas or help is appreciated.

**Comment by AlbertEinsteinGlitchPoint** [comment]
sorted

just sudo kill pidnumer..

**Comment by Saentist** [comment]
HTOP help without mistake.
