### ISSUE TITLE
2.1.0_20180602_mumudvb2 Not tuned after timeout on TBS6281SE in DVB-T2 Mode

### ISSUE THREAD

**Issue by ph0bo** [braice/MuMuDVB#224]
Hi!
I'm trying to stream DVB-T2 channels over local network and I have the following issue on my server running Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64) with TBS6281SE tuner.
Kaffeine app perfectly sees needed channels and gives the specs, which I use in the config file:

![image](https://user-images.githubusercontent.com/37534650/44843520-2cdfe800-ac51-11e8-8c92-ce74c1b44226.png)

When running MuMuDVB I get a bunch of strings

> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:

and finally
> Info:  Main:  Card not tuned after timeout - exiting

Am I doing something wrong or it is a bug?

Please, see full log below:

MuMuDVB Version 2.1.0_20180602_mumudvb2
 --- Build information ---
Built without CAM support.
Built without SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 card=0
Deb2:  Main:  002 tuner=0
Deb2:  Main:  003 freq=650000
Deb2:  Main:  004 bandwidth=8MHz
Deb2:  Main:  005 rewrite_pat=1
Deb2:  Main:  006 autoconfiguration=full
Deb2:  Main:  007 
Deb2:  Main:  008 new_channel
Deb2:  Main:  009 ip=224.0.0.0
Deb2:  Main:  010 service_id=2030
Deb2:  Main:  ============ done ===========
Info:  Rewrite:  You have enabled the PAT Rewriting
Info:  Main:  New channel, current number 0
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 2.1.0_20180602_mumudvb2 is starting ==========
WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
Info:  Main:  Streaming. Freq 650000000.000000
Info:  Tune:  Using DVB card "TurboSight TBS 6281SE DVB-T/T2/C " tuner 0
Info:  Tune:  Tuning Terrestrial to 650000000 Hz, Bandwidth: 8000000
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Main:  Card not tuned after timeout - exiting

**Comment by braice** [comment]
Hello

I tried to make the frequency input more consistent and robust recently but
I might have screwed things up

Can you try entering 650 or 650000000 as frequency ?

The other issue might be around the delivery system. Can you set the
delivery_system variable ?

thank you

Brice

**Comment by ph0bo** [comment]
Hi braice!
I've tried 650 and 650000000, but every time result is the same:

> Info: Tune: Tuning Terrestrial to 650000000 Hz, Bandwidth: 8000000
> Deb0: Tune: polling....
> Info: Tune: FE_STATUS:
..........................................
> Deb0: Tune: polling....
> Info: Tune: FE_STATUS:
> Info: Main: Card not tuned after timeout - exiting

**Comment by braice** [comment]
Ok, can you set the delivery system?

**Comment by ph0bo** [comment]
Hi, braice! Thanks a lot,
delivery_system=DVBT2 have solved the issue
