### ISSUE TITLE
mumudvb reads SDT endlessly 

### ISSUE THREAD

**Issue by malakudi** [braice/MuMuDVB#226]
On 12399 H on Eutelsat 9B (9 degrees east), mumudvb keeps rereading SDT endlessly.
Log is full with looping output like the following:
Sep 11 17:47:39 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel filters
Sep 11 17:47:39 job MUMUDVB[7291]: Info:  Common chan:  Looking through all services to update their filters
Sep 11 17:47:39 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel networking
Sep 11 17:47:39 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:40 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:40 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:40 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:41 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:41 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel names
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel status
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  Looking through all channels to see if they are ready for streaming
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel filters
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Common chan:  Looking through all services to update their filters
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  We update the channel networking
Sep 11 17:47:42 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:43 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:43 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:43 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:44 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:44 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed
Sep 11 17:47:44 job MUMUDVB[7291]: Info:  Autoconf:  The SDT version changed, channels description have changed

It only happens on this transponder. How can I debug this issue?

If I run with -v -v I get (among others):
Deb1:  Autoconf:  SDT Need update. stored version : -1, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : -1, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 10, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 9, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 9, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 1, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 3, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 3, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 1, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 11, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 30, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 30, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 11, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 9, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 9, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 16, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 3, new: 2
Deb1:  Autoconf:  SDT Need update. stored version : 19, new: 2

Any hint?

**Comment by braice** [comment]
Hi

This is an annoying transponder were they send tge sdt information in
different tables...

I will have a look on how to fix that

**Comment by braice** [comment]
Can you add an extra -v to your command line so I see a bit more the
structure of the tables ?

Thank you

Le mar. 11 sept. 2018 à 19:03, Brice Dubost <bricedubost@gmail.com> a
écrit :

> Hi
>
> This is an annoying transponder were they send tge sdt information in
> different tables...
>
> I will have a look on how to fix that
>
> On Tue, Sep 11, 2018, 10:54 Panagiotis Malakoudis <

**Comment by malakudi** [comment]
I attach mumudvb log with -v -v -v and dvbsnoop 100 packets raw binary log (can be replayed with dvbsnoop -if) from pid 0x11
[mumudvb.debug3.log](https://github.com/braice/MuMuDVB/files/2374410/mumudvb.debug3.log)

[dvbsnoop_binary_sdt.log](https://github.com/braice/MuMuDVB/files/2374415/dvbsnoop_binary_sdt.log)

**Comment by malakudi** [comment]
I think the issue is in autoconf_read_sdt(), it checks version before checking table 0x42. So it triggers version change wrongly, since the version change is for table 0x4a or 0x46.
```
From dvbsnoop log:
Table_ID: 66 (0x42)  [= Service Description Table (SDT) - actual transport stream]
section_syntax_indicator: 1 (0x01)
reserved_1: 1 (0x01)
reserved_2: 3 (0x03)
Section_length: 602 (0x025a)
Transport_Stream_ID: 6 (0x0006)
reserved_3: 3 (0x03)
Version_number: 2 (0x02)
--
Table_ID: 66 (0x42)  [= Service Description Table (SDT) - actual transport stream]
section_syntax_indicator: 1 (0x01)
reserved_1: 1 (0x01)
reserved_2: 3 (0x03)
Section_length: 946 (0x03b2)
Transport_Stream_ID: 6 (0x0006)
reserved_3: 3 (0x03)
Version_number: 2 (0x02)
--
Table_ID: 74 (0x4a)  [= Bouquet Association Table (BAT)]
section_syntax_indicator: 1 (0x01)
reserved_1: 1 (0x01)
reserved_2: 3 (0x03)
Section_length: 843 (0x034b)
Bouquet_ID: 24924 (0x615c)  [= >>ERROR: not (yet) defined... Report!<<]
reserved_3: 3 (0x03)
Version_number: 19 (0x13)
--
```
3rd packet is table 0x4a, version number 19, so it triggers a reread, which is wrong.

I can prepare a patch if needed, but I think you can handle it easily.

**Comment by malakudi** [comment]
Simple (not elegant) patch that fixes the issue:
```
--- autoconf_sdt.c~	2018-09-10 16:37:08.000000000 +0300
+++ autoconf_sdt.c	2018-09-12 13:32:16.970804358 +0300
@@ -104,6 +104,8 @@
 	len=sdt_mumu->len_full;
 
 	header=(sdt_t *)buf; //we map the packet over the header structure
+	
+	if(header->table_id != 0x42) return 0;
 
 	if(header->version_number==auto_p->sdt_version)
 	{
```

**Comment by malakudi** [comment]
Will you apply fix to git?

**Comment by braice** [comment]
yes

**Comment by braice** [comment]
Done, Thank you very much !
