### ISSUE TITLE
Failed to tune using Unicable Switch

### ISSUE THREAD

**Issue by KlausReinhard** [braice/MuMuDVB#229]
Hi mumudvb user,

I currently experince a problem where I can use a unicable switch (Kathrein  EXD1524) when running w_scan with the relevant parameter and diseqc commands ( always getting lock of signal) but when I use mumudvb sending the identical diseqc commands I get no signal lock.

Any suggestion where to tune ?

**Comment by braice** [comment]
Hello

You have a few things you can play with,

1. You can ask mumudvb to resend. (there is an option for that)
2. You can share the diseqc commands you see on mumudvb side and w_scan
3. We can play with timings, which seems to be pretty sensitive

In general the more you gave us the better to investigate

Thank you

Brice


Le mer. 10 oct. 2018 à 04:05, KlausReinhard <notifications@github.com> a
écrit :

**Comment by KlausReinhard** [comment]
Hi again,

I managed to sent identical diseqc commands from w_scan and mumudvb (see logs below - Transponder Freq 10744), I also tried to immitate the timings used within w_scan, having 5ms before/after the command sent. Still no success. How can I support you with more infos, still need to solve the issue urgently. Any help appreciated.

Many thanks in advance.

Klaus



w_scan log:

> ./bin/w_scan -vvvv -f s -s S19E2 -u 0:1284:A 
> w_scan version 20170107 (compiled for DVB API 5.10)
> using settings for 19.2 east Astra 1KR/1L/1N/1M
> SCR: slot=0, userfreq=1284MHz, satpos=A, pin=-1
> scan type SATELLITE, channellist 68
> output format vdr-2.0
> WARNING: could not guess your codepage. Falling back to 'UTF-8'
> output charset 'UTF-8', use -C <charset> to override
> Info: using DVB adapter auto detection.
>    check MXL5XX:
>            DSS
>            DVB-S2
>            DVB-S
> 	/dev/dvb/adapter0/frontend0 -> SATELLITE "MXL5XX": very good :-))
> 
> Using SATELLITE frontend (adapter /dev/dvb/adapter0/frontend0)
> -_-_-_-_ Getting frontend capabilities-_-_-_-_ 
> Using DVB API 5.11
> frontend 'MXL5XX' supports
> INVERSION_AUTO
> DVB-S
> DVB-S2
> FREQ (0.30GHz ... 2.35GHz)
> SRATE (1.000MSym/s ... 45.000MSym/s)
> using LNB "UNIVERSAL"
> -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_ 
>    check MXL5XX:
>            DSS
>            DVB-S2
>            DVB-S
> trying 'S2 f = 10729 kHz V SR = 22000  2/3 0,35  8PSK  (0:0:0)'
> (time: 00:00.002) setup_scr:618: DiSEqC: e0 10 5a 00 d8 00 - Length: 5
> setup_scr:620: fIF: 979  fLO: 9750000 Transponder: 10729000
> setup_scr:621: Scan Frequency: 1285
> setup_scr:618: DiSEqC: e0 10 5a 00 d8 00 - Length: 5
> setup_scr:620: fIF: 979  fLO: 9750000 Transponder: 10729000
> setup_scr:621: Scan Frequency: 1285
> 
> trying 'S  f = 10744 kHz H SR = 22000  5/6 0,35  QPSK  (0:0:0)'
> (time: 00:02.392) setup_scr:618: DiSEqC: e0 10 5a 08 dc 00 - Length: 5
> setup_scr:620: fIF: 994  fLO: 9750000 Transponder: 10744000
> setup_scr:621: Scan Frequency: 1286
> setup_scr:618: DiSEqC: e0 10 5a 08 dc 00 - Length: 5
> setup_scr:620: fIF: 994  fLO: 9750000 Transponder: 10744000
> setup_scr:621: Scan Frequency: 1286
> 
>         (0.464sec): SCL (0x1F)
>         (0.464sec) signal
>         (0.464sec) lock
>         signal ok:	S  f = 10744 kHz H SR = 22000  5/6 0,35  QPSK  (0:0:0)
>         initial PAT lookup..
> add_filter:1933: add_filter 1933: pid=0 (0x0000), s=0x7ffef9ceec30

mumudvb log:

> MuMuDVB Version 2.1.0_20180909_mumudvb2
>  --- Build information ---
> Built with CAM support.
> Built with SCAM support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.10.
> Built with support for DVB-T2.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.net/
> Project from the cr@ns (http://www.crans.org)
> by Brice DUBOST (mumudvb@braice.net)
> 
> Deb2:  Main:  ==== Configuration file ====
> Deb2:  Main:  001 # should select needed dvbs/dvbs2
> Deb2:  Main:  002 # especially for radio stations
> Deb2:  Main:  003 delivery_system=DVBS
> Deb2:  Main:  004 
> Deb2:  Main:  005 card=0
> Deb2:  Main:  006 freq=10744
> Deb2:  Main:  007 pol=h
> Deb2:  Main:  008 srate=22000
> Deb2:  Main:  009 
> Deb2:  Main:  010 
> Deb2:  Main:  011 sat_number=1
> Deb2:  Main:  012 switch_input=0
> Deb2:  Main:  013 switch_type=N
> Deb2:  Main:  014 diseqc_repeat=1
> Deb2:  Main:  015 uni_freq=1284
> Deb2:  Main:  016 #lnb_type=universal
> Deb2:  Main:  017 #lnb_voltage_off=1
> Deb2:  Main:  018 
> Deb2:  Main:  019 unicast=1
> Deb2:  Main:  020 ip_http=127.0.0.1
> Deb2:  Main:  021 port_http=8005
> Deb2:  Main:  022 rtp_header=0
> Deb2:  Main:  023 multicast_ttl=3
> Deb2:  Main:  024 
> Deb2:  Main:  025 dvr_buffer_size=200
> Deb2:  Main:  026 dvr_thread=1
> Deb2:  Main:  027 dvr_thread_buffer_size=5000
> Deb2:  Main:  028 
> Deb2:  Main:  029 store_eit=1
> Deb2:  Main:  030 sort_eit=1
> Deb2:  Main:  031 
> Deb2:  Main:  032 autoconfiguration=full
> Deb2:  Main:  033 # includes radio stations
> Deb2:  Main:  034 autoconf_radios=1
> Deb2:  Main:  035 
> Deb2:  Main:  036 autoconf_ip4=239.110.0.20+%number
> Deb2:  Main:  037 autoconf_multicast_port=1234
> Deb2:  Main:  038 
> Deb2:  Main:  039 sap_default_group=tvip-channels
> Deb2:  Main:  ============ done ===========
> Info:  Tune:  You will use DVB API version 5 for tuning your card.
> WARN:  Main:  You want to use a thread for reading the card, please report bugs/problems
> Info:  Rewrite:  You have enabled the EIT (EPG) storage for webservices
> Info:  Rewrite:  You have enabled the EIT rewriting
> Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
> Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
> Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
> Info:  Main:  ========== End of configuration, MuMuDVB version 2.1.0_20180909_mumudvb2 is starting ==========
> WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
> WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
> Info:  Main:  Streaming. Freq 10744000.000000
> Info:  Tune:  Using DVB card "MXL5XX" tuner 0
> Info:  Tune:  Tuning DVB-S to Freq: 994000 kHz, Transp frequency: 10744000.000000 , LO frequency 9750000 kHz  Pol:H Srate=22000000, LNB number: 1
> Info:  Tune:  LNB voltage 18V
> Info:  Tune:  Diseqc switch position specified, we force switch input to 0
> Info:  Tune:  SCR/UNICABLE message 
> Deb1:  Tune:  Unicable tuning information : unicable freq 1284 lo_freq 994000 channel byte 0x08  0xdc   t 0xdc
> Deb0:  Tune:  Test Diseqc message e0 10 5a 08 dc 00 len 5
> Deb0:  Tune:  Sending first Diseqc message e0 10 5a 08 dc 00 len 5
> Deb0:  Tune:  Sending repeated Diseqc message e0 10 5a 08 dc 00 len 5
> Info:  Tune:  DISEQC SETTING SUCCEDED - Frequency: 1286000
> Info:  Tune:  Tuning With DVB-API version 5. delivery system : 5
> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:
> Info:  Tune:  Strength:          0
> Info:  Tune:  SNR:          0
> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:
> Info:  Tune:  Strength:      57777
> Info:  Tune:  SNR:          0
> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:
> Info:  Tune:  Strength:      57924
> Info:  Tune:  SNR:          0
> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:
> Info:  Tune:  Strength:      57976
> Info:  Tune:  SNR:          0
> Deb0:  Tune:  polling....
> Info:  Tune:  FE_STATUS:
> Info:  Tune:  Strength:      57971
> Info:  Tune:  SNR:          0

**Comment by braice** [comment]
Hello

Can you Try to use dvbs2 as delivery system?

Otherwise try diseqc repeat

Brice

**Comment by braice** [comment]
If it does not work, please give me the source code for the w scan you use (
mumudvb@braice.net) and I will add a lot of debug to check everything.
Thank you

**Comment by KlausReinhard** [comment]
w_scan is used from here : http://wirbel.htpc-forum.de/w_scan/w_scan-20170107.tar.bz2
As you can see in log, I use the diseqc_repeat flag already, will try later today the dvbs2 delivery system.

thanks in advance

**Comment by KlausReinhard** [comment]
I tried with dvbs2, still no luck getting a lock ;-)

Sent you a patch-file of the tune.c file adopting w_scan behaviour and writing a few more logs. May be of any help.

klaus

**Comment by braice** [comment]
Sorry for the confusion with the other answer I just saw this one,
Does your tune.c fix the issue ?

Le mar. 16 oct. 2018 à 08:58, KlausReinhard <notifications@github.com> a
écrit :

**Comment by braice** [comment]
Hello

There is one thing I don't understand, why there is two frequencies for the
unicable
1284 and 1286, You set 1284 it send the right message and then tuning is
set to 1286.

The other thing you can try is to set the FEC, rolloff as w_scan do
 5/6 0,35

I am still very confused by the issue, I don't know if this is a diseqc
problem or a more general tuning problem

Brice



Le lun. 15 oct. 2018 à 07:48, KlausReinhard <notifications@github.com> a
écrit :

**Comment by KlausReinhard** [comment]
HI Brice,

1284 is the frequency of the Unicabel-Switch, nevertheless w_scan uses some rounding which results in 1286 but when tuning gets a signal and can lock it. I simply tried to mimick w_scan since w_scan works but mumudvb does not in terms of signal locking.

The tune.c patch does not resolve the issue but mimicks the w_scan behaviour in terms of diseqc command sequence / timing / commands for the cards, still no luck. 

I guess its  a tuning issue since both send the same diseqc commands with the patched tune.c and tries to tune the card with the same command sequence for the card. I hoped with your in-depth knowledge  of mumudvb you may spot the difference more easily.

Klaus

**Comment by braice** [comment]
Hello

So far I would say it could be
* this frequency difference. I will add some debug stuff there is some
surprising rounding in MuMuDVB too
 * The FEC and rolloff that are auto in MuMuDVB, manual in W_scan. Can you
give it a try ?

Brice

**Comment by KlausReinhard** [comment]
Hi Brice,

tried out rolloff=35, coderate=5/6 for 10744 Transponder, still no lock. 

I believe its a timing problem or sending wrong commands ? It is not a frequency problem since w_scan get a lock for 1286 (rather than 1284 as necessary for unicabel switch). I think the card manages a range of +- 5 MHz from the target frequency anyway.

Would be great if you could  do some debugging regarding the timings and commands from w_scan vs. mumudvb. Please let me know how I can assist.

Klaus

**Comment by KlausReinhard** [comment]
Hi brice,

any luck during debugging ? Any hint why the different behaviour between w_scan and mumudvb while tuning the card?

if you need any support or debug infos please let me know.

klaus

**Comment by KlausReinhard** [comment]
Hi brice,

found and fixed first problem, when using TBS6909 which uses the mxl58x driver there is a patch available which is needed to send proper commands for unicable switch. The patch enables the rising/lowering of voltage to accept commands, simply two "break"-statements need to be removed from the mxl58x.c code.

more details found under google: "Can't make TBS6909 to work in Unicable/JESS mode"

After patching the file and installing the drivers again, both w_scan and mumudvb were able to tune to the unicable frequencies without problems. 
Now I need to find out why the DD MaxS8 card does not properly lock a signal, but I guess you can close the issue since its unlikely to be a mumudvb issue.

thx in advance for the help.

klaus

**Comment by braice** [comment]
Thank you for the investigation !

Glad you found a solution

Brice


Le mar. 6 nov. 2018 à 11:04, KlausReinhard <notifications@github.com> a
écrit :

**Comment by KlausReinhard** [comment]
close issue

**Comment by KlausReinhard** [comment]
patch of driver solved problem
