### ISSUE TITLE
HTTP unicast not supporting IPv6

### ISSUE THREAD

**Issue by DaAllexx** [braice/MuMuDVB#231]
Unfortunately, HTTP unicast streaming does not support IPv6. The `ip_http` directive currently only accepts ipv4 addresses, what makes ipv6 only deployments impossible. Is it possible to support ipv6 with unicast as well? for example:
```
# equivalent to 0.0.0.0 for ipv4
ip_http=::

# full ipv6 address
ip_http=2001:DB8:1337:42::1
```

**Comment by braice** [comment]
Hello

When I looked into it a while ago, the dual stack ipv6/ipv4 under linux was
kind of annoying to do.
Usually MuMuDVB is in a private network so not a lot of people asked for
ipv6

If you have any advise on how to implement I will be glad to review and
include

Brice


Le sam. 3 nov. 2018 à 18:21, Alexander Beck <notifications@github.com> a
écrit :

**Comment by trollcop** [comment]
I've implemented this in my fork, here: https://github.com/trollcop/MuMuDVB/commit/3fe7a9cc1eed21119b2a2387f7ef171f7bf5c038
It should be easy to merge once PR #290 is merged.
The changes are minimal.

**Comment by trollcop** [comment]
ipv6 http unicast has been merged to master, and I've done some testing using public ipv6 addresses. seems to work.

@DaAllexx wanna try it out and see?

**Comment by DaAllexx** [comment]
I just tried it and it works as expected. Thank you!
