### ISSUE TITLE
error.h: No such file or directory

### ISSUE THREAD

**Issue by danielkucera** [braice/MuMuDVB#236]
What is this include for? If I comment it out, the code compiles OK:
```
tune.c:44:10: fatal error: error.h: No such file or directory
 #include <error.h>
          ^~~~~~~~~

```

**Comment by braice** [comment]
Hello

Is it to get a description of the error messages
Did you made some code changes, the real filename have an s, it is
error*s*.h
https://github.com/braice/MuMuDVB/blob/mumudvb2/src/errors.h

brice


Le sam. 29 déc. 2018 à 17:18, Daniel Kucera <notifications@github.com> a
écrit :

**Comment by danielkucera** [comment]
Hi, I did not make any changes, it's like this in the original code from master branch:
https://github.com/braice/MuMuDVB/blob/mumudvb2/src/tune.c#L44

I was just compiling for OpenWRT.

**Comment by braice** [comment]
Hello

Ok so I think it is this one
https://www.gnu.org/software/gnulib/manual/html_node/error_002eh.html
https://code.woboq.org/userspace/glibc/misc/error.h.html

Try to remove it and let me know if the compilation is OK

Brice


Le dim. 30 déc. 2018 à 16:19, Daniel Kucera <notifications@github.com> a
écrit :

**Comment by danielkucera** [comment]
After commenting out the line, the code compiles and binary works. OpenWRT probably uses musl:
toolchain-mipsel_24kc_gcc-7.3.0_musl

**Comment by danielkucera** [comment]
It compiles without that line even with `gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) `

**Comment by danielkucera** [comment]
@braice is that include really needed?

**Comment by braice** [comment]
Indeed it is an historical left over.

https://github.com/braice/MuMuDVB/commit/2cf952139f94add5fd51d0b72cadacb163a87f70

It can be safely removed

Le lun. 7 janv. 2019 à 09:11, Daniel Kucera <notifications@github.com> a
écrit :

**Comment by braice** [comment]
Removed !!!

Thank you
!

**Comment by danielkucera** [comment]
Thank you.
I don't know why did I make that referenced pull request against my own master... :man_facepalming: 

If you are interested, here is a working OpenWRT package definition:
https://github.com/danielkucera/openwrt-packages/tree/master/mumudvb

**Comment by braice** [comment]
Le lun. 21 janv. 2019 à 18:00, Daniel Kucera <notifications@github.com> a
écrit :

> If you are interested, here is a working OpenWRT package definition:
> https://github.com/danielkucera/openwrt-packages/tree/master/mumudvb
>
>
>

Yes I am, can you do a pull request ? !

Thank you
