### ISSUE TITLE
assign individual multicast addresses for each channel without PMT

### ISSUE THREAD

**Issue by KlausReinhard** [braice/MuMuDVB#245]
HI,
I use w_scan to get all my information about PIDs etc but w_scan does not deliver the PMT PID as I found out.

Nevertheless, I would like to give possibly all channels an individual multicast address and therefore my config file need to have a list of PIDs including the PMT PID for each channel entry which I don't have explicitly.

Is there any work around/solution to handle that issue?

Many thanks in advance.
Klaus

**Comment by KlausReinhard** [comment]
I think i found solution, sorry for bothering:

1) Fetch SID-list from w_scan
2) add in conf-file list of sid in transponder 
      autoconf_sid_list=10301 10302 10303 10304 for S19E2 Transponder 11493

3) add entries for each channel with service_id and assign individual IP

new_channel
service_id=10301
ip=239.xx.yy.zz

new_channel
service_id=10302
ip=239.aa.bb.cc

etc.

**Comment by braice** [comment]
w_scan definitely knows the PMT PID (
https://www.vdr-portal.de/forum/index.php?thread/122781-w-scan-single-frequency-search/),
I think it will be a few lines change to it to output it if not already
implemented

You can try the different output formats to see if one gives the PMT already
http://manpages.ubuntu.com/manpages/bionic/man1/w_scan.1.html
