### ISSUE TITLE
cannot get lock but dvblast works

### ISSUE THREAD

**Issue by KlausReinhard** [braice/MuMuDVB#252]
Dear Brice,
I have currently the problem that a cfg for mumudvb doesn't work but the "same" values get a lock with dvblast

Any idea why?

Attach first log of mumudvb:
================================================
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 # should select needed dvbs/dvbs2
Deb2:  Main:  002 # especially for radio stations
Deb2:  Main:  003 delivery_system=DVBS2
Deb2:  Main:  004 
Deb2:  Main:  005 card=0
Deb2:  Main:  006 tuner=1
Deb2:  Main:  007 freq=11373
Deb2:  Main:  008 pol=h
Deb2:  Main:  009 srate=27500
Deb2:  Main:  010 modulation=8PSK
Deb2:  Main:  011 
Deb2:  Main:  012 unicast=1
Deb2:  Main:  013 ip_http=127.0.0.1
Deb2:  Main:  014 port_http=8005
Deb2:  Main:  015 rtp_header=0
Deb2:  Main:  016 multicast_ttl=3
Deb2:  Main:  017 
Deb2:  Main:  018 dvr_buffer_size=80
Deb2:  Main:  019 dvr_thread=1
Deb2:  Main:  020 dvr_thread_buffer_size=10000
Deb2:  Main:  021 
Deb2:  Main:  022 store_eit=1
Deb2:  Main:  023 sort_eit=1
Deb2:  Main:  024 
Deb2:  Main:  025 cam_support=0
Deb2:  Main:  026 cam_number=0
Deb2:  Main:  027 
Deb2:  Main:  028 autoconfiguration=full
Deb2:  Main:  029 # includes radio stations
Deb2:  Main:  030 # autoconf_radios=1
Deb2:  Main:  031 
Deb2:  Main:  032 # autoconf_ip4=%ip4_address%
Deb2:  Main:  033 autoconf_multicast_port=4444
Deb2:  Main:  034 autoconf_sid_list=501 504 506 507 508 509 510 530 532 533 534
Deb2:  Main:  035 rewrite_pmt=1
Deb2:  Main:  036 
Deb2:  Main:  037 sap_default_group=tvip-channels
Deb2:  Main:  038 
Deb2:  Main:  039 sat_number=2
Deb2:  Main:  040 switch_input=2
Deb2:  Main:  041 switch_type=C
Deb2:  Main:  042 diseqc_time=15
Deb2:  Main:  043 diseqc_repeat=1
Deb2:  Main:  044 
Deb2:  Main:  045 
Deb2:  Main:  046 new_channel
Deb2:  Main:  047 ip=239.110.0.0
Deb2:  Main:  048 service_id=501
Deb2:  Main:  049 name=Iran International HD
Deb2:  Main:  050 pids=5011 5012
Deb2:  Main:  051 
Deb2:  Main:  052 new_channel
Deb2:  Main:  053 ip=239.110.0.1
Deb2:  Main:  054 service_id=504
Deb2:  Main:  055 name=NASA TV HD
Deb2:  Main:  056 pids=5041 5042 5043 5044 5045
Deb2:  Main:  057 
Deb2:  Main:  058 new_channel
Deb2:  Main:  059 ip=239.110.0.2
Deb2:  Main:  060 service_id=506
Deb2:  Main:  061 name=RUDAW HD
Deb2:  Main:  062 pids=5061 5064 5062 5063
Deb2:  Main:  063 
Deb2:  Main:  064 new_channel
Deb2:  Main:  065 ip=239.110.0.3
Deb2:  Main:  066 service_id=507
Deb2:  Main:  067 name=WAAR HD
Deb2:  Main:  068 pids=5071 5072
Deb2:  Main:  069 
Deb2:  Main:  070 new_channel
Deb2:  Main:  071 ip=239.110.0.4
Deb2:  Main:  072 service_id=508
Deb2:  Main:  073 name=Kurdistan 24 HD
Deb2:  Main:  074 pids=5081 5082
Deb2:  Main:  075 
Deb2:  Main:  076 new_channel
Deb2:  Main:  077 ip=239.110.0.5
Deb2:  Main:  078 service_id=509
Deb2:  Main:  079 name=TV&TV
Deb2:  Main:  080 pids=5091 5092
Deb2:  Main:  081 
Deb2:  Main:  082 new_channel
Deb2:  Main:  083 ip=239.110.0.6
Deb2:  Main:  084 service_id=510
Deb2:  Main:  085 name=Parole di Vita
Deb2:  Main:  086 pids=5101 5102
Deb2:  Main:  087 
Deb2:  Main:  088 new_channel
Deb2:  Main:  089 ip=239.110.0.7
Deb2:  Main:  090 service_id=530
Deb2:  Main:  091 name=World Fashion Channel
Deb2:  Main:  092 pids=5301 5302
Deb2:  Main:  093 
Deb2:  Main:  094 new_channel
Deb2:  Main:  095 ip=239.110.0.8
Deb2:  Main:  096 service_id=532
Deb2:  Main:  097 name=Tesory Channel
Deb2:  Main:  098 pids=5321 5322
Deb2:  Main:  099 
Deb2:  Main:  100 new_channel
Deb2:  Main:  101 ip=239.110.0.9
Deb2:  Main:  102 service_id=533
Deb2:  Main:  103 name=NHK WORLD-JAPAN
Deb2:  Main:  104 pids=5331 5332
Deb2:  Main:  105 
Deb2:  Main:  106 new_channel
Deb2:  Main:  107 ip=239.110.0.10
Deb2:  Main:  108 service_id=534
Deb2:  Main:  109 name=Iraqia News HD
Deb2:  Main:  110 pids=5341 5342
Deb2:  Main:  111 
Deb2:  Main:  112 
Deb2:  Main:  ============ done ===========
Info:  Tune:  You will use DVB API version 5 for tuning your card.
WARN:  Main:  You want to use a thread for reading the card, please report bugs/problems
Info:  Rewrite:  You have enabled the EIT (EPG) storage for webservices
Info:  Rewrite:  You have enabled the EIT rewriting
Info:  Rewrite:  You have enabled the PMT Rewriting
WARN:  Main:  Config issue : unknow symbol : diseqc_time

Info:  Main:  New channel, current number 0
Info:  Main:  New channel, current number 1
Info:  Main:  New channel, current number 2
Info:  Main:  New channel, current number 3
Info:  Main:  New channel, current number 4
Info:  Main:  New channel, current number 5
Info:  Main:  New channel, current number 6
Info:  Main:  New channel, current number 7
Info:  Main:  New channel, current number 8
Info:  Main:  New channel, current number 9
Info:  Main:  New channel, current number 10
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 2.1.0_20181020_mumudvb2 is starting ==========
Info:  Main:  Streaming. Freq 11373000.000000
Info:  Tune:  Using DVB card "Silicon Labs Si2183" tuner 1
Info:  Tune:  Tuning DVB-S to Freq: 1623000 kHz, LO frequency 9750000 kHz Pol:H Srate=27500000, LNB number: 2
Info:  Tune:  LNB voltage 18V
Info:  Tune:  Diseqc switch position specified, we force switch input to 2
Deb0:  Tune:  Test Diseqc message e2 10 38 f2 00 00 len 4
Deb0:  Tune:  Sending first Diseqc message e2 10 38 f2 00 00 len 4
Deb0:  Tune:  Sending repeated Diseqc message e1 10 38 f2 00 00 len 4
Info:  Tune:  DISEQC SETTING SUCCEDED
Info:  Tune:  Tuning With DVB-API version 5. delivery system : 6
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....

Second log for dvblast- command: dvblast -a 0 -n 1 -f 11373000 -s 27500000 -S 2 -v 18 -m psk_8
=============================================================
DVBlast 3.0 (release)
warning: restarting
debug: compiled with DVB API version 5.10
debug: using DVB API version 5.11
debug: Frontend "Silicon Labs Si2183" supports:
debug:  frequency min: 950000, max: 2150000, stepsize: 0, tolerance: 0
debug:  symbolrate min: 1000000, max: 45000000, tolerance: 0
debug:  capabilities:
debug:   INVERSION_AUTO
debug:   FEC_1_2
debug:   FEC_2_3
debug:   FEC_3_4
debug:   FEC_5_6
debug:   FEC_7_8
debug:   FEC_AUTO
debug:   QPSK
debug:   QAM_16
debug:   QAM_32
debug:   QAM_64
debug:   QAM_128
debug:   QAM_256
debug:   QAM_AUTO
debug:   TRANSMISSION_MODE_AUTO
debug:   GUARD_INTERVAL_AUTO
debug:   HIERARCHY_AUTO
debug:   2G_MODULATION
debug:   MULTISTREAM
debug:   FE_CAN_MUTE_TS
debug:  delivery systems:
debug:   DVBS
debug:   DVBS2
debug:   DSS
debug: frequency 11373000 is in Ku-band (lower)
debug: configuring LNB to v=18 p=0 satnum=2 uncommitted=0
debug: tuning DVB-S frontend to f=11373000 srate=27500000 inversion=-1 fec=999 rolloff=35 modulation=psk_8 pilot=-1 mis=0
debug: CA interface with 1 slot
debug:   CI link layer level interface type
debug:   0 available descramblers (keys)
CAM none
debug: setting filter on PID 0
debug: setting filter on PID 16
debug: setting filter on PID 17
debug: setting filter on PID 18
debug: setting filter on PID 19
debug: setting filter on PID 20
error: no config file
debug: frontend has acquired signal
debug: frontend has acquired carrier
debug: frontend has acquired stable FEC
debug: frontend has acquired sync
info: frontend has acquired lock
lock status: 1
debug: - Bit error rate: 0
debug: - Signal strength: 40672
debug: - SNR: 44280
debug: new PAT tsid=900 version=14
debug:   * NIT pid=16
debug:   * program number=501 pid=5010
debug:   * program number=504 pid=5040
debug:   * program number=506 pid=5060
debug:   * program number=507 pid=5070
debug:   * program number=508 pid=5080
debug:   * program number=509 pid=5090
debug:   * program number=510 pid=5100
debug:   * program number=530 pid=5300
debug:   * program number=532 pid=5320
debug:   * program number=533 pid=5330
debug:   * program number=534 pid=5340
debug:   * program number=1303 pid=1760
debug: end PAT
debug: new SDT actual tsid=900 version=14 onid=318
debug:   * service sid=501 running=4
debug:     - desc 48 service type=0x1 provider="ABS" service="Iran International HD"
debug:   * service sid=504 running=4
debug:     - desc 48 service type=0x1 provider="" service="NASA TV HD"
debug:   * service sid=506 eit_pf running=4
debug:     - desc 48 service type=0x1 provider="" service="RUDAW HD"
debug:   * service sid=507 eit_pf running=4
debug:     - desc 48 service type=0x1 provider="Waar" service="WAAR HD"
debug:   * service sid=508 running=4
debug:     - desc 48 service type=0x1 provider="" service="Kurdistan 24 HD"
debug:   * service sid=509 eit_pf running=4
debug:     - desc 48 service type=0x1 provider="M-Three satcom" service="TV&TV"
debug:   * service sid=510 eit_pf running=4
debug:     - desc 48 service type=0x1 provider="M-Three satcom" service="Parole di Vita"
debug:   * service sid=530 running=4
debug:     - desc 48 service type=0x19 provider="DVB" service="World Fashion Channel"
debug:   * service sid=532 eit_pf running=4
debug:     - desc 48 service type=0x1 provider="M-Three satcom" service="Tesory Channel"
debug:   * service sid=533 running=4
debug:     - desc 48 service type=0x19 provider="" service="NHK WORLD-JAPAN"
debug:   * service sid=534 running=4
debug:     - desc 48 service type=0x19 provider="Nilesat" service="Iraqia News HD"

**Comment by KlausReinhard** [comment]
close the issue by myself - found that wait-time between diseqc messages is important.
dvblast waits 100ms (officially 15ms required) between diseqc messages which seems to make the difference for the driver.

**Comment by braice** [comment]
Thank you for solving it so quickly.
I was looking if this was not an issue in the Diseqc setting.

I will put the timing question in the FAQ

Brice

**Comment by KlausReinhard** [comment]
Dear Brice,
I extended the tune.[ch] catering for a configurable timing between the diseqc/unicable-switch commands using diseqc_time and  a pin_number for unicable. Furthermore I re-wrote a bit the handling, splitting between disqec and unicable to  change things more comfortably.

May I send you the patchfile? / Would it be possible to include the changes in the development?

thx, Klaus

**Comment by braice** [comment]
Hi

I will be glad to check/include your changes. Can you please fork/patch/do
a pull request through github?

Thank you

**Comment by KlausReinhard** [comment]
Hi,
since I'm doing that first time I may need some suport:

I created my own branch "diseqc_unicable_extensions" from mumudvb2 and made the changes and committed them.

Now I tried to push it with "git push --set-upstream origin diseqc_unicable_extensions" but failed with

remote: Permission to braice/MuMuDVB.git denied to KlausReinhard.

What step am I missing or do you need to enable me?

thx,
Klaus

**Comment by KlausReinhard** [comment]
I believe I gave correct Username/PWD I was asked for.

**Comment by KlausReinhard** [comment]
... getting their - did as you suggested: fork/patch/pull request

**Comment by braice** [comment]
Hello

Sorry I thought this was closed.

You can do the commit from git in your own fork (not in my repo you do not
have rights to write to it) but then the pull request from github web
interface, it's almost simpler

https://guides.github.com/activities/hello-world/

If you still struggle, just send me a patch/bundle and I will merge it the
old fashioned way (and of course, please put correctly the authorship so
you get credit)
https://git-scm.com/book/en/v2/Git-Tools-Bundling


Brice
