### ISSUE TITLE
Unable to unscramble channels with latest OSCAM

### ISSUE THREAD

**Issue by scramatte** [braice/MuMuDVB#258]
Hi,

I'm trying to unscramble channels using  oscam 1.20  r11572-798  build from following git repository https://github.com/oscam-emu/oscam-patched

Everything looks ok, I see ECM requests into oscam log but channels still scrambled :

`Channel "Chan1"  is now highly scrambled (97% of scrambled packets). Card 2`

Note I'm running debian 10, with TBS tuner cards and MumuDVB build from Github repository too.

```
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.11.
Built with support for DVB-T2.


```
I suspect that is might due to dvbapi version that is different between MumuDVB and Oscam
` (dvbapi) Using /tmp/camd.socket listen socket, API forced to DVBAPIv3 (0), userconfig boxtype: 11`
And looks that MumuDVB use version 5.11 ...

Regards

**Comment by Ro-Den** [comment]
I've got the same problem using mumudvb_2.0.0-dmo2+bp1_amd64.deb with oscam-svn_1.20.10176+svn202005241631~ubuntu19.10.1_amd64.deb & oscam-1.20_svn11581 built by myself.

mumudvb_2.1.0-dmo1_amd64.deb works fine with both OSCAMs.

So, I guess it is MuMuDVB issue.

**Comment by braice** [comment]
So it's more an issue of package as you say it works with the latest MuMuDVB

**Comment by marian34-git** [comment]
Same problem.
### Not work descramble:
```
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.11.
Built with support for DVB-T2.

Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)
```


### version work:

```
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.

Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)
```

**Comment by braice** [comment]
Hello

I think it is worth a shot to ask on the mailing list, the people who
developed the oscam support are there

Brice

**Comment by Ro-Den** [comment]
Just tested MuMuDVB with OSCam-Emu, both built from the latest sources. Same issue. MuMuDVB built with support for DVB API Version 5.11 doesn't work with OSCam-Emu. There are also a lot of strange warnings in VLC log:

>ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)
ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)
ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)
ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)
ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)
ts warning: scrambled state changed on pid 100 (1->0)
ts warning: scrambled state changed on pid 100 (0->1)

MPV doesn't play the stream either.

MuMuDVB built with support for DVB API Version 5.10 works fine.

**Comment by braice** [comment]
How did you choose the specific build version of the DVB API

This is very strange and as I don't understand the OScam internals it's
hard to me to help further besides having in this issue how to build with
the 5.10

**Comment by Saentist** [comment]
Is in settings in oscam on DVBAPI page have writenn port number?
