### ISSUE TITLE
mumudvb not working 

### ISSUE THREAD

**Issue by mgelecomnet** [braice/MuMuDVB#260]
Hi
Iv installed ubuntu 18 and TBS 6904 DVBS/S2 card and mumudvb
but Mumudvb doesn't work !
But the DVBLAST works well,  I got the multicast with the VLC .
Can anyone help me?

root@iptv:~# mumudvb -d -c conf.txt -vvv
MuMuDVB Version 1.7.1
 --- Build information ---
Built with CAM support.
Built without transcoding support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 autoconfiguration=full
Deb2:  Main:  002 freq=11938
Deb2:  Main:  003 pol=v
Deb2:  Main:  004 srate=27500
Deb2:  Main:  ============ done ===========
Info:  Main:  ========== End of configuration, MuMuDVB version 1.7.1 is starting ==========
Info:  Main:  Streaming. Freq 11938000
Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVB-S/S2 " tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1338000 kHz, LO frequency 10600000 kHz Pol:V Srate=27500000, LNB number: 0
Info:  Tune:  LNB voltage 13V
Info:  Tune:  DISEQC SETTING SUCCEDED
Deb0:  Tune:  polling....
Deb0:  Tune:  Getting frontend event
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Deb0:  Tune:  Getting frontend event
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:       FE_HAS_VITERBI : FEC is stable
Info:  Tune:       FE_HAS_SYNC : found sync bytes
Info:  Tune:       FE_HAS_LOCK : everything's working...
Info:  Tune:  Event:  Frequency: 11938000 (or 9262000)
Info:  Tune:          SymbolRate: 27500000
Info:  Tune:          FEC_inner:  5
Info:  Tune:  Bit error rate: 0
Info:  Tune:  Signal strength: 24272
Info:  Tune:  SNR: 0
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:       FE_HAS_VITERBI : FEC is stable
Info:  Tune:       FE_HAS_SYNC : found sync bytes
Info:  Tune:       FE_HAS_LOCK : everything's working...
Info:  Main:  Card 0, tuner 0 tuned
Deb1:  DVB:  Setting filter for PID 0
Deb1:  DVB:  Setting filter for PID 1
Deb1:  DVB:  Setting filter for PID 16
Deb1:  DVB:  Setting filter for PID 17
Deb1:  DVB:  Setting filter for PID 18
Deb1:  DVB:  Setting filter for PID 20
Info:  Main:  Diffusion 0 channel

Info:  Main:  End of streaming. We streamed during 0d 0:00:11
Info:  Main:  Caught signal 2 - closing cleanly.
Deb1:  Main:  Signal/power Thread closing
Deb1:  Main:  Monitor Thread closing
Deb1:  Main:  Monitor thread stopping, it lasted 10.000000 seconds
Info:  Main:  ========== MuMuDVB version 1.7.1 is stopping with ExitCode 0 ==========
root@iptv:~#

**Comment by kslimani** [comment]
According provided logs, you are using version 1.7.1 which is very old (2012 !). Have you tried to compile latest version 2.1.0 ? (or even better, compiling current master branch which have many fixes, but no release tag yet).

**Comment by mgelecomnet** [comment]
Iv installed mumudvb v2.1 today but the same as 1.7.1 
channels doesn't stream !!

 root@iptv:~# mumudvb -d -c conf.txt -vvv
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built without CAM support.
Built with SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 autoconfiguration=full
Deb2:  Main:  002 freq=11938
Deb2:  Main:  003 pol=v
Deb2:  Main:  004 srate=27500
Deb2:  Main:  ============ done ===========
Info:  Main:  ========== End of configuration, MuMuDVB version 2.1.0_20181020_mumudvb2 is starting ==========
WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
Info:  Main:  Streaming. Freq 11938000.000000
Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVB-S/S2 " tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 1338000 kHz, LO frequency 10600000 kHz Pol:V Srate=27500000, LNB number: 0
Info:  Tune:  LNB voltage 13V
Info:  Tune:  DISEQC SETTING SUCCEDED
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Info:  Tune:       FE_HAS_SIGNAL : found something above the noise level
Info:  Tune:       FE_HAS_CARRIER : found a DVB signal
Info:  Tune:       FE_HAS_VITERBI : FEC is stable
Info:  Tune:       FE_HAS_SYNC : found sync bytes
Info:  Tune:       FE_HAS_LOCK : everything's working...
Info:  Tune:  Event:  Frequency: 11938000 (or 9262000)
Info:  Tune:          SymbolRate: 27500000
Info:  Tune:          FEC_inner:  5
Info:  Tune:  Bit error rate: 0
Info:  Tune:  Signal strength: 24272
Info:  Tune:  SNR: 36080
Info:  Main:  Card 0, tuner 0 tuned
main 0x7ffcf85bfee0
Info:  Common chan:  Looking through all services to update their filters
Deb0:  Common chan:  Open the new filters
Deb1:  DVB:  Setting filter for PID 0
Deb1:  DVB:  Setting filter for PID 1
Deb1:  DVB:  Setting filter for PID 16
Deb1:  DVB:  Setting filter for PID 17
Deb1:  DVB:  Setting filter for PID 18
Deb1:  DVB:  Setting filter for PID 20
Info:  Main:  Diffusion 0 channel

**Comment by kslimani** [comment]
That's strange, i am also using TBS 6904 with MumuDVB and it works.

Would you mind to share your configuration file ?

For example, ensure it contains `delivery_system=DVBS2` directive.
EDIT: or `delivery_system=DVBS` if applicable (more info [here](http://mumudvb.net/documentation/asciidoc/mumudvb-2.0.0/README_CONF.html))

**Comment by Saentist** [comment]
Is w-scan found anything?

**Comment by mgelecomnet** [comment]
Hi
Thanks for reply
yes W_scan found signal
----------------------------------------
this is my config file:
card=0
autoconfiguration=full
freq=11996
pol=h
srate=27500
delivery_system=DVBS
modulation=QPSK
------------------------------------------
this is w_scan log:
RFI Francais;GLOBECAST:11996:hC34M2O0S0:S26E0:27500:0:2020@3:0:0:20:702:509:0
France 24 (in Arabic);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:2260=2:2220@3:0:0:22:702:509:0
BBC Arabic;BBC World Service:11996:hC34M2O0S0:S26E0:27500:2360=2:2320=ara@3:0:0:23:702:509:0
CNBC Arabiya;du:11996:hC34M2O0S0:S26E0:27500:2460=2:2301=ara@3:0:0:24:702:509:0
Sky News Arabia;Sky News Arabia:11996:hC34M2O0S0:S26E0:27500:2560=2:2520=Ara@3:0:0:25:702:509:0
BBC Arabic HD;ARABSAT:11996:hC34M2O0S0:S26E0:27500:3060=27:3020=ara@17:0:0:30:702:509:0
France 24 (en Français);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:3160=2:3120=fra@3:251:0:31:702:509:0
France 24 (in English);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:3260=2:3220=eng@3:0;902:0:32:702:509:0
Sky News Arabia Radio;Sky News Arabia:11996:hC34M2O0S0:S26E0:27500:0:2521=FM@3:0:0:35:702:509:0
CNBC Arabiya R1;du:11996:hC34M2O0S0:S26E0:27500:0:2301=eng@4:0:0:41:702:509:0
WRN (Sawt Al Alam) R1;Globecast:11996:hC34M2O0S0:S26E0:27500:0:4220=eng@3:0:0:42:702:509:0
BBC World Service Arabic;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:6752=ara@3:0:0:45:702:509:0
BBC World Service English Middle East;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:6662=eng@3:0:0:46:702:509:0
BBC Horn of Africa;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:4760=und@3:0:0:47:702:509:0
RMC Doualia;GLOBECAST:11996:hC34M2O0S0:S26E0:27500:0:1608@3:0:0:51:702:509:0

**Comment by Saentist** [comment]
> ## Hi
> Thanks for reply
> yes W_scan found signal
> ## this is my config file:
> card=0
> autoconfiguration=full
> freq=11996
> pol=h
> srate=27500
> delivery_system=DVBS
> modulation=QPSK
> this is w_scan log:
```
RFI Francais;GLOBECAST:11996:hC34M2O0S0:S26E0:27500:0:2020@3:0:0:20:702:509:0
France 24 (in Arabic);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:2260=2:2220@3:0:0:22:702:509:0
BBC Arabic;BBC World Service:11996:hC34M2O0S0:S26E0:27500:2360=2:2320=ara@3:0:0:23:702:509:0
CNBC Arabiya;du:11996:hC34M2O0S0:S26E0:27500:2460=2:2301=ara@3:0:0:24:702:509:0
Sky News Arabia;Sky News Arabia:11996:hC34M2O0S0:S26E0:27500:2560=2:2520=Ara@3:0:0:25:702:509:0
BBC Arabic HD;ARABSAT:11996:hC34M2O0S0:S26E0:27500:3060=27:3020=ara@17:0:0:30:702:509:0
France 24 (en Français);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:3160=2:3120=fra@3:251:0:31:702:509:0
France 24 (in English);France Médias Monde:11996:hC34M2O0S0:S26E0:27500:3260=2:3220=eng@3:0;902:0:32:702:509:0
Sky News Arabia Radio;Sky News Arabia:11996:hC34M2O0S0:S26E0:27500:0:2521=FM@3:0:0:35:702:509:0
CNBC Arabiya R1;du:11996:hC34M2O0S0:S26E0:27500:0:2301=eng@4:0:0:41:702:509:0
WRN (Sawt Al Alam) R1;Globecast:11996:hC34M2O0S0:S26E0:27500:0:4220=eng@3:0:0:42:702:509:0
BBC World Service Arabic;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:6752=ara@3:0:0:45:702:509:0
BBC World Service English Middle East;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:6662=eng@3:0:0:46:702:509:0
BBC Horn of Africa;BBC World Service:11996:hC34M2O0S0:S26E0:27500:0:4760=und@3:0:0:47:702:509:0
RMC Doualia;GLOBECAST:11996:hC34M2O0S0:S26E0:27500:0:1608@3:0:0:51:702:509:0
```

Format your post to be easy for reading

try to run **mumudvb** with bath file 
```
echo -e "Fix folder missing"
mkdir /run/mumudvb
echo -e "DVB-S"
mumudvb -c /conf-location/mumuS0.conf
echo -e "DVB-T"
mumudvb -c /conf-location/mumuT0.conf
```

**Comment by mgelecomnet** [comment]
Hi
I run mumudvb in bash but no udp output.
iv installed dbvlast and tvheadend on this server , everything is ok 
but i don't know why mumudvb doesn't work !!!

**Comment by kslimani** [comment]
Like Saentist described, ensure the mumudvb directory exists :
_(this should not be related to your issue, but will remove some WARN messages)_

```shell
mkdir -p /var/run/mumudvb
```

I guess you are trying retrieve channels from Badr X 26° E ?

Also could you verify in your config file that `freq=11996`, because in your debug log i can read 11938 instead of 11996.

**Comment by braice** [comment]
Hello

I would agree on the frequency check first as in some of your logs I see
11996 and in some 11938

Deb2: Main: ==== Configuration file ====
Deb2: Main: 001 autoconfiguration=full
Deb2: Main: 002 freq=11938
Deb2: Main: 003 pol=v
Deb2: Main: 004 srate=27500
Deb2: Main: ============ done ===========

Normally the TBS works pretty well in full auto but the delivery system
must be set if this is a dvb-s2 transponder ...

Then I would look at modulation or other stuff

Brice

**Comment by mgelecomnet** [comment]
Hi 
yes i am trying to receive channels on badr 26E - some TP 11938v,dvbs -11996h,dvbs - 11900v,dvbs
i checked /run but mumudvb was not exist and after make it and run mumudvb-  2 file created by 0 byte of size.
channels_streamed_adapter0_tuner0 
channels_unstreamed_adapter0_tuner0
and not output

**Comment by mgelecomnet** [comment]
i will focus on 11900v 27500 DVBS 
it is on card=1
----------------------------------
and  this is dvblast test:

root@ubuntu:~# dvblast -f 11900000 -s 27500000 -a 1
DVBlast 3.0 (release)
warning: restarting
debug: compiled with DVB API version 5.10
debug: using DVB API version 5.11
debug: Frontend "TurboSight TBS 6904 DVB-S/S2 " supports:
debug:  frequency min: 950000, max: 2150000, stepsize: 1011, tolerance: 5000
debug:  symbolrate min: 1000000, max: 45000000, tolerance: 0
debug:  capabilities:
debug:   INVERSION_AUTO
debug:   FEC_1_2
debug:   FEC_2_3
debug:   FEC_3_4
debug:   FEC_4_5
debug:   FEC_5_6
debug:   FEC_6_7
debug:   FEC_7_8
debug:   FEC_AUTO
debug:   QPSK
debug:   2G_MODULATION
debug:   FE_CAN_RECOVER
debug:  delivery systems:
debug:   DVBS
debug:   DVBS2
debug: frequency 11900000 is in Ku-band (higher)
debug: configuring LNB to v=13 p=0 satnum=0 uncommitted=0
debug: tuning DVB-S frontend to f=11900000 srate=27500000 inversion=-1 fec=999 rolloff=35 modulation=legacy pilot=-1 mis=0
warning: failed opening CAM device /dev/dvb/adapter1/ca0 (No such file or directory)
debug: setting filter on PID 0
debug: setting filter on PID 16
debug: setting filter on PID 17
debug: setting filter on PID 18
debug: setting filter on PID 19
debug: setting filter on PID 20
error: no config file
debug: frontend has acquired signal
debug: frontend has acquired carrier
debug: frontend has acquired stable FEC
debug: frontend has acquired sync
info: frontend has acquired lock
lock status: 1
debug: - Bit error rate: 67108863
debug: - Signal strength: 67096447
debug: - SNR: 67067928
debug: new PAT tsid=300 version=4
debug:   * NIT pid=16
debug:   * program number=301 pid=301
debug:   * program number=302 pid=302
debug:   * program number=303 pid=303
debug:   * program number=304 pid=304
debug:   * program number=306 pid=306
debug:   * program number=307 pid=307
debug:   * program number=308 pid=308
debug:   * program number=310 pid=310
debug:   * program number=351 pid=351
debug:   * program number=352 pid=352
debug:   * program number=353 pid=353
debug:   * program number=354 pid=354
debug:   * program number=355 pid=355
debug:   * program number=357 pid=357
debug:   * program number=358 pid=358
debug:   * program number=359 pid=359
debug: end PAT
debug: new SDT actual tsid=300 version=4 onid=3622
debug:   * service sid=301 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB TV1"
debug:   * service sid=302 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB TV2"
debug:   * service sid=303 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB TV3"
debug:   * service sid=304 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB TV4"
debug:   * service sid=306 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRINN"
debug:   * service sid=307 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB AMOOZESH"
debug:   * service sid=308 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB SALAMAT"
debug:   * service sid=310 running=4
debug:     - desc 48 service type=0x1 provider="IRIB" service="IRIB SEPEHR"
debug:   * service sid=351 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO IRAN"
debug:   * service sid=352 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO PAYAM"
debug:   * service sid=353 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO JAVAN"
debug:   * service sid=354 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO MAAREF"
debug:   * service sid=355 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO FARHANG"
debug:   * service sid=357 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO VARZESH"
debug:   * service sid=358 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO QURAN"
debug:   * service sid=359 running=4
debug:     - desc 48 service type=0x2 provider="IRIB" service="RADIO MONASEBATI(MOHARAM)"
debug: end SDT
debug: new NIT actual networkid=3622 version=4
debug:     - desc 40 networkname="11900 TA"
debug:   * ts tsid=300 onid=3622
debug:     - desc 43 dvb-s frequency=11900000V pos=26.0E modulation=qpsk symbolrate=27500000 fecinner=3/4
debug:     - desc 41 service_list sid=301 type=0x01
debug:     - desc 41 service_list sid=302 type=0x01
debug:     - desc 41 service_list sid=303 type=0x01
debug:     - desc 41 service_list sid=304 type=0x01
debug:     - desc 41 service_list sid=306 type=0x01
debug:     - desc 41 service_list sid=307 type=0x01
debug:     - desc 41 service_list sid=308 type=0x01
debug:     - desc 41 service_list sid=310 type=0x01
debug:     - desc 41 service_list sid=351 type=0x02
debug:     - desc 41 service_list sid=352 type=0x02
debug:     - desc 41 service_list sid=353 type=0x02
debug:     - desc 41 service_list sid=354 type=0x02
debug:     - desc 41 service_list sid=355 type=0x02
debug:     - desc 41 service_list sid=357 type=0x02
debug:     - desc 41 service_list sid=358 type=0x02
debug:     - desc 41 service_list sid=359 type=0x02
debug:   * ts tsid=100 onid=3622
debug:     - desc 43 dvb-s frequency=11880000H pos=26.0E modulation=qpsk symbolrate=27500000 fecinner=3/4
debug:   * ts tsid=700 onid=3622
debug:     - desc 43 dvb-s frequency=12264000H pos=26.0E modulation=qpsk symbolrate=27500000 fecinner=3/4
debug:   * ts tsid=800 onid=3622
debug:     - desc 43 dvb-s frequency=12283000V pos=26.0E modulation=qpsk symbolrate=30000000 fecinner=7/8
debug:   * ts tsid=200 onid=3622
debug:     - desc 43 dvb-s frequency=12302000H pos=26.0E modulation=qpsk symbolrate=32000000 fecinner=3/4
debug:   * ts tsid=600 onid=3622
debug:     - desc 43 dvb-s frequency=12322000V pos=26.0E modulation=qpsk symbolrate=30000000 fecinner=2/3
debug: end NIT

**Comment by kslimani** [comment]
According [kingofsat](https://fr.kingofsat.net/pos-26E.php), there is nothing on 11900 vertical.

But, let's focus instead on 11938 vertical DVB-S.

If you set `card=1` it is the __second input__ of the four card inputs. (first is 0).

Also modulation parameter should not be required.

Also if you are using a DiSEqC i recommend to set __sat_number__ with the proper value (1 to 4).

Your configuration file should be something like :

```ini
card=1
tuner=0

delivery_system=DVBS
freq=11938
pol=v
srate=27500

timeout_no_diff=0
common_port=2000

# Alternatively, comment the autoconfiguration parameter and uncomment
# the following line bloc
autoconfiguration=full

# new_channel
# ip=224.1.1.1
# name=ERI TV
# service_id=593
# pmt_pid=127
# pids=998 569
```

**Comment by mgelecomnet** [comment]
dear kslimani thanks for help
With this configuration, I encountered the following error.
" ERRO:  Multicast:  ip : You have to start a channel first (using new_channel) "
After several attempts, I realized that I needed to add a space after "new_channel" in config file.
Now the problem is solved and I can to get the video by  VLC.
Also, in the previous settings, after " autoconfiguration=full" , i need to add a space so that mumudvb can send all the services.
is it normal ?
----------
mumudvb log:
root@iptv:~# mumudvb -d -c conf1.txt -vvv
MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built without CAM support.
Built with SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.

Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 card=1
Deb2:  Main:  002 tuner=0
Deb2:  Main:  003
Deb2:  Main:  004 delivery_system=DVBS
Deb2:  Main:  005 freq=11938
Deb2:  Main:  006 pol=v
Deb2:  Main:  007 srate=27500
Deb2:  Main:  008
Deb2:  Main:  009 timeout_no_diff=0
Deb2:  Main:  010 common_port=2000
Deb2:  Main:  011
Deb2:  Main:  012
Deb2:  Main:  013 #autoconfiguration=full
Deb2:  Main:  014
Deb2:  Main:  015 new_channel
Deb2:  Main:  016 ip=224.1.1.1
Deb2:  Main:  017 name=ERI TV
Deb2:  Main:  018 service_id=593
Deb2:  Main:  019 pmt_pid=127
Deb2:  Main:  020 pids=998 569
Deb2:  Main:  ============ done ===========
Info:  Tune:  You will use DVB API version 5 for tuning your card.
ERRO:  Multicast:  ip : You have to start a channel first (using new_channel)
root@iptv:~#

**Comment by kslimani** [comment]
I think spaces (new line) are expected in configuration file.

As described in documentation, configuration file has two parts. ("common" and "channel").

For more details, see [General behaviour](http://mumudvb.net/documentation/asciidoc/mumudvb-2.0.0/README_CONF.html#_general_behavior) chapter.

**Comment by mgelecomnet** [comment]
Do you have a recommendation to use the mumudvb for 300 simultaneous users as a unicast?
16 tuner on 4 adapter 
50 services maximum 3Mbps per channel.
And What is the minimum recommended hardware?

**Comment by kslimani** [comment]
> 
> Do you have a recommendation to use the mumudvb for 300 simultaneous users as a unicast?
> 16 tuner on 4 adapter
> 50 services maximum 3Mbps per channel.
> And What is the minimum recommended hardware?

I don't know about unicast, i mainly used only multicast without automatic configuration.

About hardware, with multicast scenario, MumuDVB use less than 1% CPU, but i don't know about unicast.

Also i would check the card PCI express maximum bandwidth and ensure that motherboard bus can handle 4.

Someone else may hopefully answer you about unicast...

**Comment by anphsw** [comment]
Pure receiving (without scrambling) can be used at almost any PC. On Celeron G3900 and 5*tbs6902 it uses about 20% CPU in unicast installation. All other CPU overhead will increase as client bandwith usage will grow.
Better to use multicast where it possible.
Recommended hardware with 16TPs will be about Core i3 9100F or comparable 4-core processor.

**Comment by malakudi** [comment]
Problem was configuration specific and was resolved. This issue can be closed.

**Comment by braice** [comment]
Good catch, closed.
Happy to get your help feel free to send me a personal email (you will find the address on the website)
