### ISSUE TITLE
QUESTION: How to reduce quaility and restream?

### ISSUE THREAD

**Issue by pawlosck** [braice/MuMuDVB#263]
How to reduce quality/resolution stream and restream in unicast mode.

Yes, I know, there is info about it using multicast and ffserver, but currently ffserver project is closed.

How to do that using other soft or mumudvb?
I want to stream for vlc with epg and for web (with epg - it could be great, but video and audio can be enought too). Video tag doesn't support it or I can't implement it.

FFmpeg can restream using udp://, but it works only in VLC for linux desktop (under windows not tested). VLC (Android) doesn't support it or I can't activate it.
I tried other methods, but I couldn't run ffmpeg. There were messages about no permissions to run tcp:// or similar. I run it using root account.

**Comment by Saentist** [comment]
Multicast and wireless is not good combination, use http-ts streaming.

**Comment by pawlosck** [comment]
I know. Multicast is horrible. I had huge problems with LAN, when I tried use multicast.

http-ts -> What is this? Is it package for node.js?

**Comment by Saentist** [comment]
It's  other ouput of Mumudvb
enable http interface and will see it 
for more information RTFM

----
My advice is to disable multicast except you use IGMP snooping software or hardware.

**Comment by pawlosck** [comment]
RTFM -> no comment

I asked, because ffmpeg contains mpegts output, so I thought it's connected with ffmpeg.

I searched documentation, but I can't find http-ts. What I should search for? Is it options "ip_http" and "port_http"

It's my config. Do I should add/modify/remove something in this config?

card=0
tuner=0
freq=674MHz
autoconfiguration=full
autoconf_radios=1
multicast_ipv4=0
multicast_ipv6=0
unicast=1
ip_http=0.0.0.0
port_http=7128
sap=1
autoconf_unicast_start_port=6100
store_eit=1

**Comment by braice** [comment]
There was some experiment at transcoding inside MuMuDVB but it was
pretty difficult, the documentation contains information how to transcode
and restream with outside tools

**Comment by pawlosck** [comment]
Could you send me link to documention? I can't find this. I found a lot of things, but I can't find information how to transcode
and restream with outside tools.

I found solution, how to restream using ffmpeg (I had to add option "listen"), but I have problem, because ffmpeg is closing when client disconnect.

ffmpeg -i http://localhost:7000 -codec copy -listen 1 -f avi "http://0.0.0.0:7011" -> this works, but ffmpeg is closing.

With "listen 2" I can't connect to ffmpeg. Netstat display ffmpeg as listening app.


I tried to use mkvserver_mk2 too, but it doesn't work for me.

**Comment by Saentist** [comment]
http://mumudvb.net/documentation/asciidoc/mumudvb-2.1.0/TRANSCODE_EXTERNAL.html

Nginx
https://github.com/CESNET/UltraGrid/wiki/Live-web-streaming-with-Nginx

there is lot of LIVE transcoding projects.

**Comment by braice** [comment]
This might be old but I hope it helps

http://mumudvb.net/documentation/asciidoc/mumudvb-2.1.0/TRANSCODE_EXTERNAL.html

**Comment by pawlosck** [comment]
> http://mumudvb.net/documentation/asciidoc/mumudvb-2.1.0/TRANSCODE_EXTERNAL.html
> 
This tutorial need ffserver which is not active project.
http://trac.ffmpeg.org/wiki/ffserver
Warning: ffserver has been removed on 2018-01-06. If you still need it checkout commit 2ca65fc or use the 3.4 release branch. 


> Nginx
> https://github.com/CESNET/UltraGrid/wiki/Live-web-streaming-with-Nginx
> 
I am using Apache, so I can't install Nginx.

> there is lot of LIVE transcoding projects.

Could you give more other projects or tutorials? It would be great, if these project will be open source.

**Comment by pawlosck** [comment]
> This might be old but I hope it helps http://mumudvb.net/documentation/asciidoc/mumudvb-2.1.0/TRANSCODE_EXTERNAL.html

This tutorial need ffserver which is not active project.
http://trac.ffmpeg.org/wiki/ffserver
Warning: ffserver has been removed on 2018-01-06. If you still need it checkout commit 2ca65fc or use the 3.4 release branch.

**Comment by kslimani** [comment]
> 
> I am using Apache, so I can't install Nginx.
> 
You can install Nginx with Apache, just don't bind on same http port number.

**Comment by pawlosck** [comment]
> > I am using Apache, so I can't install Nginx.
> 
> You can install Nginx with Apache, just don't bind on same http port number.

Ok, maybe other words. I don't want to install second web server. I never use Nginx and I don't know how to configure it. This host is available in the Internet and I want to install minimal number of apps. More applications (especially network apps), more hacking possibilities. Just security.

**Comment by Saentist** [comment]
NGINX can accelerate your Apache (with is main propose of nginx)

**Comment by malakudi** [comment]
> How to reduce quality/resolution stream and restream in unicast mode.
> 
> Yes, I know, there is info about it using multicast and ffserver, but currently ffserver project is closed.
> 
> How to do that using other soft or mumudvb?
> I want to stream for vlc with epg and for web (with epg - it could be great, but video and audio can be enought too). Video tag doesn't support it or I can't implement it.
> 
> FFmpeg can restream using udp://, but it works only in VLC for linux desktop (under windows not tested). VLC (Android) doesn't support it or I can't activate it.
> I tried other methods, but I couldn't run ffmpeg. There were messages about no permissions to run tcp:// or similar. I run it using root account.

MuMuDVB doesn't do transcoding. It only streams original streams. This is no issue of MumuDVB, so it can be closed.
