### ISSUE TITLE
Problems on receiving Radio Channels

### ISSUE THREAD

**Issue by SourceDoctor** [braice/MuMuDVB#273]
Satellite: Astra 19.2 E
Transponderfrequency: 11053 h

Log says this continously and i cannot receive most of the Radio Channels anymore.

```
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 73
WARN:  TS:  Too many full packets, we skip one size 106
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
```

Do not know the real reason, maybe some specific cases are not handled.
Restart did not solve the issue.

**Comment by braice** [comment]
Hello.
Can you please send us a log in very verbose mode?
I have an idea of what could be the issue but I would like to check

Thank you
Brice

**Comment by SourceDoctor** [comment]
i pasted you the full output og very verbose mode.
After 1-2 minutes very verbose mode stops running by itself.
Hope this helps on debugging

Logfile is to long to be pasted here.
You can download it here:

[ftp://ftp.berberich.info/log.txt](ftp://ftp.berberich.info/log.txt)

**Comment by SourceDoctor** [comment]
@braice 
was something useful in logfile?

**Comment by braice** [comment]
Hello

Thank you for the complete logs

I am seeing two things.
There seems to be some continuity counter mismatch, is the reception good ?
The EIT rewrite seems to be a bit flooded, in order to narrow down the bug
source could you disable it and try again?

Thank you

**Comment by SourceDoctor** [comment]
the receiption is very well.
i have this problem on a 90cm antenna, and also on a 350cm antenna.


i run another test.
But now i changed store_eit from 1 to 0, as requested.

ftp://ftp.berberich.info/log2.txt

with store_eit = 1 i still have :
```
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
WARN:  TS:  Too many full packets, we skip one size 18
```

**Comment by braice** [comment]
Ok

Could you try disabling eit rewrite and send the logs again ?

Thank you

**Comment by SourceDoctor** [comment]
I hope this configuraition is what you mean

Logfile: ftp://ftp.berberich.info/log3.txt

```
card=7
freq=11053
pol=h
srate=22000
sat_number=0

# running with DVB_API 5
delivery_system=DVBS2

# timeout_no_diff: If no channels are streamed, MuMuDVB will kill himself after this time (specified in seconds)
timeout_no_diff=3
tuning_timeout=10

rewrite_sdt=0
rewrite_eit=0
sort_eit=0
store_eit=0
unicast=1
ip_http=127.0.0.1
port_http=8012

multicast_ttl=10
multicast_auto_join=1
multicast_ipv4=1
multicast_iface4=vlan20_2

sap=0

autoconfiguration=full
autoconf_scrambled=1
autoconf_radios=1

autoconf_ip4=239.1.%sid_hi.%sid_low
common_port=1234

cam_support=0

```

**Comment by braice** [comment]
Hello

In the logs it looks fine, does it work as expected on your side ?

Brice

**Comment by SourceDoctor** [comment]
At moment everything seems to be fine.
When recognizing it again i try to record a dump an reopen this issue.
