### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock chan_p.lock

### ISSUE THREAD

**Issue by ycaibb** [braice/MuMuDVB#274]
Hi, developers, thank you for your checking. It seems the lock `chan_p.lock` is not released correctly when `mumu_init_chan(&chan_p.channels[ichan])<0`?
https://github.com/braice/MuMuDVB/blob/9c9441896b6393bcb8726f03a2c7c4acd8934693/src/mumudvb.c#L1108-L1114

https://github.com/braice/MuMuDVB/blob/9c9441896b6393bcb8726f03a2c7c4acd8934693/src/mumudvb.c#L1706-L1726

**Comment by ycaibb** [comment]
Hi, developers @braice @freddy36 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by braice** [comment]
Hello

Can you tell us more about what is the issue you are seeing?

Is it from static analysis or from unexpected behavior that you had
identified this potential lock issue?

Thank you

**Comment by ycaibb** [comment]
@braice Hi, it is from a static code scan. The issue is that the lock could **chan_p.lock** is not correctly released when **mumu_init_chan(&chan_p.channels[ichan])<0** and can lead to a lock leak. I manually checked this and found it is a true positive. Can you confirm this bug?

**Comment by braice** [comment]
Indeed this is possible that it is a true positive
If you are comfortable doing so, feel free to propose a fix via a github
merge request and I can include it !

Thank you

Brice

**Comment by ycaibb** [comment]
@braice I created a PR. Please check.

Thanks~

**Comment by braice** [comment]
Hello

I'll check it out this weekend

Thank you !

**Comment by ycaibb** [comment]
Fixed by #275
