### ISSUE TITLE
"packet BAD CRC32 PID : 18" Errors on not high used Transponder

### ISSUE THREAD

**Issue by SourceDoctor** [braice/MuMuDVB#277]
@braice 
i receive continously CRC Errors with MuMuDVB on tuned Transponder which contains CNN (the only Service delivered on the whole transponder).
But a TV on same Multiswitch has no problems with receiving CNN.
also capturing with tsduck the transponder to a file and streaming CNN from it has no Errors.

i tried it with several Multiswitches, 2 different  antennas and 3 different Tuner Cards
all the same result

I use current head on a Debian Buster

**Log Output**
```
Deb0:  EIT rewrite:  New full EIT for update
Deb0:  EIT rewrite:  Full EIT updated. sid 4422 section number 1, last_section_number 1
Deb0:  EIT rewrite:  EIT sid 18176 table id 0x50 not stored, need update.
Info:  DVB:  Bit error rate:          0 Signal strength:      61929 SNR:       1524 Uncorrected blocks:          0
Info:  DVB:  ts_discontinuities          0
Deb0:  TS:  	packet BAD CRC32 PID : 18
Info:  DVB:  Bit error rate:          0 Signal strength:      61932 SNR:       1548 Uncorrected blocks:          0
Info:  DVB:  ts_discontinuities          0
Deb0:  TS:  	packet BAD CRC32 PID : 18
Info:  Main:  Traffic :  4454.55 kb/s 	  for channel "CNN Int."
Info:  DVB:  Bit error rate:          0 Signal strength:      61932 SNR:       1562 Uncorrected blocks:          0
Info:  DVB:  ts_discontinuities          0
Deb0:  TS:  	packet BAD CRC32 PID : 18
Info:  DVB:  Bit error rate:          0 Signal strength:      61929 SNR:       1552 Uncorrected blocks:          0
Info:  DVB:  ts_discontinuities          0
Deb0:  TS:  	packet BAD CRC32 PID : 18
Deb0:  EIT rewrite:  EIT sid 4422 new section 8 version : 13
Deb0:  EIT rewrite:  New full EIT for update
Deb0:  EIT rewrite:  Full EIT updated. sid 4422 section number 8, last_section_number 48

```

**configuration looks like this:**
```
card=13
freq=11626
pol=v
srate=22000
sat_number=0

delivery_system=DVBS

timeout_no_diff=3
tuning_timeout=10

rewrite_sdt=0
sort_eit=0
store_eit=1
unicast=1
ip_http=127.0.0.1
port_http=8018

multicast_ttl=10
multicast_auto_join=1
multicast_ipv4=1
multicast_iface4=vlantv

sap=0

autoconfiguration=full
autoconf_scrambled=1
autoconf_radios=1

autoconf_ip4=239.1.%sid_hi.%sid_low
common_port=1234

cam_support=0
```

even "rewrite_eit=0" does not solve the problem.
Maybe an error in Null-Pid calculation?

**Comment by braice** [comment]
I think the stone old was just not computing CRC ....

I see this issue is closed, did you found the source of the problem ?

Brice

**Comment by SourceDoctor** [comment]
i didn't find cause of the issue.
Maybe it's the driver, will be tested next.
So i closed it for for first.
Issue is really confusing.

**Comment by SourceDoctor** [comment]
btw, i could use "BAD CRC32 PID" recognization via API :-)
do you have some plans to implement it somewhere for error detection?

**Comment by braice** [comment]
I don't remember exactly but I think there is a bad packet counter in the
API that should correspond to that

On the driver side I had CRC32 issue if the lna was not activated in the
module parameters for some cards. Maybe this could give you a direction to
look for !

**Comment by SourceDoctor** [comment]
thanks for the hint.
btw. it's not the driver :/

I have the same issue on all cards of the same type and i don't think they all have been damaged at the same time.
All the years before they worked in the set up configuration without an issue.

**Comment by SourceDoctor** [comment]
@braice 
ok, i can reproduce it also in a diseqc controlled environment.
Other TunerCards, other Multiswitch, other environment other driver version.

Other DVB applications don't have this issue
e.G. dvblast

Issue causing example is:
Astra 19.2E
11626MHz
vertical
22000 kSym/s

Transponder at moment only contains CNN with 4,4Mbit/s which means above 90% Null Pids on Transpnder

Maybe some misscalculation with Null Pids?

```
/usr/local/bin/mumudvb --help
MuMuDVB is a program who can redistribute stream from DVB on a network, in multicast or in http unicast.
It's main feature is to take a whole transponder and put each channel on a different multicast IP.

Usage: mumudvb [options] 
-c, --config : Config file
-s, --signal : Display signal power
-t, --traffic : Display channels traffic
-l, --list-cards : List the DVB cards and exit
--card       : The DVB card to use (overrided by the configuration file)
--server_id  : The server id (for autoconfiguration, overrided by the configuration file)
-d, --debug  : Don't deamonize
-v           : More verbose
-q           : Less verbose
--dumpfile   : Debug option : Dump the stream into the specified file
-h, --help   : Help

MuMuDVB Version 2.1.0_20181020_mumudvb2
 --- Build information ---
Built with CAM support.
Built without SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.11.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

```

**Comment by SourceDoctor** [comment]
@braice 
there is definitly a problem.
I retried it on a small home Antenna Multiswitch Environment with CNN Transponder and have the same problem

**Comment by braice** [comment]
Hello

I gave it some thoughts and you might be on the right track about
miscalculation
The reason is that only one PID seem affected by the CRC32 issue, while
with reception issues it is spread across the whole stream

As you have your test setup up and running could you show me what CRC32
mumudvb computes (should be in the verbose logs) and what is expected and
computed from other software.
Maybe even a small TS dump might prove useful

Best

Brice

**Comment by SourceDoctor** [comment]
i logged some stuff with this command:
`mumudvb -vvv -s -t -d -c headend3_13.conf 2>&1| tee -a mumudvb_11626_v.log`

Output can be downloaded here:
[ftp://ftp.berberich.info/mumudvb_11626_v.log](url)

If you need further data, tell me :-)

**Comment by SourceDoctor** [comment]
@braice is this log enough, or do you need more information?

**Comment by braice** [comment]
Hello

After being tunnel vision on the CRC32 calculation I think I finally found
it !

It's triggering on a stuffing table which is not processed by MuMuDVB and
does not have a CRC32 in it

Can you please try to modify ts_check_raw_crc32 in ts.c and add the if
below ?
It should just ignore the CRC32 calculation for this table

Brice

int ts_check_raw_crc32(unsigned char *data)
{
    int i,len;
    uint32_t crc32;
    tbl_h_t *tbl_struct;
    tbl_struct=(tbl_h_t *)data;
    // Stuffing table does not have CRC
    if(tbl_h_t-> table_id == 0x72)
        return 0;

**Comment by SourceDoctor** [comment]
tried this one 
(show differences in if clause), but still
""
Deb0:  TS:  	packet BAD CRC32 PID : 18
```
int ts_check_raw_crc32(unsigned char *data)
{
    int i,len;
    uint32_t crc32;
    tbl_h_t *tbl_struct;
    tbl_struct=(tbl_h_t *)data;
    // Stuffing table does not have CRC
    if(tbl_struct->table_id == 0x72)
        return 0;
...
```

Nethertheless i think this if clause is not wrong on this place :-)

**Comment by braice** [comment]
And you still have
 Struct data  table_id 0x72 section_syntax_indicator 0x01 section_length
0xb4 transport_stream_id 0xffff version_number 0x1f current_next_indicator
0x01 last_section_number 0xff

just before ?

**Comment by braice** [comment]
Found it !

Should be a return 1 not a return 0 in the new piece of code

    // Stuffing table does not have CRC
    if(tbl_h_t->table_id == 0x72)
        return 1;

**Comment by SourceDoctor** [comment]
@braice 
seems the problem has been solved


```
int ts_check_raw_crc32(unsigned char *data)
{
	int i,len;
	uint32_t crc32;
	tbl_h_t *tbl_struct;
	tbl_struct=(tbl_h_t *)data;

        // Stuffing table does not have CRC
        if(tbl_strcut->table_id == 0x72)
            return 1;

	//the real length (it cannot overflow due to the way tbl_h_t is made)
	len=HILO(tbl_struct->section_length)+BYTES_BFR_SEC_LEN;

	//CRC32 calculation

	return (crc32 == 0);
}
```
