### ISSUE TITLE
SDP file?

### ISSUE THREAD

**Issue by outhud** [braice/MuMuDVB#286]
Hi, 

I have MuMuDVB working very well now to stream DVB to an RTP stream which can be played in VLC.

For ffmpeg and other tools which won't accept RTP streams directly, they need an SDP file to describe the stream.

Is there a way to generate an SDP file from MuMuDVB to go with the RTP stream?  Or does SAP do this in some way?

**Comment by braice** [comment]
Hello

SAP is a way to announce the available streams that is recognized by VLC.
It basically announce the path to the streams via an SDP like URL

You can either parse SAP announces and generate SDP files from there (there
might be tools already doing that) or having the unicast part servicing SDP
files over http

Brice

**Comment by outhud** [comment]
Thanks, I'll have a look into parsing the announces to generate an SDP file for ffmpeg.
