### ISSUE TITLE
Software descrambling with oscam on adapter grather then 8

### ISSUE THREAD

**Issue by petarslavnic** [braice/MuMuDVB#34]
I have problem with oscam and they not answering on my ticket. Can you confirm is this oscam bug? I use x4 TBS 6985 quad tuner cards.

Here is part of my mumudvb log:
WARN:  Autoconf:  Warning : No NIT found before timeout
Info:  Autoconf:  Autoconfiguration done
Info:  Autoconf:  Diffusion 2 channels
Info:  Autoconf:  Channel number :   0, name : "Nat Geo Wild CE"  service id 3490 
Info:  Autoconf:    Unicast : Channel accessible via the master connection, 0.0.0.0:5200
Info:  Autoconf:    Unicast : Channel accessible directly via 0.0.0.0:3200
Deb0:  Autoconf:          pids : 3460 (PMT), 4046 (Video (MPEG2)), 4047 (Audio (MPEG2) eng), 4064 (Audio (MPEG2) cze), 934 (Subtitling rum), 935 (Subtitling cze), 936 (Subtitling scc), 937 (Subtitling hrv), 
Info:  Autoconf:  Channel number :   1, name : "Boomerang"  service id 3500 
Info:  Autoconf:    Unicast : Channel accessible via the master connection, 0.0.0.0:5200
Info:  Autoconf:    Unicast : Channel accessible directly via 0.0.0.0:3201
Deb0:  Autoconf:          pids : 3470 (PMT), 4048 (Video (MPEG2)), 4049 (Audio (MPEG2) eng), 2021 (Audio (MPEG2) rum), 2020 (Audio (MPEG2) hun), 
Deb1:  Main:  Nat Geo Wild CE: packets in ring buffer 0, ring buffer size 65536, to descramble 0, to send 0
Deb1:  Main:  Boomerang: packets in ring buffer 0, ring buffer size 65536, to descramble 0, to send 0
Deb1:  SCAM_SEND:  Send thread started, channel Nat Geo Wild CE
Deb1:  SCAM_DECSA:  Decsa thread started, channel Nat Geo Wild CE
Deb1:  SCAM_SEND:  Send thread started, channel Boomerang
Deb1:  SCAM_DECSA:  Decsa thread started, channel Boomerang
ERRO:  SCAM_DECSA:  thread starved, channel Boomerang 0 0
ERRO:  SCAM_DECSA:  thread starved, channel Nat Geo Wild CE 0 0
Deb1:  SCAM_CAPMT:  created socket for channel Nat Geo Wild CE
Deb1:  SCAM_CAPMT:  sent CAPMT message to socket for channel Nat Geo Wild CE, toWrite=198 wrote=198
Deb1:  SCAM_CAPMT:  created socket for channel Boomerang
Deb1:  SCAM_CAPMT:  sent CAPMT message to socket for channel Boomerang, toWrite=128 wrote=128
...
...
Info:  Main:  Channel "Nat Geo Wild CE" is now higly scrambled (99% of scrambled packets). Card 12
Info:  Main:  Channel "Boomerang" is now higly scrambled (100% of scrambled packets). Card 12
Info:  Main:  Channel "Nat Geo Wild CE" back.Card 12
Info:  Main:  Channel "Boomerang" back.Card 12
Deb1:  Main:  Nat Geo Wild CE: packets in ring buffer 9288, ring buffer size 65536, to descramble 3752, to send 5536
Deb1:  Main:  Boomerang: packets in ring buffer 11985, ring buffer size 65536, to descramble 5398, to send 6587
Deb0:  EIT rewrite:  EIT sid 1036 new section 32 version : 4
Deb2:  TS:  Full packet left: 1, we remove one
Deb2:  TS:  General information PID 18 adaptation_field_control 1 payload_unit_start_indicator 1 continuity_counter 6
Deb2:  TS:  Starting a packet PID 18 cc 6 len 183 expected len 347
Deb2:  TS:  First bytes  0x50 0xf1 0x58 0x04  0x0c 0xc9 0x20 0xb8
Deb2:  TS:  Struct data  table_id 0x50 section_syntax_indicator 0x01 section_length 0x158 transport_stream_id 0x40c version_number 0x04 current_next_indicator 0x01 last_section_number 0xb8
Deb2:  TS:  General information PID 18 adaptation_field_control 1 payload_unit_start_indicator 0 continuity_counter 7
Deb2:  TS:  Continuing packet, data left 184
Deb2:  TS:  Continuing a packet PID 18 cc 7 len 347 expected 347
Deb2:  TS:  New full packet len 347. There's now 1 full packet 
Deb2:  TS:  First full packet. len 347

**Comment by byte123** [comment]
I have the same problem, 12 adapters with same configuration of mumudvb 
1-8 are working fine
the 8th and above, does not decrypt

**Comment by mcwago** [comment]
post config, channel part here, like
autoconf_sid_list=711,...

#CHANNEL HD
new_channel
service_id=711
ip=239.255.0.30
oscam=1
ring_buffer_size=32768
decsa_delay=500000
send_delay=1500000

and version u r using
did u patch kernel for more the 8 cards?
also, MAX_DEMUX for oscam source?
post your os spec, kernel uname...

**Comment by byte123** [comment]
Kernel patched:
   root@test-dvb:~# ls -al /dev/dvb/
total 0
drwxr-xr-x 14 root root  280 May 11 11:31 ./
drwxr-xr-x 15 root root 5080 May 11 11:31 ../
drwxr-xr-x  2 root root  120 May 11 11:31 adapter0/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter1/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter10/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter11/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter2/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter3/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter4/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter5/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter6/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter7/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter8/
drwxr-xr-x  2 root root  120 May 11 11:31 adapter9/

All cards are TBS6985, and are working fine on FTA channels

This is the config file, that I am using (only changing card numer)

#----------- TUNING -------------
#The DVB/ATSC card we want to use
card=11
freq=12525
pol=h
srate=30000

autoconfiguration=full
autoconf_sid_list=1003
rewrite_pat=1
rewrite_sdt=1
sort_eit=1
dont_send_scrambled=1
filter_transport_error=1
check_cc=1
port_http=10011
unicast=1
scam_support=1
lnb_voltage_off=1
unicast_queue_size=2024000
ring_buffer_default_size=131072
decsa_default_delay=10000000
send_default_delay=30000000
sap=0

#Channel 1
new_channel
ip=239.2.115.28
name=BNT 1
service_id=1003
oscam=1

On Cards 0-7 everything is fine, on cards 8-11 I receive error:
ERRO:  SCAM_DECSA:  thread starved, channel BNT 1 0 44915
ERRO:  SCAM_DECSA:  thread starved, channel BNT 1 0 44915
....
When I change the cards order on the mainboard ( dvb8 become dvb0 ), the mumudvb is working.
I had tested it with Mumudvb 1.7.3 and 2.0.0 ( 20150614 )

Kernel is:
 3.2.29-smp #2 SMP Mon Sep 17 13:16:43 CDT 2012 i686 Intel(R) Xeon(R) CPU E3-1275 v3 @ 3.50GHz GenuineIntel GNU/Linux
Slackware 14.0

**Comment by mcwago** [comment]
My problem gone with older oscam change,

What cas system u have? Viacess, irdeto, seca....? Do u have local card, or remote share? What is your decoding time, look in live log in oscam.

**Comment by mcwago** [comment]
Oscam source patched?

**Comment by byte123** [comment]
I haven't pached my oscam.
Which version do you use ?

**Comment by mcwago** [comment]
no matter which version, use latest from repo
svn checkout http://www.streamboard.tv/svn/oscam/trunk oscam-svn
cd oscam-svn
manualy patch 

Note from mumu doc:
When using oscam with more than 16 channels adjust macro definition MAX_DEMUX (line below) on oscam header **module-dvbapi.h** to number of your channels
#define MAX_DEMUX 16
finaly ->
make

**Comment by byte123** [comment]
OK, which patch ?

Saturday, May 14, 2016, 10:59:35 PM, you wrote:

no matter which version, use latest from repo
svn checkout http://www.streamboard.tv/svn/oscam/trunk oscam-svn
cd oscam-svn
manualy patch 
Note from mumu doc:
When using oscam with more than 16 channels adjust macro definition MAX_DEMUX (line below) on oscam header module-dvbapi.h to number of your channels
#define MAX_DEMUX 16
finaly ->
make
—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub

## 

Best regards,
 Anatoli Trifonov                          mailto:anatoli@globcom.net
 Network Administrator
 Unics Ltd.
 Gabrovo +359 66 803134
