### ISSUE TITLE
feature: scr/unicable/Satellite Channel Router / DIN EN 50494

### ISSUE THREAD

**Issue by jeee** [braice/MuMuDVB#46]
Please support this:
http://en.wikipedia.org/wiki/Single_cable_distribution
http://www.inverto.tv/guide/?p=12

implementation references:
http://code.mythtv.org/trac/ticket/9726
http://www.vdr-portal.de/board16-video-disk-recorder/board8-vdr-grundlagen/p941278-plugin-patch-f%C3%BCr-unicable-verf%C3%BCgbar-en-50494/#post941278
According to the creator with some changes and testing the dvbsat_scr_odu_channel_change part in this code is interesting:
http://git.linuxtv.org/v4l-utils.git/blob/HEAD:/lib/libdvbv5/dvb-sat.c

**Comment by FRIPTV** [comment]
Please support the Unicable feature, I have this unicable lnb 
http://inverto.tv/products/product.php?section=1&id=160
you can refer to this open source project 
https://gitlab.com/berdyansk/astra-sm
or this
https://bitbucket.org/cesbo/astra/commits/f8352d27e4097c22876ecd5fb516eb8a1d9b5d32
see the "unicable_setup" method in frontend.c (src\stream\dvb\frontend.c)
this is the list of possible values of uni_scr and uni_frequency parameters
Output IF Channel 1 (SCR0)  1210 MHz
Output IF Channel 2 (SCR1)  1420 MHz
Output IF Channel 3 (SCR2)  1680 MHz
Output IF Channel 4 (SCR3)  2040 MHz
I made some tests with cesbo astra and it works good!
I will send you a 50 € donation if you add this feature to mumudvb.
thanks a lot for all work you made on mumudvb.

**Comment by marian3** [comment]
Hi,

also join in the petition of support unicable.
My skills just to the following modifications "tune.c":

<pre><code>
static int diseqc_send_msg(int fd, fe_sec_voltage_t v, struct diseqc_cmd **cmd, fe_sec_tone_mode_t t, fe_sec_mini_cmd_t b, int diseqc_repeat)
{
    int err;
    if((err = ioctl(fd, FE_SET_TONE, SEC_TONE_OFF)))
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Tone OFF\n");
        return -1;
    }
    if((err = ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_18)))
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Voltage\n");
        return -1;
    }
//Wait for at least 15 ms. Currently 100 ms because of broken drivers.
    msleep(100);
    //1.x compatible equipment
    while (*cmd) {
        (*cmd)->cmd.msg_len=5;
        log_message( log_module,  MSG_DETAIL ,"Sending first Diseqc message %02x %02x %02x %02x %02x %02x len %d\n",
                (*cmd)->cmd.msg[0],(*cmd)->cmd.msg[1],(*cmd)->cmd.msg[2],(*cmd)->cmd.msg[3],(*cmd)->cmd.msg[4],(*cmd)->cmd.msg[5],
                (*cmd)->cmd.msg_len);
        if((err = ioctl(fd, FE_DISEQC_SEND_MASTER_CMD, &(*cmd)->cmd)))
        {
            log_message( log_module,  MSG_WARN, "problem sending the DiseqC message\n");
            return -1;
        }
        msleep((*cmd)->wait);
        msleep(100);
        
if((err = ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_13)))
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Voltage\n");
        return -1;
    }
        if(diseqc_repeat)
.
.
.
static int do_diseqc(int fd, unsigned char sat_no,  int switch_no, char switch_type, int pol_v_r, int hi_lo, int lnb_voltage_off, int diseqc_repeat)
{
    fe_sec_voltage_t lnb_voltage;
    struct diseqc_cmd *cmd[2] = { NULL, NULL };
    int ret;
    //Compute the lnb voltage : 0 if we asked, of 13V for vertical and circular right, 18 for horizontal and circular left
    if (lnb_voltage_off)
    {
        lnb_voltage=SEC_VOLTAGE_OFF;
        log_message( log_module,  MSG_INFO, "LNB voltage 0V\n");
    }
    else if(pol_v_r)
    {
        lnb_voltage=SEC_VOLTAGE_13;
        log_message( log_module,  MSG_INFO, "LNB voltage 13V\n");
    }
    else
    {
        lnb_voltage=SEC_VOLTAGE_18;
        log_message( log_module,  MSG_INFO, "LNB voltage 18V\n");
    }
    //Diseqc compliant hardware
    if((sat_no != 0)||(switch_no != -1))
    {
        cmd[0]=malloc(sizeof(struct diseqc_cmd));
        if(cmd[0]==NULL)
        {
            log_message( log_module, MSG_ERROR,"Problem with malloc : %s file : %s line %d\n",strerror(errno),__FILE__,__LINE__);
            set_interrupted(ERROR_MEMORY<<8);
            return -1;
        }
        cmd[0]->wait=0;
        cmd[0]->cmd.msg[0] = 0xe0;
        cmd[0]->cmd.msg[1] = 0x10;
        cmd[0]->cmd.msg[2] = 0x5A;
        cmd[0]->cmd.msg[3] = 0xD1;
        cmd[0]->cmd.msg[4] = 0xD2;
        
        if(switch_no != -1)
        {
            log_message( log_module,  MSG_INFO ,"reset lnb");
            cmd[0]->cmd.msg[3] = 0xD1;
            cmd[0]->cmd.msg[4] = 0x00;
        }
        cmd[0]->cmd.msg[5] = 0x00;
        cmd[0]->cmd.msg_len=5;
        log_message( log_module,  MSG_DETAIL ,"Test Diseqc message %02x %02x %02x %02x %02x %02x len %d\n",
.
.
.
</code></pre>

cmd.msg [3] cmd.msg [4] need to manually calculate and convert each new compilation.
Ugly solution.
Calculate D1,D2 e.g. [(http://158.255.26.180:10500/dvb%20pc/index.html)] ->Dvblast vs. unicable...
In the configuration file, always set:

<pre><code>sat_number=1
#switch_input=1      #reset_lnb_band
pol=v                       #always   </code></pre>

and the recalculated frequency,e.g. for unicable 0_1210;high_band it is 10600+1210

<pre><code>freq = 11810</code></pre>

sometimes adjustment is needed,e.g. 11806
look at what freq dvbsnoop the tuner is tuned

**Comment by braice** [comment]
Hello
I am writing the patch

I have one follow up question: how do you choose the frequency which goes
in the cable, as the unicable head will translate it ?

Then in your configuration how did you tuned the card to this frequency ?

Thank you

2016-10-21 6:06 GMT-04:00 Brice Dubost braice@braice.net:

> hello
> 
> thanks for the example code, I will clean up merge and let you tes
> 
> Brice
>

**Comment by braice** [comment]
Hello

Can you give a try to
https://github.com/braice/MuMuDVB/commit/cdd9b8dbd9f92257d268c7743fc9336f7058db8a

Thank you

2016-10-22 9:33 GMT-04:00 Brice Dubost braice@braice.net:

> Hello
> I am writing the patch
> 
> I have one follow up question: how do you choose the frequency which goes
> in the cable, as the unicable head will translate it ?
> 
> Then in your configuration how did you tuned the card to this frequency ?
> 
> Thank you
> 
> 2016-10-21 6:06 GMT-04:00 Brice Dubost braice@braice.net:
> 
> > hello
> > 
> > thanks for the example code, I will clean up merge and let you tes
> > 
> > Brice
> >

**Comment by braice** [comment]
hello

thanks for the example code, I will clean up merge and let you tes

Brice

**Comment by marian3** [comment]
Hi braice,

from my code, do not take your example, it's ugly "hack",

-unicable channel I would define differently, for example unicableset = "0:1210"

-perhaps it is necessary to send the complete DiSEqC
//1.x compatible equipment
    while (_cmd) {
        (_cmd)->cmd.msg_len=**5**;

-It is also important timing:
voltage_18...cmd....voltage_13
time 15ms may be too short
for example vdr or minisatip they have the ability to configure.

Sorry for me english.

**Comment by braice** [comment]
Hi Marian

Is the current code working or because of the timing/message lenght it
fails ?

Also were you able to fix it ?

Thank you

BRice

2016-10-25 16:31 GMT-04:00 marian3 notifications@github.com:

**Comment by braice** [comment]
I have commited some fixes, can you test

2016-11-12 18:28 GMT-05:00 Brice Dubost braice@braice.net:

**Comment by marian3** [comment]
Hi braice,

<pre><code>static int diseqc_send_msg(int fd, fe_sec_voltage_t v, struct diseqc_cmd **cmd, fe_sec_tone_mode_t t, fe_sec_mini_cmd_t b, int diseqc_repeat, char switch_type)
{
    int err;
    if((err = ioctl(fd, FE_SET_TONE, SEC_TONE_OFF)))
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Tone OFF\n");
        return -1;
    }
    if (switch_type=='N')
    {
        if((err = ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_18)))
        {
            log_message( log_module,  MSG_WARN, "problem Setting the Voltage\n");
            return -1;
        }
    } else if((err = ioctl(fd, FE_SET_VOLTAGE, v)))
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Voltage\n");
        return -1;
    }
    msleep(80);
    //1.x compatible equipment
    while (*cmd) {
        (*cmd)->cmd.msg_len=5;
        log_message( log_module,  MSG_DETAIL ,"Sending first Diseqc message %02x %02x %02x %02x %02x %02x len %d\n",
                (*cmd)->cmd.msg[0],(*cmd)->cmd.msg[1],(*cmd)->cmd.msg[2],(*cmd)->cmd.msg[3],(*cmd)->cmd.msg[4],(*cmd)->cmd.msg[5],
                (*cmd)->cmd.msg_len);
        if((err = ioctl(fd, FE_DISEQC_SEND_MASTER_CMD, &(*cmd)->cmd)))
        {
            log_message( log_module,  MSG_WARN, "problem sending the DiseqC message\n");
            return -1;
        }
        msleep((*cmd)->wait);
        msleep(15);
        if (switch_type=='N')
        {
            if((err = ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_13)))
            {
                log_message( log_module,  MSG_WARN, "problem Setting the Voltage\n");
                return -1;
            }
        }
        if(diseqc_repeat)
        {
            msleep(100);
            //Framing byte : Command from master, no reply required, repeated transmission : 0xe1
            cmd[0]->cmd.msg[0] = 0xe1;
            //cmd.msg[0] = 0xe1; /* framing: master, no reply, repeated TX */
            log_message( log_module,  MSG_DETAIL ,"Sending repeated Diseqc message %02x %02x %02x %02x %02x %02x len %d\n",
                    (*cmd)->cmd.msg[0],(*cmd)->cmd.msg[1],(*cmd)->cmd.msg[2],(*cmd)->cmd.msg[3],(*cmd)->cmd.msg[4],(*cmd)->cmd.msg[5],
                    (*cmd)->cmd.msg_len);
            if((err = ioctl(fd, FE_DISEQC_SEND_MASTER_CMD, &(*cmd)->cmd)))
            {
                log_message( log_module,  MSG_WARN, "problem sending the repeated DiseqC message\n");
                return -1;
            }
            msleep((*cmd)->wait);
        }
        cmd++;
    }
    msleep(15);
    if ((err = ioctl(fd, FE_DISEQC_SEND_BURST, b)))
    {
        log_message( log_module,  MSG_WARN, "problem sending the Tone Burst\n");
        return err;
    }
    msleep(15);
    if(ioctl(fd, FE_SET_TONE, t) < 0)
    {
        log_message( log_module,  MSG_WARN, "problem Setting the Tone back\n");
        return -1;
    }
    return 0;
}
/** @brief generate and sent the digital satellite equipment control "message",
 * specification is available from http://www.eutelsat.com/ 
 *
 * This function will set the LNB voltage and the 22kHz tone. If a satellite switching is asked
 * it will send a diseqc message
 *
 * @param fd : the file descriptor of the frontend
 * @param sat_no : the satellite number (0 for non diseqc compliant hardware, 1 to 4 for diseqc compliant)
 * @param switch_type the switch type (commited or uncommited or unicqbe)
 * @param pol_v_r : 1 : vertical or circular right, 0 : horizontal or circular left
 * @param hi_lo : the band for a dual band lnb
 * @param lnb_voltage_off : if one, force the 13/18V voltage to be 0 independantly of polarization
 */
static int do_diseqc(int fd, unsigned char sat_no,  int switch_no, char switch_type, int pol_v_r, int hi_lo, int lnb_voltage_off, int diseqc_repeat, uint32_t *fefrequency, uint32_t uni_freq)
{
    fe_sec_voltage_t lnb_voltage;
    struct diseqc_cmd *cmd[2] = { NULL, NULL };
    int ret;
    //Compute the lnb voltage : 0 if we asked, of 13V for vertical and circular right, 18 for horizontal and circular left
    if (lnb_voltage_off)
    {
        lnb_voltage=SEC_VOLTAGE_OFF;
        log_message( log_module,  MSG_INFO, "LNB voltage 0V\n");
    }
    else if(pol_v_r)
    {
        lnb_voltage=SEC_VOLTAGE_13;
        log_message( log_module,  MSG_INFO, "LNB voltage 13V\n");
    }
    else
    {
        lnb_voltage=SEC_VOLTAGE_18;
        log_message( log_module,  MSG_INFO, "LNB voltage 18V\n");
    }
    //Diseqc compliant hardware
    if((sat_no != 0)||(switch_no!=-1)||(switch_type=='N'))
    {
        if(sat_no == 0)
            sat_no = 1;
        cmd[0]=malloc(sizeof(struct diseqc_cmd));
        if(cmd[0]==NULL)
        {
            log_message( log_module, MSG_ERROR,"Problem with malloc : %s file : %s line %d\n",strerror(errno),__FILE__,__LINE__);
            set_interrupted(ERROR_MEMORY<<8);
            return -1;
        }
        cmd[0]->wait=0;
        //Framing byte : Command from master, no reply required, first transmission : 0xe0
        cmd[0]->cmd.msg[0] = 0xe0;
        //Address byte : Any LNB, switcher or SMATV
        cmd[0]->cmd.msg[1] = 0x10;
        //Command byte : Write to port group 1 (Uncommited switches)
        //Command byte : Write to port group 0 (Committed switches) 0x38
        //Command byte : Unicable switch : 5A
        if(switch_type=='U')
            cmd[0]->cmd.msg[2] = 0x39;
        else if (switch_type=='N')
            cmd[0]->cmd.msg[2] = 0x5A;
        else
            cmd[0]->cmd.msg[2] = 0x38;
        /* param: high nibble: reset bits, low nibble set bits,
         * bits are: option, position, polarization, band */
        cmd[0]->cmd.msg[3] =
                0xf0 | ((((sat_no-1) * 4) & 0x0f) | (pol_v_r ? 0 : 2) | (hi_lo ? 1 : 0));
        if(switch_no != -1)
        {
            log_message( log_module,  MSG_INFO ,"Diseqc switch position specified, we force switch input to %d\n",switch_no);
            cmd[0]->cmd.msg[3] = 0xf0 | (switch_no& 0x0f);
        }
        //
        cmd[0]->cmd.msg[4] = 0x00;
        if (switch_type=='N')
        { //Unicable, we recompute the proper messages
            //see https://patchwork.linuxtv.org/patch/7994/
            log_message( log_module,  MSG_INFO, "SCR/UNICABLE message ");
            //*fefrequency
            uint8_t channel_byte_1, channel_byte_2;
            channel_byte_1 = (uint8_t) (switch_no<<  5);
            uint16_t t;
            if (sat_no != 1)
                channel_byte_1 |= (1<<  4);
            if (!pol_v_r ) /* horizontal*/
                channel_byte_1 |= (1<<  3);
            if (hi_lo) /* high band*/
                channel_byte_1 |= (1<<  2);
            //https://code.mythtv.org/trac/attachment/ticket/9726/0001-libmythtv-Unicable-SCR-DIN-EN-50494.patch
            //seems that we will have to tune to another frequency too and adjust the voltage
            //Then we will have to tune the card to the SCR frequency as the LNB change it
            //https://patchwork.linuxtv.org/patch/7994/
            t = (uint16_t) ((((*fefrequency / 1000) + uni_freq + 2) / 4) - 350);
            channel_byte_1 |= (((uint8_t) (t>>  8))&  0x03);
            channel_byte_2 = (uint8_t) (t&  0x00FF);
            
                        cmd[0]->cmd.msg[3] = channel_byte_1;
                cmd[0]->cmd.msg[4] = channel_byte_2;
            
            if(t>1024)
                log_message( log_module,  MSG_ERROR, "SCR/UNICABLE T out of range (is the Scr frequency valid ?) ");
            log_message( log_module,  MSG_DEBUG, "Unicable tuning information : unicable freq %d lo_freq %d channel byte 0x%02x  0x%02x   t 0x%02x",
                    uni_freq, *fefrequency, channel_byte_1, channel_byte_2, t);
            //We rewrite the frontend frequency
            *fefrequency = uni_freq*1000UL;
        }
        cmd[0]->cmd.msg[5] = 0x00;
        cmd[0]->cmd.msg_len=5;
        log_message( log_module,  MSG_DETAIL ,"Test Diseqc message %02x %02x %02x %02x %02x %02x len %d\n",
                cmd[0]->cmd.msg[0],cmd[0]->cmd.msg[1],cmd[0]->cmd.msg[2],cmd[0]->cmd.msg[3],cmd[0]->cmd.msg[4],cmd[0]->cmd.msg[5],
                cmd[0]->cmd.msg_len);
        ret = diseqc_send_msg(fd,
                lnb_voltage,
                cmd,
                hi_lo ? SEC_TONE_ON : SEC_TONE_OFF,
                (sat_no) % 2 ? SEC_MINI_B : SEC_MINI_A,
                diseqc_repeat,
                switch_type);
        if(ret)
        {
            log_message( log_module,  MSG_WARN, "problem sending the DiseqC message or setting tone/voltage\n");
        }
        free(cmd[0]);
        return ret;
    }
    else    //only tone and voltage
    {
        if(ioctl(fd, FE_SET_VOLTAGE, lnb_voltage) < 0)
        {
            log_message( log_module,  MSG_WARN, "problem to set the LNB voltage\n");
            return -1;
        }
        if(ioctl(fd, FE_SET_TONE, (hi_lo ? SEC_TONE_ON : SEC_TONE_OFF)) < 0)
        {
            log_message( log_module,  MSG_WARN, "problem to set the 22kHz tone\n");
            return -1;
        }
        msleep(15);
        return 0;
    }
}
</code></pre>

to timing 18V->sleep_x->cmd:
I have Inverto  IDLB-QUDL42-UNI2L-1PP and in the timing 15ms sometimes no tuned. But it can be individually.

There superstructure unicable-> unicable II (or Jess). Up to 32 bands unicable. Later, it may finish.

Thanks.

**Comment by braice** [comment]
Hello

Can you please explain more what you did. I really have difficulties to
understand what you need.

Also I cannot read a piece of code like this without helping me on what you
did, you can provide a patch. You can highlight parts

Please try to use more words !

Thank you

2016-11-13 8:11 GMT-05:00 marian3 notifications@github.com:

**Comment by marian3** [comment]
[patch_unicable.zip](https://github.com/braice/MuMuDVB/files/587898/patch_unicable.zip)

**Comment by vladojko** [comment]
Hello,

I have tested the latest code but unfortunately I can't make my Unicable LNB tune.... If someone can help i would appreciate


root@ubuntu04:~/mumudvb/conf# mumudvb -c t0.conf -d -vvv
MuMuDVB Version 2.0.0_20150614_mumudvb2
 --- Build information ---
Built without CAM support.
Built with SCAM support.
Built with ATSC support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Deb2:  Main:  ==== Configuration file ====
Deb2:  Main:  001 #This is an example configuration file for mumudvb using full autoconfiguration
Deb2:  Main:  002 #All the commented lines are optionnal (except for tuning you have to match your system)
Deb2:  Main:  003 #If you want to set HTTP unicast, see the README and the README_CONF
Deb2:  Main:  004 #------------ TUNING -------------
Deb2:  Main:  005 #The DVB/ATSC card we want to use
Deb2:  Main:  006 card=0
Deb2:  Main:  007 #The Transponder frequency
Deb2:  Main:  008 freq=10720
Deb2:  Main:  009 # ---- SATELLITE (DVB-S) -----
Deb2:  Main:  010 #The polarisation (can be h, v, l, r)
Deb2:  Main:  011 pol=h
Deb2:  Main:  012 #The symbol rate
Deb2:  Main:  013 srate=27500
Deb2:  Main:  014 #delivery_system=DVBS2
Deb2:  Main:  015 sat_number=2
Deb2:  Main:  016 #modulation=8PSK
Deb2:  Main:  017 switch_input=2
Deb2:  Main:  018 switch_type=N
Deb2:  Main:  019 uni_freq=1420
Deb2:  Main:  020
Deb2:  Main:  021 # ----- CABLE (DVB-C) ----
Deb2:  Main:  022 #The symbol rate
Deb2:  Main:  023 #srate=27500
Deb2:  Main:  024 # ---- TERRESTRIAL (DVB-T) -----
Deb2:  Main:  025 #For DVB-T if the bandwith is 8MHz you don't have to set other parameters
Deb2:  Main:  026 #
Deb2:  Main:  027 # ----- ATSC ----
Deb2:  Main:  028 #For ATSC you could have to set the modulation if it's different from VSB_8
Deb2:  Main:  029 #
Deb2:  Main:  030 #---------- AUTOCONFIGURATION -----------
Deb2:  Main:  031 #We want the full autoconfiguration (ie we discover the channels and their pids)
Deb2:  Main:  032 autoconfiguration=full
Deb2:  Main:  033 multicast_ipv4 = 0
Deb2:  Main:  034 unicast=1
Deb2:  Main:  035 #Do we want to add the radios to the list of channels (default 0) ?
Deb2:  Main:  036 #autoconf_radios=1
Deb2:  Main:  037 #Do we want to configure channels marked as scrambled (automatically done if cam_support=1)
Deb2:  Main:  038 #autoconf_scrambled=1
Deb2:  Main:  039 #Select here if you want to stream only some services
Deb2:  Main:  040 #autoconf_sid_list=
Deb2:  Main:  041 #--------- NETWORKING --------------
Deb2:  Main:  042 #What is the "ip template"?
Deb2:  Main:  043 #Allow to select on which IP address each service will be sent
Deb2:  Main:  044 #autoconf_ip4=239.%card.%sid_hi.%sid_lo
Deb2:  Main:  045 #
Deb2:  Main:  046 #Do we want to change the default port (optionnal) ?
Deb2:  Main:  047 #common_port=4422
Deb2:  Main:  048 #
Deb2:  Main:  049 #Do we need to change the default multicast TTL (if you have routers, default value : 2) ?
Deb2:  Main:  050 #multicast_ttl=10
Deb2:  Main:  051 #
Deb2:  Main:  052 #--------- SAP ANNOUNCES --------------
Deb2:  Main:  053 #The sap announces are sent automatically with full autoconfiguration
Deb2:  Main:  054 #Do we want NOT to send the announces ?
Deb2:  Main:  055 #sap=0
Deb2:  Main:  056 #
Deb2:  Main:  057 #What is the default playlist group for the SAP announces (optionnal) ?
Deb2:  Main:  058 #sap_default_group=My channels
Deb2:  Main:  059 #Who is the organisation wich send the stream (optionnal) ?
Deb2:  Main:  060 #sap_organisation=my_organisation
Deb2:  Main:  061 #The intervall between the SAP announces in second (default 5)
Deb2:  Main:  062 #sap_interval=10
Deb2:  Main:  063 # ---------- SCRAMBLED CHANNELS ----------
Deb2:  Main:  064 #Do we want hadware descrambling ?
Deb2:  Main:  065 #cam_support=1
Deb2:  Main:  066 #
Deb2:  Main:  067 #If you have multiple CAMs you can specify the number of the one wich will be used
Deb2:  Main:  068 #cam_number=2
Deb2:  Main:  069
Deb2:  Main:  070 #scam_support=1
Deb2:  Main:  071
Deb2:  Main:  072 #new_channel
Deb2:  Main:  073 #oscam=1
Deb2:  Main:  ============ done ===========
Info:  Main:  Autoconfiguration, we activate SAP announces. if you want to disable them see the README.
Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
Info:  Main:  Streaming. Freq 10720000
Info:  Tune:  Using DVB card "TurboSight TBS 6902 DVB-S/S2 " tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 970000 kHz, LO frequency 9750000 kHz Pol:H Srate=27500000, LNB number: 2
Info:  Tune:  LNB voltage 18V
Info:  Tune:  Diseqc switch position specified, we force switch input to 2
Info:  Tune:  SCR/UNICABLE message
Deb1:  Tune:  Unicable tuning information : unicable freq 1420 lo_freq 970000 channel byte 0x58  0xf8   t 0xf8
Deb0:  Tune:  Test Diseqc message e0 10 5a f2 00 00 len 5
Deb0:  Tune:  Sending first Diseqc message e0 10 5a f2 00 00 len 4
Info:  Tune:  DISEQC SETTING SUCCEDED
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
Deb0:  Tune:  polling....
Info:  Tune:  FE_STATUS:
^C
root@ubuntu04:~/mumudvb/conf#

**Comment by braice** [comment]
Hello

Thank to the patch I fixed a bug in the code (it could not work before)

Can you try again ?

Thank you

Brice


2016-12-08 4:28 GMT-05:00 vladojko <notifications@github.com>:

**Comment by vladojko** [comment]
Yes it works now! Thanks a lot!
So I guess the next step is now to support Unicable II/Jess ;-)

**Comment by braice** [comment]
Any doc on Unicable II ?

2016-12-14 3:52 GMT-05:00 vladojko <notifications@github.com>:
