### ISSUE TITLE
DVB-T2 config issue

### ISSUE THREAD

**Issue by dtcmumuuser** [braice/MuMuDVB#55]
Dear developer!
I installed mumudvb from git. I supposed it would be 2.0, but it shows version 1.7.3 built with DVB-T2 support. I try to lock with this config options
delivery_system=DVBT2
freq=514
bandwidth=10MHz
unicast=1
port_http=10007
card=2
I get
"Info:  Tune:  You will use DVB API version 5 for tuning your card.
ERRO:  Tune:  Config issue : bandwidth"
Your configuration Readme shows 5Mhz, 10Mhz, 1.712Mhz options for DVB-T2 bandwidth. However, only 6Mhz or 8Mhz seem to be applicable. Those are not the right values for DVB-T2, but right ones, 5 or 10, give an error.
When I omit bandwidth option the default 8Mhz is used and of course the card cannot tune
Info:  Tune:  Tuning DVB-T to 514000000 Hz, Bandwidth: 8000000
Info:  Tune:  Tuning With DVB-API version 5. delivery system : 16
ERRO:  Tune:  FE_SET_PROPERTY failed : Invalid argument
Info:  Main:  Tunning issue, card 2
Info:  Main:  Closing cleanly. Error 7
Info:  Main:  ========== MuMuDVB version 1.7.3_20131116_master is stopping with ExitCode 7 ==========
Please help.
Best wishes,
Pavel.

**Comment by tizen-wissem** [comment]
good morning
