### ISSUE TITLE
descrambling issue with mumudvb using oscam

### ISSUE THREAD

**Issue by morsino** [braice/MuMuDVB#56]
Hello,

Mumudvb stop descrambling channels after 5-10 minutes, oscam is running and connected to dvbapi, but i don't undersand why doesn't mumudvb continue descrambling channels even with oscam connected, i have to run mumudvb -d -c mychannelconfig.txt to resume manually the channel.

is there a solution for that ?

i'm using mumudvb 1.7.2

Regards,
Morsi

**Comment by xforze** [comment]
Hi All,

I have also an issue with getting my hardware cam working.
Where can I find the mailing archive ?
And where can I sent support questions to ?

Best Regards, Thomas

**Comment by braice** [comment]
The list archives are here
https://lists.crans.org/listinfo/mumudvb-dev

Are you able to see your cam with gnutv -cammenu ?

2015-05-10 11:39 GMT+02:00 xforze <notifications@github.com>:

**Comment by xforze** [comment]
Hi  Braice,

Thank you for your answer.

Yes, it shows the cam menu (viaccess module is plugged in):
root@odroid:~# gnutv -cammenu
CAM Application type: 01
CAM Application manufacturer: cafe
CAM Manufacturer code: babe
CAM Menu string: Viaccess Access
CAM supports the following ca system ids:
  0x0500
  0x0502
------------------------------
Viaccess Conditional Access
Main Menu
0. Quit menu
1. Consultation
2. Settings
3. Upgrade
Press 'OK' to confirm, 'EXIT' to quit
Enter option:

Here is the output of "cat /var/run/mumudvb/caminfo_adapter0_tuner0"
CAM_Application_Type=01
CAM_Application_Manufacturer=cafe
CAM_Manufacturer_Code=babe
CAM_Menu_String=Viaccess Access
ID_CA_Supported=0500
ID_CA_Supported=0502

Here is the output of "cat /var/run/mumudvb/channels_streamed_adapter0_tuner0"
239.100.0.0:1234:SCT7:HighlyScrambled
239.100.0.1:1234:SCT HD:HighlyScrambled
239.100.0.2:1234:SEXY SAT ALGERIE:FullyUnscrambled
239.100.0.3:1234:TELESUR:FullyUnscrambled
239.100.0.4:1234:Redlight:HighlyScrambled
239.100.0.5:1234:EXOTICA TV:HighlyScrambled
239.100.0.6:1234:SCT 5:HighlyScrambled
239.100.0.7:1234:SCT 6:HighlyScrambled
239.100.0.8:1234:SCT 7:HighlyScrambled
239.100.0.9:1234:SCT HQ:HighlyScrambled
239.100.0.10:1234:PLATINUM:FullyUnscrambled
239.100.0.11:1234:SCT PROMO b:FullyUnscrambled
239.100.0.12:1234:SCT PROMO c:FullyUnscrambled
239.100.0.13:1234:SCT PROMO d:FullyUnscrambled
239.100.0.14:1234:SCT PROMO e:FullyUnscrambled
239.100.0.15:1234:SCT PROMO f:FullyUnscrambled
239.100.0.16:1234:SCT PROMO g:FullyUnscrambled
239.100.0.17:1234:SCT PROMO h:FullyUnscrambled
239.100.0.18:1234:SCT PROMO i:FullyUnscrambled
239.100.0.19:1234:SCT PROMO j:FullyUnscrambled
239.100.0.20:1234:SCT PROMO k:FullyUnscrambled
239.100.0.21:1234:SCT PROMO l:FullyUnscrambled
239.100.0.22:1234:SCT PROMO m:FullyUnscrambled
239.100.0.23:1234:SCT PROMO n:FullyUnscrambled
239.100.0.24:1234:SCT PROMO o:FullyUnscrambled
239.100.0.25:1234:PINK O TV:HighlyScrambled
239.100.0.26:1234:HB SEXYSAT 2:FullyUnscrambled
239.100.0.27:1234:Citta Italia HD:FullyUnscrambled
239.100.0.28:1234:TV Record EEUU:FullyUnscrambled

This is my config file (want to descramble SCT7):
unicast=1
freq=11727
pol=v
srate=27500
#autoconf_radios=0
autoconfiguration=full
multicast_ttl=16
dvr_buffer_size=10
dvr_thread=1
dvr_thread_buffer_size = 5000
sat_number = 3
diseqc_repeat = 1
cam_support=1

#autoconf_scrambled=1

new_channel
pids = 4700 4701

ip=239.100.0.0
port=1234
name=SCT7
port1

Im using the newest mumudvb build:
MuMuDVB Version 2.0.0_20150103_mumudvb2
 --- Build information ---
Built with CAM support.
Built with SCAM support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.10.
Built with support for DVB-T2.
---------

I started mumudvb with -vvv. As the output is very big, I uploaded the log file here
http://xxa.biz/log

How can I see if the channel is unscrambled ?
Is the channel listed as unscrambled in "/var/run/mumudvb/channels_streamed_adapter0_tuner0" ?

Best regards, Tom

**Comment by braice** [comment]
Hello

It's a bug from your provider, the flag free_ca_mode is improperly set
*free_CA_mode*: This 1-bit field, when set to "0" indicates that all the
component streams of the service are not scrambled.

it's 0 for all your channels

Can you change in mumudvb_channel.c line 217
if(auto_p->autoconf_scrambled && chan_p->channels[ichan].free_ca_mode)

by

if(auto_p->autoconf_scrambled && 1)

And give the log back an tell if it works !

Best

Brice

2015-05-11 22:44 GMT+02:00 xforze <notifications@github.com>:

**Comment by xforze** [comment]
Hi Brice, 

I made the changes to mumudvb_channel.c line 217 and recompiled it.
But it seems that it makes no difference as you can see here (new log file uploaded ) http://xxa.biz/log
I have a xtratv (conax) card and Sky (NDS) card with CI as well. I can give a try with one of these cards.

Best regards, Thomas

**Comment by braice** [comment]
Hello

You need to wait more, now the channels are asked to the cam

Deb1:  CAM:  CA_Info_Callback: 2 CA systems supported
Deb0:  CAM:  CAM supports the following ca system ids:
Deb0:  CAM:  Ca system id 0x0500 : France Telecom
Deb0:  CAM:  Ca system id 0x0502 : France Telecom
Deb0:  TS:  GOOD service_id for PMT 74 and channel "SCT PROMO n"
Info:  CAM:  Received new PMT - sending to CAM...
Info:  CAM:  CA PMT (ADDED) sent for channel 23 : "SCT PROMO n"
Deb0:  TS:  GOOD service_id for PMT 58 and channel "SCT HD"
Info:  CAM:  Received new PMT - sending to CAM...
Info:  CAM:  CA PMT (ADDED) sent for channel 1 : "SCT HD"
Deb0:  TS:  GOOD service_id for PMT 75 and channel "SCT PROMO o"
Info:  CAM:  Received new PMT - sending to CAM...
Info:  CAM:  CA PMT (ADDED) sent for channel 24 : "SCT PROMO o"
Info:  Main:  End of streaming. We streamed during 0d 0:00:19


2015-05-14 20:44 GMT+02:00 xforze <notifications@github.com>:

**Comment by xforze** [comment]
Hi !!

The new log looks better: http://xxa.biz/log
there some lines like "Channel "SCT 6" is now fully unscrambled (0% of scrambled packets)"

But:
cat /var/run/mumudvb/channels_streamed_adapter0_tuner0 |grep "SCT 6
shows:
"239.100.0.7:1234:SCT 6:HighlyScrambled"

The other chanels are "HighlyScrambled" as well.

Regards, Thomas

**Comment by zavazingo** [comment]
CI can't decode 2 stream at the same time. Just choose one stream or use oscam with cardsharing if you want to decode whole package channels.

**Comment by xforze** [comment]
Thank you zavazingo for this information.
Because of this, I switched to oscam and have a working setup now :-)

Just one question:

If I want to stream only one channel, I have to switch autoconfiguration=0 and add a new channel like this:

new_channel
pids = 4700 4701
ip=239.100.0.0
port=1234
name=SCT7
oscam=1

If I run this configuration, I get the following warning:
WARN:  SCAM_COMMON:  channel 0 with SCAM support and no PMT set I disable SCAM support for this channel

How can I get the pid_pmt value ?

Cheers !

**Comment by braice** [comment]
Use Autoconf_sid_list and full autoconfiguration, it is safer

**Comment by xforze** [comment]
Great !!

Thank you for this, working fine now :-)

**Comment by braice** [comment]
Perfect !

**Comment by sirk98** [comment]
Hi dear,

I have build a little dvb streaming server using mumudvb and I can watch DTT free channel, but I can't watch scrambled channel .
Here my config 

# Adapter 0
# 
#
freq=754000
tuner=0
multicast=0
multicast_ipv4=0
multicast_ipv6=0
scam_support=1
autoconfiguration=full
autoconf_scrambled=1
autoconf_unicast_start_port
autoconf_unicast_port
oscam=1
unicast=1
ip_http=192.168.1.254
#

I've compiled oscam and installed it with dvbapi support ( oscam works perfectly ). I installed libdvbcsa, but scrambled channel are always off .
Can someone help me.. 
Best regards,
sirk98

**Comment by ghost** [comment]
Hello.

> You should find info in the archives of the mailing list, which I put in
copy so people can share their working configurations

Does the archives work anymore?
I think not. Could we access them somehow?
Thanks!
