### ISSUE TITLE
MuMuDVB for MIPS and PowerPC arch with CI with CAM and SCAM support

### ISSUE THREAD

**Issue by ghost** [braice/MuMuDVB#67]
Hello,

I would like to ask your opinion/permission about what I did. Basically I am using drone.io as a build server to compile, build and pack mumudvb for OpenWRT on both mips and powerpc arch with CAM/SCAM support.

Please have a look:
https://github.com/Gorkhaan/mumudvb-mips
https://github.com/Gorkhaan/mumudvb-powerpc

I couldn't find your contact so I created an Issue. Feel free to remove it.

Kind Regards,
G.

**Comment by braice** [comment]
It's very interesting, do you have an idea how to include you work
mainstream ? I don't know a log about drone.io so I think your opinion will
be better than mine on this subject.

Thank you

2014-06-28 0:47 GMT+02:00 Gorkhaan <notifications@github.com>:
