### ISSUE TITLE
ATSC EPG

### ISSUE THREAD

**Issue by joolzg** [braice/MuMuDVB#84]
I have a block of streams, 8 in total and need to add pids so I can decode ATSC EPG.

2 streams checked and

stream 1 needs 0x1ffb, 0x1488, 0x1388 to 0x130f and 0x1408 to 0x140f
stream 2 needs 0x1ffb, 0x1000 to 0x1007 and 0x1200 to 0x1207

Any ideas on doing this?

**Comment by braice** [comment]
Hello

Can you detail a bit more :
What is the type of the PIDs you want to add (so they could be seen by
autoconf)? If you don't know, please give the logs in full autoconf and
verbose
In case you want to do it manually, what version are you using ?

Best

Brice


2015-01-21 11:55 GMT+01:00 Julian Gardner <notifications@github.com>:

**Comment by joolzg** [comment]
Thats the problem as we need to decode the 0x1ffb pid to get the list of pids needed for the EPG decoding.

I will try and find more info out as I have just started looking into this myself.

joolz

**Comment by braice** [comment]
Please have a look to
https://github.com/braice/MuMuDVB/blob/b8c65e257432f34a3415cf1f1237ffd3b4b97b78/src/autoconf_atsc.c
This PID is already parsed by MuMuDVB,

If you can also find the norm describing how to get the EPG PIDs please
tell.

2015-01-21 22:30 GMT+01:00 Julian Gardner <notifications@github.com>:
