### ISSUE TITLE
Request on reciving MPTS instead of dvb signal

### ISSUE THREAD

**Issue by davoudafshari** [braice/MuMuDVB#86]
As I know, mumudvb is a very stable and full feature on streaming dvb signals toIP networks. I am very satisfied to use it in my network. But I suggest to add De multiplexing of MPTS streams to SPTS channels(services) by this software because this is a killing feature in IPTV environments.
This must be easy to find service and channels and maybe the problem will be in reading MPTS from IP network. I mean the source will change to IP Stream instead of dvb card. 
Any comment and help will be appreciated!

**Comment by braice** [comment]
Hello
It is clearly feasible, probably would need some code cleanup to make
abstraction of the stream source but shouldn't be a big issue

Do you have architectures in mind or test set-up. ?

I can clearly help you to developp is you have knowledge in C could make it
go faster

Best

2015-01-26 12:24 GMT+01:00 davoudafshari <notifications@github.com>:
