### ISSUE TITLE
Mumudvb and oscam not decrypting

### ISSUE THREAD

**Issue by emmelmann** [braice/MuMuDVB#88]
Hi,

I have a problem using mumudvb and oscam.
in oscam logs i see it finds it ecms, but mumudvb is not decrypting.

Oscam Logs:
2015/05/27 10:17:10 2339E60 c (ecm) mumudvb (0100&00006C/5C00/1B90/64:B0A178C79AE892BCD3D9382916F16FB9): found (868 ms) by Reader-1
2015/05/27 10:17:10 2339E60 c (ecm) mumudvb (0100&00006C/5C00/1B91/64:982217130B2D96A214F7DF57DE2FEC87): found (915 ms) by Reader-1
2015/05/27 10:17:10 2339E60 c (ecm) mumudvb (0100&00006C/5C00/1B76/64:5438212B51FB23554A4D07A562743C17): found (978 ms) by Reader-1
2015/05/27 10:17:10 2339E60 c (ecm) mumudvb (0100&00006C/5C00/1B91/64:4F3158039F78C0C0E31C8C94BBABD104): found (449 ms) by Reader-1
2015/05/27 10:17:11 2339E60 c (ecm) mumudvb (0100&00006C/5C00/1B76/64:DEEDEAF1B7B0E55733DAE1D79972ADFA): found (439 ms) by Reader-1

mumudvb logs:
Info:  Main:  Channel "VTM HD" is now highly scrambled (98% of scrambled packets). Card 1
Info:  Main:  Channel "2BE HD" is now highly scrambled (98% of scrambled packets). Card 1
Info:  Main:  Channel "VIER HD" is now highly scrambled (100% of scrambled packets). Card 1

can you help please?

thank you

**Comment by zavazingo** [comment]
1 - try to decode one channel first specially sd channel instead hd.
2 - run mumudvb like " -d -vvv -c /root/your_mumudvb.conf " for more verbose log.
3 - key delay is too much according to me. 
a - check net connection.
b - change oscam peer for stable keys.

**Comment by emmelmann** [comment]
hi zavazingo!

tried with sd channel, but stays te same.
when i enable more verbose logging, i only see this:
Deb1:  Main:  Vitaya: packets in ring buffer 2511, ring buffer size 32768, to descramble 938, to send 1573
Deb1:  Main:  Vitaya: packets in ring buffer 2788, ring buffer size 32768, to descramble 954, to send 1834
Deb1:  Main:  Vitaya: packets in ring buffer 2731, ring buffer size 32768, to descramble 874, to send 1857
Deb1:  Main:  Vitaya: packets in ring buffer 2227, ring buffer size 32768, to descramble 654, to send 1573

key delay is now about 350ms

what can i check more?

**Comment by zavazingo** [comment]
Seems channel decoded if you didn't got fake key. How do you try to view channel? Unicast? Multicast?
And can you post full or partial mumudvb configuration and log please...

**Comment by emmelmann** [comment]
this is my config:
card=1
sat_number=3
delivery_system=DVBS2
unicast=1
multicast_ipv4=0
multicast=0
freq=12129
pol=v
srate=27500

autoconfiguration=full
scam_support=1
autoconf_sid_list=21120

channel_next
oscam=1

#channel_next
#oscam=1

#channel_next
#oscam=1

**Comment by emmelmann** [comment]
here is my mumudvb output
http://pastebin.com/zrRZj3Z4

**Comment by zavazingo** [comment]
Keep it simple first.
No need to;

delivery_system=DVBS2 (specially that one)
channel_next
oscam=1

**Comment by emmelmann** [comment]
ok commented above lines, still the same.. :(
anything else i can try?
do you need my output again?

**Comment by zavazingo** [comment]
I missed that you are still trying to decode DVB-S2... Please find DVB-S channel/frequency (http://en.kingofsat.net/sat-astra3b.php) or tune it to another satellite for test. DVB-S2 is really annoying at decoding.

**Comment by emmelmann** [comment]
hi just tried tuning and decrypt dvb-s channel, but stil the same, it finds it on oscam.. but doesn't decrypt..

**Comment by zavazingo** [comment]
1 - Do you able to see fta channels?
2 - Oscam solve encryption?
3 - Can you upload log?

I think better to reinstall / compile new mumudvb2 instead old stable, oscam, libdvbcsa...

**Comment by emmelmann** [comment]
fta is working perfect, also with hardware cam.

oscam log:
14:46:58        0 s >> OSCam <<  cardserver started, version 1.20-unstable_svn, build r10665 (x86_64-linux-gnu)
14:46:58        0 s     (main) System name    = Linux
14:46:58        0 s     (main) Host name      = xxxxx-SAT2
14:46:58        0 s     (main) Release        = 3.16.0-30-generic
14:46:58        0 s     (main) Version        = #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
14:46:58        0 s     (main) Machine        = x86_64
14:46:58        0 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 18448
14:46:58        0 s   (config) userdb reloaded: 2 accounts loaded, 0 expired, 0 disabled
14:46:58        0 s     (main) signal handling initialized
14:46:58        0 s      (net) cs378x: initialized (fd=4, port=2233)
14:46:58        0 s      (net) newcamd: initialized (fd=5, port=5555)
14:46:58        0 s      (net) -> CAID: 0100 PROVID: 00006C
14:46:58        0 s   (reader) Reader-1 [cccam] creating thread for device xxxxxxxxxxx
14:46:58        0 s     (stat) loadbalancer: could not open /tmp/.oscam/stat for reading (errno=2 No such file or directory)
14:46:58        0 s     (main) waiting for local card init
14:46:58 280008C0 h    (webif) webif: decompressed 152292 bytes back into 365952 bytes
14:46:58 280008C0 h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
14:46:58   924EC0 p   (reader) xxxxxx: resolved ip=xxxxxx
14:46:58   924EC0 p   (reader) Reader-1 [cccam] connecting to xxxxxxx:12000
14:46:59   924EC0 p   (reader) Reader-1 [cccam] proxy initialized, server teve.emmelmann.be:12000
14:46:59        0 s     (main) init for all local cards done
14:46:59        0 s (emmcache) loading emmcache disabled since no reader is using it!
14:46:59        0 s (emmcache) loading emmstats disabled since no reader is using it!
14:46:59        0 s (anticasc) anti cascading disabled
14:46:59   9258B0 c   (client) plain dvbapi-client granted (mumudvb, au=off)
14:46:59   9258B0 c   (dvbapi) dvbapi channelcache loaded from /usr/local/etc/oscam.ccache
14:46:59   9258B0 c   (dvbapi) Using /tmp/camd.socket listen socket, API forced to DVBAPIv3 (0), userconfig boxtype: 11
14:47:30   924EC0 p   (reader) Reader-1 [cccam] disconnected: reason inactivity
14:48:09   9258B0 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0D96 ECM_PID: 005F PROVID: 000000
14:48:09   9258B0 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0624 ECM_PID: 0060 PROVID: 000000
14:48:09   9258B0 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0666 ECM_PID: 0061 PROVID: 000000
14:48:09   9258B0 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0B00 ECM_PID: 0063 PROVID: 000000
14:48:09   9258B0 c   (dvbapi) Demuxer 0 found 4 ECMpids and 4 STREAMpids in PMT
14:48:09   9258B0 c   (dvbapi) Demuxer 0 serving srvid 36F8 (0D96:36F8 unknown) on adapter 0001 camask 0002 index 0000 pmtpid 0000
14:48:09   9258B0 c   (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 0 
14:48:09   9258B0 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0D96 PROVID 000000 ECMPID 005F ANY CHID PMTPID 0000 VPID 1C2A
14:48:10   924EC0 p   (reader) Reader-1 [cccam] connecting to xxxxxxxxxx:12000
14:48:15   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:405B8DEE6CB1C36CBB1C6988FA516EAD): timeout (5001 ms) by Reader-1
14:48:17   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:CF4756798D8BDAD5E0425ADE1EE2EAA4): found (269 ms) by Reader-1
14:48:17   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:405B8DEE6CB1C36CBB1C6988FA516EAD): found (2735 ms) by Reader-1
14:48:27   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:7EB470278C8CE04E3B611C9C5304303A): found (270 ms) by Reader-1
14:48:37   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:8A4ADB88D2A0190E2F3FC350BACC8367): found (269 ms) by Reader-1
14:48:47   9258B0 c      (ecm) mumudvb (0D96&000004/0000/36F8/80:09D28147943926E27D1806CBDFF106F2): found (279 ms) by Reader-1
^C14:48:49 280008C0 h    (webif) HTTP Server stopped
14:48:49        0 s   (dvbapi) dvbapi channelcache saved to /usr/local/etc/oscam.ccache
14:48:49        0 s (emmcache) saving emmcache disabled since no reader is using it!
14:48:49        0 s (emmcache) saving emmstats disabled since no reader is using it!
14:48:49        0 s   (client) killing client mumudvb
14:48:49        0 s   (reader) Reader-1 [cccam] Killing reader
14:48:49        0 s   (config) userdb 2 accounts freed
14:48:49        0 s   (config) readerdb 2 readers freed
14:48:49        0 s     (main) cardserver down

**Comment by emmelmann** [comment]
hi updated to mumudvb2. works out of the box now.
thank you for your help!
