### ISSUE TITLE
add_ts_packet_data in ts.c fails when the first section chunk is less than 3 bytes

### ISSUE THREAD

**Issue by JGRennison** [braice/MuMuDVB#90]
add_ts_packet_data gets the length in the START_TS/START_SECTION block as tbl_struct->section_length. This is in byte offsets 1 and 2 from buf. If data_left is less than 3, this will read off the end of the buffer, and cause the length in pkt->expected_len_partial to be wrong.
UK DVB-T EIT tables seem to frequently trigger this bug, which results in badly mangled EIT output whenever the sort_eit switch is enabled.

Less urgently, the MSG_FLOOD log messages at the end of the block produce wrong logging output if data_left is less than 8.

A possible fix would be to delay table length calculation and logging until at least 3 or 8 bytes have been collected. I may have a go at writing a fix.

**Comment by braice** [comment]
Hello

Thank you for the report

If you write a fix I'll be happy to integrate it, otherwise I should be
able to write some within next week or so

Best

Brice


2015-06-16 22:00 GMT+02:00 Jonathan G Rennison <notifications@github.com>:
