### ISSUE TITLE
mumudvb-oscam only descrambling one tuner 

### ISSUE THREAD

**Issue by ashuprabhaker** [braice/MuMuDVB#93]
I got three scrambled transponders , First on Tuner 11 , 26 and 27 .

When i start oscam , its perfectly descramble channels on card 11 , But on card 26 and card 27 , i can see Codes are going from oscam , buts channels are not clearing up in mumudvb on tuners 26 and 27 .

I am using all latest drivers available , Tried different versions of mumudvb , still all same .

I changed max demux in oscam to support more channels , however still i am trying to descramble in total of 8 channels , 

While decrypting this is the logs from mumudvb for tune 26 and 27 :-
Info: SCAM_CAPMT: sent CAPMT message to socket for channel CHANNEL I, toWrite=169 wrote=169
Info: Main: Channel "CHANNEL I" down.Card 26
Info: Main: Channel "CHANNEL I" is now highly scrambled (99% of scrambled packets). Card 26
Info: Main: Channel "CHANNEL I" back.Card 26

While mumudvb stay like this , oscam sending ecm to clear up channels .

Any help guys .

card=26

autoconf_sid_list=60001 60019
lnb_type=universal
lnb_lof_standard=10750
lnb_slof=11700
lnb_lof_low=9750
lnb_lof_high=10600

timeout_no_diff=0
tuning_timeout=0

multicast_ipv4=0
unicast=1

autoconf_scrambled=1
dvr_buffer_size=40
dvr_thread=1

This same config if i use for card 11 works fine.

Thanks

**Comment by ostryck** [comment]
Please try with this mumudvb version https://github.com/ostryck/MuMuDVB,
and oscam rev 9870, also please send debug log with -vvv.
Cheers,
Ostryck

2015-06-23 7:54 GMT+02:00 ashuprabhaker <notifications@github.com>:

**Comment by ashuprabhaker** [comment]
Its still same with mumudvb version https://github.com/ostryck/MuMuDVB,
and oscam rev 9870,

Here are the logs     http://50.3.230.108/errormum.txt

**Comment by ashuprabhaker** [comment]
I figured out the issue , As i got 28 Tuners in one system , apparently mumudvb-oscam , can descramble up-to 16 Tuners simultaneously after that , descrambling part does not work.

**Comment by zavazingo** [comment]
[NOTE] 
When using oscam with more than 16 channels adjust macro definition `MAX_DEMUX` (line below) on oscam header `module-dvbapi.h` to number of your channels
------------------------------
#define MAX_DEMUX 16
------------------------------

**Comment by ashuprabhaker** [comment]
@zavazingo  Thanks for comment sir , 

Please read issue properly , My Oscam #define MAX_DEMUX 64 , Moreover , my problem is not with the no of channels , its the no of tuners ,.

Thanks
