### ISSUE TITLE
Reduce CPU usage when using only unicast and there are no clients connected.

### ISSUE THREAD

**Issue by joeusercz** [braice/MuMuDVB#96]
Hi, I just started looking at the code to see if there is a way to reduce CPU usage when using only unicast and there are no clients clients connected. As it is now, MuMuDVB uses about 10-13% CPU whether or not any clients are connected. Since most of the time I have no clients connected, it would be useful to reduce that cpu usage. Maybe a flag could be set and it would just dump packets after autoconfiguration is done if there are not any unicast clients connected? It would be even better to stop the card altogether when there are no clients, but by my first look at the code, I think that would be much more difficult to implement.

**Comment by braice** [comment]
Hello

Where you able to trace where the time is spent, is it on interrupts or
other stuff ?

Maybe I need to poll the descriptors less often or something like this
(like for the DVB card)


2015-07-27 15:11 GMT+02:00 joeusercz <notifications@github.com>:

**Comment by joeusercz** [comment]
I disabled the monitor and that reduced it by almost half. I haven't had time to debug further.. 

Maybe the rewrite pat/sdt is still being done? 

If I have time later in the week, I will look again.
