### ISSUE TITLE
autoconf_pid_update not implemented?

### ISSUE THREAD

**Issue by joeusercz** [braice/MuMuDVB#97]
Hi, when I tried to set the "autoconf_pid_update" option in the config that is mentioned in the "README_CONF", I get a warning 
```
WARN:  Main:  Config issue : unknow symbol : autoconf_pid_update
```
And indeed when I look at the code, it doesn't seem to exist. Maybe it was an old option which was removed??

**Comment by braice** [comment]
Yes it's an old version option, can you tell me:

Which readme conf ? accessed from where ? for which version of MuMuDVB ?

Thank you

2015-07-27 15:17 GMT+02:00 joeusercz <notifications@github.com>:

**Comment by joeusercz** [comment]
http://www.mumudvb.net/doc/mumudvb-2.0.0/README_CONF.html
